import { BiomethanePlant } from './types';

export const VERIFIED_COMMERCIAL_PLANTS: BiomethanePlant[] = [
  // Denmark (DK)
  {
    id: 'dk-korskro',
    name: 'Nature Energy Korskro',
    country: 'Denmark',
    countryCode: 'DK',
    countryFlag: '🇩🇰',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'South Denmark (Esbjerg)',
    operator: 'Nature Energy Biogas A/S (Shell)',
    commissioningYear: 2018,
    capacityNm3h: 3800,
    annualEnergyGWh: 240.0,
    primaryFeedstockCategory: 'Manure & Agricultural residues',
    feedstockDetails: 'Deep cattle & pig slurry (75%), straw bedding & agricultural biowaste (25%)',
    upgradingTechnology: 'Water wash scrubbing (Greenlane)',
    gridConnectionType: 'Transmission (TSO high-pressure)',
    networkOperator: 'Energinet',
    certificationAndRegistry: 'ISCC EU · Energinet Biometangasregister (UDB Ingested)',
    primaryOfftake: 'Cross-border transport / German THG & Dutch ERE compliance',
    coordinates: [8.591, 55.518],
  },
  {
    id: 'dk-holsted',
    name: 'Nature Energy Holsted',
    country: 'Denmark',
    countryCode: 'DK',
    countryFlag: '🇩🇰',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'South Denmark (Vejen)',
    operator: 'Nature Energy Biogas A/S (Shell)',
    commissioningYear: 2016,
    capacityNm3h: 2900,
    annualEnergyGWh: 185.0,
    primaryFeedstockCategory: 'Manure & Agricultural residues',
    feedstockDetails: 'Dairy manure slurry (80%), agro-industrial organic waste (20%)',
    upgradingTechnology: 'Water wash scrubbing',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Energinet',
    certificationAndRegistry: 'ISCC EU · Energinet Biometangasregister',
    primaryOfftake: 'Industrial heat & transport compliance',
    coordinates: [8.915, 55.510],
  },
  {
    id: 'dk-glansager',
    name: 'Nature Energy Glansager',
    country: 'Denmark',
    countryCode: 'DK',
    countryFlag: '🇩🇰',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'South Denmark (Sønderborg)',
    operator: 'Nature Energy Biogas A/S (Shell)',
    commissioningYear: 2020,
    capacityNm3h: 3100,
    annualEnergyGWh: 195.0,
    primaryFeedstockCategory: 'Manure & Agricultural residues',
    feedstockDetails: 'Swine & cattle slurry, sugar beet pulp, clover grass',
    upgradingTechnology: 'Membrane separation (Evonik SEPURAN®)',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Energinet',
    certificationAndRegistry: 'ISCC EU · Energinet Biometangasregister',
    primaryOfftake: 'Cross-border virtual swap to Trading Hub Europe',
    coordinates: [9.840, 54.935],
  },
  {
    id: 'dk-kalundborg',
    name: 'Bigadan Kalundborg Biogas',
    country: 'Denmark',
    countryCode: 'DK',
    countryFlag: '🇩🇰',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Zealand (Kalundborg)',
    operator: 'Bigadan A/S & Novo Nordisk Symbiosis',
    commissioningYear: 2019,
    capacityNm3h: 2400,
    annualEnergyGWh: 155.0,
    primaryFeedstockCategory: 'Industrial biowaste & Slurry',
    feedstockDetails: 'Industrial fermentation broth (Novozymes/Novo Nordisk), yeast slurry, agricultural residues',
    upgradingTechnology: 'Amine chemical wash',
    gridConnectionType: 'Distribution (DSO)',
    networkOperator: 'Evida',
    certificationAndRegistry: 'REDcert EU · Energinet Register',
    primaryOfftake: 'Kalundborg industrial symbiosis & gas grid injection',
    coordinates: [11.088, 55.679],
  },
  {
    id: 'dk-vinkel',
    name: 'BioCirc Vinkel Bioenergi',
    country: 'Denmark',
    countryCode: 'DK',
    countryFlag: '🇩🇰',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Central Denmark (Skive)',
    operator: 'BioCirc Group',
    commissioningYear: 2021,
    capacityNm3h: 4500,
    annualEnergyGWh: 300.0,
    primaryFeedstockCategory: 'Manure & Agricultural residues',
    feedstockDetails: 'Livestock manure (400k t/y), straw, maize silage',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Energinet',
    certificationAndRegistry: 'ISCC EU · Energinet Register',
    primaryOfftake: 'European compliance export & biogenic CO2 capture',
    coordinates: [9.120, 56.520],
  },

  // Germany (DE)
  {
    id: 'de-gustrow',
    name: 'EnviTec Güstrow Bio-LNG Plant',
    country: 'Germany',
    countryCode: 'DE',
    countryFlag: '🇩🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Mecklenburg-Vorpommern (Güstrow)',
    operator: 'EnviTec Biogas AG',
    commissioningYear: 2009,
    capacityNm3h: 5000,
    annualEnergyGWh: 360.0,
    primaryFeedstockCategory: 'Agricultural residues & Manure',
    feedstockDetails: 'Solid cattle manure, chicken litter, agricultural catch crops',
    upgradingTechnology: 'EnviThan® Membrane + Cryogenic Liquefaction (Bio-LNG)',
    gridConnectionType: 'Direct Bio-LNG / Off-grid + THE grid injection',
    networkOperator: 'ONTRAS Gastransport GmbH',
    certificationAndRegistry: 'REDcert EU / dena Biogasregister (§37a BImSchG)',
    primaryOfftake: 'Heavy-duty transport Bio-LNG bunkering & THG quota compliance',
    coordinates: [12.176, 53.794],
  },
  {
    id: 'de-schwedt',
    name: 'VERBIO Schwedt Biomethane',
    country: 'Germany',
    countryCode: 'DE',
    countryFlag: '🇩🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Brandenburg (Uckermark)',
    operator: 'VERBIO Vereinigte BioEnergie AG',
    commissioningYear: 2014,
    capacityNm3h: 4200,
    annualEnergyGWh: 280.0,
    primaryFeedstockCategory: '100% Agricultural Straw',
    feedstockDetails: 'Cereal straw bales & whole distillery stillage (Annex IX-A)',
    upgradingTechnology: 'Amine chemical wash (Schmack Carbotech)',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'ONTRAS Gastransport GmbH',
    certificationAndRegistry: 'ISCC EU / dena Biogasregister (Annex IX-A Double Counting)',
    primaryOfftake: 'Bio-CNG transport fuel & German THG quota surrender',
    coordinates: [14.285, 53.064],
  },
  {
    id: 'de-zorbig',
    name: 'VERBIO Zörbig Biomethane',
    country: 'Germany',
    countryCode: 'DE',
    countryFlag: '🇩🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Saxony-Anhalt (Anhalt-Bitterfeld)',
    operator: 'VERBIO Vereinigte BioEnergie AG',
    commissioningYear: 2010,
    capacityNm3h: 3600,
    annualEnergyGWh: 240.0,
    primaryFeedstockCategory: '100% Agricultural Straw & Stillage',
    feedstockDetails: 'Distillery stillage byproduct from bioethanol unit & pressed straw',
    upgradingTechnology: 'Amine chemical wash',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'MITNETZ GAS / ONTRAS',
    certificationAndRegistry: 'ISCC EU / dena Biogasregister',
    primaryOfftake: 'German transport quota (§37a BImSchG)',
    coordinates: [12.118, 51.628],
  },
  {
    id: 'de-sudergellersen',
    name: 'Weltec Südergellersen',
    country: 'Germany',
    countryCode: 'DE',
    countryFlag: '🇩🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Lower Saxony (Lüneburg)',
    operator: 'WELTEC BIOPOWER GmbH',
    commissioningYear: 2015,
    capacityNm3h: 1800,
    annualEnergyGWh: 115.0,
    primaryFeedstockCategory: 'Manure & Energy Crops',
    feedstockDetails: 'Slurry, corn silage, whole plant silage',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Distribution (DSO)',
    networkOperator: 'Avacon Netz GmbH',
    certificationAndRegistry: 'REDcert EU / dena Biogasregister',
    primaryOfftake: 'Regional utility decarbonization & municipal heating',
    coordinates: [10.298, 53.227],
  },

  // France (FR)
  {
    id: 'fr-biobearn',
    name: 'TotalEnergies BioBéarn',
    country: 'France',
    countryCode: 'FR',
    countryFlag: '🇫🇷',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Nouvelle-Aquitaine (Mourenx)',
    operator: 'TotalEnergies Biogaz France',
    commissioningYear: 2023,
    capacityNm3h: 2200,
    annualEnergyGWh: 160.0,
    primaryFeedstockCategory: 'Agro-industrial & Farming waste',
    feedstockDetails: 'Corn processing residues, livestock manure, agrifood effluents (220k t/y)',
    upgradingTechnology: 'Membrane separation (Air Liquide)',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Teréga',
    certificationAndRegistry: 'ISCC EU · Registre National des Garanties d\'Origine (EEX)',
    primaryOfftake: 'French CPB compliance & industrial gas network injection',
    coordinates: [-0.612, 43.372],
  },
  {
    id: 'fr-claye-souilly',
    name: 'Waga Energy Claye-Souilly',
    country: 'France',
    countryCode: 'FR',
    countryFlag: '🇫🇷',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Île-de-France (Seine-et-Marne)',
    operator: 'Waga Energy / Veolia',
    commissioningYear: 2022,
    capacityNm3h: 3000,
    annualEnergyGWh: 120.0,
    primaryFeedstockCategory: 'Landfill Gas (LFG)',
    feedstockDetails: 'Captured raw biogas from Veolia non-hazardous waste storage facility',
    upgradingTechnology: 'Cryogenic Distillation (WAGABOX® technology)',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'GRTgaz',
    certificationAndRegistry: 'ISCC EU · EEX French GO Register',
    primaryOfftake: 'Paris regional grid supply & corporate PPA',
    coordinates: [2.684, 48.948],
  },
  {
    id: 'fr-beauce',
    name: 'ENGIE Beauce Gâtinais Biogaz',
    country: 'France',
    countryCode: 'FR',
    countryFlag: '🇫🇷',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Centre-Val de Loire (Pithiviers)',
    operator: 'ENGIE BioZ / Storengy',
    commissioningYear: 2021,
    capacityNm3h: 1600,
    annualEnergyGWh: 95.0,
    primaryFeedstockCategory: 'Agricultural byproducts',
    feedstockDetails: 'Sugar beet pulp, cereal wastes, intermediate crops (CIVE)',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Distribution (DSO)',
    networkOperator: 'GRDF',
    certificationAndRegistry: 'REDcert EU · EEX GO Register',
    primaryOfftake: 'French feed-in tariff (CPB tariff contract)',
    coordinates: [2.250, 48.170],
  },

  // Netherlands (NL)
  {
    id: 'nl-wijster',
    name: 'Attero Wijster Organic Waste Digester',
    country: 'Netherlands',
    countryCode: 'NL',
    countryFlag: '🇳🇱',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Drenthe (Midden-Drenthe)',
    operator: 'Attero B.V.',
    commissioningYear: 2017,
    capacityNm3h: 3500,
    annualEnergyGWh: 210.0,
    primaryFeedstockCategory: 'Municipal Organic Waste (VGF)',
    feedstockDetails: 'Source-separated household organic biowaste & commercial food leftovers',
    upgradingTechnology: 'Water wash scrubbing (DMT Clear Gas)',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Gasunie Transport Services (GTS)',
    certificationAndRegistry: 'ISCC EU · VertiCer Register (HBE/ERE eligible)',
    primaryOfftake: 'Dutch transport renewable energy unit (ERE/HBE) market',
    coordinates: [6.516, 52.793],
  },
  {
    id: 'nl-coevorden',
    name: 'Nature Energy Coevorden',
    country: 'Netherlands',
    countryCode: 'NL',
    countryFlag: '🇳🇱',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Drenthe (Coevorden)',
    operator: 'Nature Energy Netherlands B.V.',
    commissioningYear: 2023,
    capacityNm3h: 3200,
    annualEnergyGWh: 190.0,
    primaryFeedstockCategory: 'Manure & Agro-industrial residues',
    feedstockDetails: 'Cattle slurry, poultry manure, food processing waste',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Gasunie Transport Services (GTS)',
    certificationAndRegistry: 'ISCC EU · VertiCer Register',
    primaryOfftake: 'Dutch ERE quota compliance & industrial TTF injection',
    coordinates: [6.741, 52.661],
  },

  // Sweden (SE)
  {
    id: 'se-goteborg',
    name: 'Gasum Göteborg Biogas & Bio-LNG',
    country: 'Sweden',
    countryCode: 'SE',
    countryFlag: '🇸🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Västra Götaland (Göteborg)',
    operator: 'Gasum AB',
    commissioningYear: 2016,
    capacityNm3h: 2500,
    annualEnergyGWh: 145.0,
    primaryFeedstockCategory: 'Industrial food waste & Sludge',
    feedstockDetails: 'Food industry waste, municipal sewage sludge, grease trap waste',
    upgradingTechnology: 'Water wash scrubbing + Cryogenic liquefaction',
    gridConnectionType: 'Distribution & Direct Bio-LNG',
    networkOperator: 'Göteborg Energi / Swedegas',
    certificationAndRegistry: 'ISCC EU · Energigas Sverige Register',
    primaryOfftake: 'Nordic maritime bunkering & road transport Bio-LNG',
    coordinates: [11.974, 57.708],
  },
  {
    id: 'se-skogn',
    name: 'Biokraft Skogn Bio-LNG Facility',
    country: 'Sweden',
    countryCode: 'SE',
    countryFlag: '🇸🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Trøndelag / Nordic Corridor',
    operator: 'St1 Biokraft International',
    commissioningYear: 2018,
    capacityNm3h: 3400,
    annualEnergyGWh: 210.0,
    primaryFeedstockCategory: 'Aquaculture sludge & Paper mill waste',
    feedstockDetails: 'Salmon farming organic sludge & Norske Skog paper mill byproducts',
    upgradingTechnology: 'Water wash + Wärtsilä Bio-LNG liquefier',
    gridConnectionType: 'Direct Bio-LNG / Off-grid maritime rail',
    networkOperator: 'Nordic Clean Gas Grid',
    certificationAndRegistry: 'ISCC EU · Nordic Biogas Register',
    primaryOfftake: 'Heavy transport logistics & Baltic maritime fuel',
    coordinates: [11.180, 63.620],
  },

  // Spain (ES)
  {
    id: 'es-unue',
    name: 'Biovic / Suma UNUE Burgos',
    country: 'Spain',
    countryCode: 'ES',
    countryFlag: '🇪🇸',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Castile and León (Burgos)',
    operator: 'Biovic / Suma Capital (Aenergy)',
    commissioningYear: 2021,
    capacityNm3h: 1200,
    annualEnergyGWh: 70.0,
    primaryFeedstockCategory: 'Organic industrial biowaste & Slurry',
    feedstockDetails: 'Agrifood waste, pig slurry, slaughterhouse waste',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Enagás',
    certificationAndRegistry: 'ISCC EU · Enagás GTS Spanish Guarantee of Origin System',
    primaryOfftake: 'Spanish industrial decarbonization & GTS injection',
    coordinates: [-3.703, 42.343],
  },
  {
    id: 'es-can-mata',
    name: 'Waga Energy Can Mata (Els Hostalets de Pierola)',
    country: 'Spain',
    countryCode: 'ES',
    countryFlag: '🇪🇸',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Catalonia (Barcelona)',
    operator: 'Waga Energy / PreZero España',
    commissioningYear: 2023,
    capacityNm3h: 2200,
    annualEnergyGWh: 85.0,
    primaryFeedstockCategory: 'Landfill Gas (LFG)',
    feedstockDetails: 'Degasification of the Can Mata landfill (20M tons stored waste)',
    upgradingTechnology: 'WAGABOX® Cryogenic Distillation',
    gridConnectionType: 'Distribution (DSO)',
    networkOperator: 'Nedgia (Naturgy Group)',
    certificationAndRegistry: 'ISCC EU · Enagás GTS Register',
    primaryOfftake: 'Long-term corporate PPA & Spanish grid injection',
    coordinates: [1.810, 41.530],
  },

  // Italy (IT)
  {
    id: 'it-sant-agata',
    name: 'HERA Sant’Agata Bolognese Biomethane',
    country: 'Italy',
    countryCode: 'IT',
    countryFlag: '🇮🇹',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Emilia-Romagna (Bologna)',
    operator: 'Gruppo HERA S.p.A.',
    commissioningYear: 2018,
    capacityNm3h: 2100,
    annualEnergyGWh: 90.0,
    primaryFeedstockCategory: 'Municipal Organic Waste (FORSU)',
    feedstockDetails: 'Source-separated food waste (100k t/y) + green pruning waste (35k t/y)',
    upgradingTechnology: 'Water wash scrubbing (DMT)',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'SNAM Rete Gas',
    certificationAndRegistry: 'ISCC EU · GSE CIC Register (D.M. 2 Marzo 2018 / PNRR)',
    primaryOfftake: 'Italian CIC certificate issuance & vehicle fuel injection',
    coordinates: [11.132, 44.664],
  },

  // Belgium (BE)
  {
    id: 'be-quevy',
    name: 'ENGIE BioZ Quévy Biomethane',
    country: 'Belgium',
    countryCode: 'BE',
    countryFlag: '🇧🇪',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Wallonia (Hainaut)',
    operator: 'ENGIE BioZ / Fluxys',
    commissioningYear: 2021,
    capacityNm3h: 1500,
    annualEnergyGWh: 80.0,
    primaryFeedstockCategory: 'Agricultural & Food processing residues',
    feedstockDetails: 'Cattle manure, cover crops, vegetable sorting residues',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Transmission (TSO)',
    networkOperator: 'Fluxys Belgium',
    certificationAndRegistry: 'ISCC EU · CWaPE Guarantees of Origin',
    primaryOfftake: 'Fluxys natural gas transmission grid injection',
    coordinates: [3.935, 50.360],
  },

  // Poland (PL)
  {
    id: 'pl-pgb-brodzyce',
    name: 'Polska Grupa Biogazowa Brodzyce',
    country: 'Poland',
    countryCode: 'PL',
    countryFlag: '🇵🇱',
    status: 'Active',
    provenance: 'GIE/EBA European Biomethane Map 2026 (Verified Commercial Registry)',
    region: 'Lower Silesia (Dolnośląskie)',
    operator: 'TotalEnergies / Polska Grupa Biogazowa (PGB)',
    commissioningYear: 2022,
    capacityNm3h: 1400,
    annualEnergyGWh: 65.0,
    primaryFeedstockCategory: 'Agricultural byproducts & Distillery waste',
    feedstockDetails: 'Distillery stillage, pomace, manure, corn residues',
    upgradingTechnology: 'Membrane separation',
    gridConnectionType: 'Distribution (DSO)',
    networkOperator: 'Polska Spółka Gazownictwa (PSG)',
    certificationAndRegistry: 'KZR INiG / ISCC EU',
    primaryOfftake: 'Polish grid injection & industrial decarbonization',
    coordinates: [17.020, 50.850],
  },
];
