/**
 * Generated by scripts/build_fueleu_shipping_targets.ts. DO NOT hand-edit.
 * EU MRV (THETIS-MRV) publication the FuelEU / ETS-maritime shipping data was built from.
 */
export const MRV_REPORTING_YEAR = 2025;
export const MRV_PUBLICATION_VERSION = 58;
