import { Consignment } from './types';
import { FeedstockInfo, FEEDSTOCK_REGISTRY } from './feedstockData';
import { feedstockDefaultCi, getAssumption } from '../assumptions/registry';

export type { FeedstockInfo };
export { FEEDSTOCK_REGISTRY };

/**
 * Standard Named Reference Consignments
 * Shared across Domain, UI and Automated Test Suites to avoid hardcoded duplication.
 */
export const REFERENCE_CONSIGNMENTS: Record<string, Consignment> = {
  DANISH_MANURE: {
    id: 'ref_dk_manure',
    name: 'Danish Manure Benchmark',
    originCountry: 'DK',
    originCountryName: 'Denmark',
    feedstock: 'manure',
    feedstockName: 'Animal manure and slurry',
    annexClassification: 'IX_A',
    carbonIntensity: -100,
    commissioningDateRange: 'POST_2021_TO_2025',
    certificationScheme: 'ISCC_EU',
    chainOfCustody: 'MASS_BALANCE',
    injectionCountry: 'DK',
    injectionIsEU: true,
    udbStatus: 'RECORDED',
    posStatus: 'ISSUED',
    volumeMWh: 10000,
    deliveryPeriod: null,
    counterparty: null,
  },
  /** Spanish manure into the NL green-gas obligation (delivery 2027), so the Morning brief ladder shows NL GGE. */
  SPANISH_MANURE: {
    id: 'ref_es_manure',
    name: 'Spanish Manure Benchmark',
    originCountry: 'ES',
    originCountryName: 'Spain',
    feedstock: 'manure',
    feedstockName: FEEDSTOCK_REGISTRY.manure.name,
    annexClassification: FEEDSTOCK_REGISTRY.manure.annexClassification,
    carbonIntensity: feedstockDefaultCi('manure') ?? FEEDSTOCK_REGISTRY.manure.defaultCI,
    commissioningDateRange: 'POST_2021_TO_2025',
    certificationScheme: 'ISCC_EU',
    chainOfCustody: 'MASS_BALANCE',
    injectionCountry: 'ES',
    injectionIsEU: true,
    udbStatus: 'RECORDED',
    posStatus: 'ISSUED',
    volumeMWh: getAssumption('deal.defaultVolumeMwh'),
    deliveryPeriod: { type: 'CALENDAR', startDate: '2027-01-01', endDate: '2027-12-31', complianceYear: 2027 },
    counterparty: null,
  },
  UK_FOOD_WASTE: {
    id: 'ref_uk_food_waste',
    name: 'UK Food Waste (Non-EU Grid Injected)',
    originCountry: 'GB',
    originCountryName: 'United Kingdom',
    feedstock: 'food_waste',
    feedstockName: 'Bio-waste (food waste)',
    annexClassification: 'IX_A',
    carbonIntensity: 20,
    commissioningDateRange: 'POST_2021_TO_2025',
    certificationScheme: 'ISCC_EU',
    chainOfCustody: 'MASS_BALANCE',
    injectionCountry: 'GB',
    injectionIsEU: false,
    udbStatus: 'NOT_RECORDED',
    posStatus: 'ISSUED',
    volumeMWh: 8000,
    deliveryPeriod: null,
    counterparty: null,
  },
  ISCC_PLUS_VOLUNTARY: {
    id: 'ref_iscc_plus',
    name: 'French Residues (ISCC PLUS Voluntary)',
    originCountry: 'FR',
    originCountryName: 'France',
    feedstock: 'agricultural_residues',
    feedstockName: 'Straw and agricultural residues',
    annexClassification: 'IX_A',
    carbonIntensity: 18,
    commissioningDateRange: 'POST_2021_TO_2025',
    certificationScheme: 'ISCC_PLUS',
    chainOfCustody: 'MASS_BALANCE',
    injectionCountry: 'FR',
    injectionIsEU: true,
    udbStatus: 'RECORDED',
    posStatus: 'ISSUED',
    volumeMWh: 5000,
    deliveryPeriod: null,
    counterparty: null,
  },
  FUELEU_MARITIME_LNG: {
    id: 'ref_fueleu_lng',
    name: 'Dutch Manure Bio-LNG (FuelEU Maritime Deficit Neutraliser)',
    originCountry: 'NL',
    originCountryName: 'Netherlands',
    feedstock: 'manure',
    feedstockName: 'Animal manure and slurry',
    annexClassification: 'IX_A',
    carbonIntensity: -120,
    commissioningDateRange: 'POST_2021_TO_2025',
    certificationScheme: 'ISCC_EU',
    chainOfCustody: 'MASS_BALANCE',
    injectionCountry: 'NL',
    injectionIsEU: true,
    udbStatus: 'RECORDED',
    posStatus: 'ISSUED',
    volumeMWh: 15000,
    deliveryPeriod: null,
    counterparty: null,
  },
};
