import { LegalCitation } from './types';

export const CITATIONS: Record<string, LegalCitation> = {
  RED_III_VOLUNTARY_SCHEMES: {
    shortName: 'RED III Art. 30(4)',
    fullReference: 'Directive (EU) 2023/2413 Article 30(4)',
    establishes: 'Recognition of voluntary schemes',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_UDB: {
    shortName: 'RED III Art. 28(2) & 31a',
    fullReference: 'Directive (EU) 2023/2413 Article 28(2) and Article 31a',
    establishes: 'Union Database requirement',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  UDB_IMPLEMENTING_REG: {
    shortName: 'Regulation (EU) 2024/2792',
    fullReference: 'Commission Implementing Regulation (EU) 2024/2792',
    establishes: 'Implementation rules for the Union Database',
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg_impl/2024/2792/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_CHAIN_OF_CUSTODY: {
    shortName: 'RED III Art. 30(1)-(2)',
    fullReference: 'Directive (EU) 2023/2413 Article 30(1)-(2)',
    establishes: 'Mass balance requirement',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_ANNEX_IX_A: {
    shortName: 'RED III Annex IX Part A',
    fullReference: 'Directive (EU) 2023/2413 Annex IX Part A',
    establishes: 'Advanced biofuel feedstocks',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_ANNEX_IX_B: {
    shortName: 'RED III Annex IX Part B',
    fullReference: 'Directive (EU) 2023/2413 Annex IX Part B',
    establishes: 'Capped feedstocks',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_ART_26: {
    shortName: 'RED III Art. 26',
    fullReference: 'Directive (EU) 2023/2413 Article 26',
    establishes: 'Crop cap',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_GHG_TRANSPORT: {
    shortName: 'RED III Art. 29(10)',
    fullReference: 'Directive (EU) 2023/2413 Article 29(10)',
    establishes: 'GHG saving thresholds for transport',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_GHG_HEAT: {
    shortName: 'RED III Art. 29(10)',
    fullReference: 'Directive (EU) 2023/2413 Article 29(10)',
    establishes: 'GHG saving thresholds for heat/power',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_COMPARATOR: {
    shortName: 'RED III Annex V Part C(19)',
    fullReference: 'Directive (EU) 2023/2413 Annex V Part C point 19',
    establishes: 'Fossil fuel comparator',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  DE_BIMSCHG: {
    shortName: '§37a BImSchG',
    fullReference: 'Bundes-Immissionsschutzgesetz (BImSchG) § 37a',
    establishes: 'German THG quota',
    sourceUrl: 'https://www.gesetze-im-internet.de/bimschg/',
    verifiedDate: '2026-08-16',
  },
  DE_38_BIMSCHV: {
    shortName: '38. BImSchV',
    fullReference: '38. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes',
    establishes: 'Implementing regulation for THG quota',
    sourceUrl: 'https://www.gesetze-im-internet.de/bimschv_38/',
    verifiedDate: '2026-08-16',
  },
  NL_ERE: {
    shortName: 'NL Regeling energie vervoer',
    fullReference: 'Wet milieubeheer, Regeling energie vervoer',
    establishes: 'Netherlands ERE requirements',
    sourceUrl: 'https://wetten.overheid.nl/',
    verifiedDate: '2026-08-16',
  },
  FR_CPB: {
    shortName: 'FR Code de l\'énergie',
    fullReference: 'Code de l\'énergie, Art. L.446-24 et seq.',
    establishes: 'France CPB requirements',
    sourceUrl: 'https://www.legifrance.gouv.fr/',
    verifiedDate: '2026-08-16',
  },
  IT_CIC: {
    shortName: 'IT DM 2 March 2018',
    fullReference: 'Decreto Ministeriale 2 marzo 2018',
    establishes: 'Italy CIC GSE regulatory framework',
    sourceUrl: 'https://www.gazzettaufficiale.it/',
    verifiedDate: '2026-08-16',
  },
  AT_EGG: {
    shortName: 'AT Erneuerbaren-Gase-Gesetz',
    fullReference: 'Erneuerbaren-Gase-Gesetz (EGG)',
    establishes: 'Austria Green gas supplier quota',
    sourceUrl: 'https://www.ris.bka.gv.at/',
    verifiedDate: '2026-08-16',
  },
  FUELEU_MARITIME: {
    shortName: 'Regulation (EU) 2023/1805',
    fullReference: 'Regulation (EU) 2023/1805 of the European Parliament and of the Council',
    establishes: 'FuelEU Maritime requirements',
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2023/1805/oj',
    verifiedDate: '2026-08-16',
  },
  EU_ETS_DIRECTIVE: {
    shortName: 'Directive 2003/87/EC',
    fullReference: 'Directive 2003/87/EC, as amended by Directive (EU) 2023/959',
    establishes: 'EU ETS requirements',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2003/87/oj',
    verifiedDate: '2026-08-16',
  },
  UK_RTFO: {
    shortName: 'UK RTFO Order 2007',
    fullReference: 'Renewable Transport Fuel Obligations Order 2007',
    establishes: 'UK RTFO requirements',
    sourceUrl: 'https://www.legislation.gov.uk/uksi/2007/3072/contents',
    verifiedDate: '2026-08-16',
  },
  ISCC_EU_RECOGNITION: {
    shortName: 'ISCC EU Recognition',
    fullReference: 'Commission Implementing Decision on the recognition of the ISCC EU voluntary scheme',
    establishes: 'EC recognition of ISCC EU',
    sourceUrl: 'https://energy.ec.europa.eu/',
    verifiedDate: '2026-08-16',
  },
  ISCC_PLUS_SCOPE: {
    shortName: 'ISCC PLUS Scope',
    fullReference: 'ISCC PLUS system document v3.4',
    establishes: 'Voluntary market scope rules',
    sourceUrl: 'https://www.iscc-system.org/',
    verifiedDate: '2026-08-16',
  }
};
