import { LegalCitation } from './types';

export const CITATIONS: Record<string, LegalCitation> = {
  RED_III_VOLUNTARY_SCHEMES: {
    shortName: 'RED III Art. 30(4)',
    fullReference: 'Directive (EU) 2023/2413 Article 30(4)',
    establishes: 'Recognition of voluntary schemes by European Commission',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_UDB: {
    shortName: 'RED III Art. 28(2) & 31a',
    fullReference: 'Directive (EU) 2023/2413 Article 28(2) and Article 31a',
    establishes: 'Union Database (UDB) mass balance tracing requirement within EU perimeter',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  UDB_IMPLEMENTING_REG: {
    shortName: 'Regulation (EU) 2024/2792',
    fullReference: 'Commission Implementing Regulation (EU) 2024/2792 on UDB operation',
    establishes: 'Implementation rules for the Union Database and gas grid mass balance',
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg_impl/2024/2792/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_CHAIN_OF_CUSTODY: {
    shortName: 'RED III Art. 30(1)-(2)',
    fullReference: 'Directive (EU) 2023/2413 Article 30(1)-(2)',
    establishes: 'Mass balance system requirements for physical gas grid deliveries',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_ANNEX_IX_A: {
    shortName: 'RED III Annex IX Part A',
    fullReference: 'Directive (EU) 2023/2413 Annex IX Part A',
    establishes: 'Advanced biofuel feedstock list (manure, bio-waste, straw, sludges)',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_ANNEX_IX_B: {
    shortName: 'RED III Annex IX Part B',
    fullReference: 'Directive (EU) 2023/2413 Annex IX Part B',
    establishes: 'Capped feedstocks (used cooking oil, animal fats Cat 1 & 2)',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_ART_26: {
    shortName: 'RED III Art. 26',
    fullReference: 'Directive (EU) 2023/2413 Article 26',
    establishes: 'Food and feed crop caps and phase-out of high ILUC-risk biofuels',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_GHG_TRANSPORT: {
    shortName: 'RED III Art. 29(10)',
    fullReference: 'Directive (EU) 2023/2413 Article 29(10)',
    establishes: 'Mandatory GHG saving thresholds (50% / 60% / 65%) for transport fuels',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  RED_III_COMPARATOR: {
    shortName: 'RED III Annex V Part C(19)',
    fullReference: 'Directive (EU) 2023/2413 Annex V Part C point 19',
    establishes: 'Fossil fuel baseline comparator (94.0 gCO₂e/MJ for transport fuels)',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2023/2413/oj',
    verifiedDate: '2026-08-16',
  },
  DE_BIMSCHG: {
    shortName: '§37a BImSchG',
    fullReference: 'Bundes-Immissionsschutzgesetz (BImSchG) § 37a',
    establishes: 'German Greenhouse Gas (THG) reduction quota obligation',
    sourceUrl: 'https://www.gesetze-im-internet.de/bimschg/',
    verifiedDate: '2026-08-16',
  },
  DE_38_BIMSCHV: {
    shortName: '38. BImSchV',
    fullReference: '38. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes',
    establishes: 'Implementing regulation for upstream emission reduction and biomethane crediting',
    sourceUrl: 'https://www.gesetze-im-internet.de/bimschv_38/',
    verifiedDate: '2026-08-16',
  },
  NL_ERE: {
    shortName: 'NL Regeling energie vervoer',
    fullReference: 'Wet milieubeheer, Regeling energie vervoer (Staatscourant 2025/2026)',
    establishes: 'Netherlands ERE Emissions Reduction Obligation replacing HBE system from 2026',
    sourceUrl: 'https://wetten.overheid.nl/',
    verifiedDate: '2026-08-16',
  },
  FR_CPB: {
    shortName: 'FR Code de l\'énergie Art. L.446-24',
    fullReference: 'Code de l\'énergie, Articles L.446-24 à L.446-32 (Loi Climat et Résilience)',
    establishes: 'French Certificats de Production de Biogaz (CPB) supplier obligation from 1 Jan 2026',
    sourceUrl: 'https://www.legifrance.gouv.fr/',
    verifiedDate: '2026-08-16',
  },
  IT_CIC: {
    shortName: 'IT DM 2 March 2018',
    fullReference: 'Decreto Ministeriale 2 marzo 2018 e DM 15 settembre 2022 (PNRR Biometano)',
    establishes: 'Italy CIC regulatory framework (1 CIC = 10 Gcal conventional / 5 Gcal advanced)',
    sourceUrl: 'https://www.gazzettaufficiale.it/',
    verifiedDate: '2026-08-16',
  },
  DK_ENERGY_ACT: {
    shortName: 'DK Lov om fremme af VE',
    fullReference: 'Bekendtgørelse af lov om fremme af vedvarende energi (VE-loven)',
    establishes: 'Danish green gas production feed-in and Energinet GO register framework',
    sourceUrl: 'https://www.retsinformation.dk/',
    verifiedDate: '2026-08-16',
  },
  AT_EGG: {
    shortName: 'AT Erneuerbaren-Gase-Gesetz',
    fullReference: 'Bundesgesetz über die Verpflichtung zum Einsatz erneuerbarer Gase (EGG)',
    establishes: 'Austrian green gas supplier quota rising to 7.7% by 2030',
    sourceUrl: 'https://www.ris.bka.gv.at/',
    verifiedDate: '2026-08-16',
  },
  ES_RD_376: {
    shortName: 'ES Real Decreto 376/2022',
    fullReference: 'Real Decreto 376/2022 por el que se regulan los criterios de sostenibilidad y GdO',
    establishes: 'Spanish Guarantees of Origin (GdO) system and Enagás GTS registry',
    sourceUrl: 'https://www.boe.es/eli/es/rd/2022/05/17/376',
    verifiedDate: '2026-08-16',
  },
  PL_OZE_ACT: {
    shortName: 'PL Ustawa o OZE',
    fullReference: 'Ustawa o odnawialnych źródłach energii z późn. zm. (Nowelizacja OZE 2023/2024)',
    establishes: 'Polish biomethane operational support, direct pipeline injection, and KZR INiG',
    sourceUrl: 'https://isap.sejm.gov.pl/',
    verifiedDate: '2026-08-16',
  },
  SE_TAX_ACT: {
    shortName: 'SE Lag om skatt på energi',
    fullReference: 'Lag (1994:1776) om skatt på energi (re-approved EU State Aid decision 2024)',
    establishes: 'Swedish energy and carbon tax exemption for biomethane motor fuels and heating',
    sourceUrl: 'https://www.riksdagen.se/',
    verifiedDate: '2026-08-16',
  },
  FI_DIST_ACT: {
    shortName: 'FI Jakeluvelvoitelaki',
    fullReference: 'Laki uusiutuvien polttoaineiden käytön edistämisestä liikenteessä (446/2007)',
    establishes: 'Finnish transport fuel distribution obligation and Gasgrid Ex-Domain transfers',
    sourceUrl: 'https://www.finlex.fi/',
    verifiedDate: '2026-08-16',
  },
  BE_REGIONAL_DECREES: {
    shortName: 'BE Regional Decrees (VREG/SPW)',
    fullReference: 'Flamisch Energiedecreet 2009 & Décret wallon relatif à l\'organisation du marché du gaz',
    establishes: 'Belgian regional green gas certificate systems and transport blending mandates',
    sourceUrl: 'https://www.vreg.be/',
    verifiedDate: '2026-08-16',
  },
  CZ_POZE_ACT: {
    shortName: 'CZ Zákon č. 165/2012 Sb. (POZE)',
    fullReference: 'Zákon o podporovaných zdrojích energie (POZE) a OTE systém záruk původu',
    establishes: 'Czech Republic biomethane feed-in support and OTE Guarantee of Origin registry',
    sourceUrl: 'https://www.zakonyprolidi.cz/',
    verifiedDate: '2026-08-16',
  },
  IE_RHO_FRAMEWORK: {
    shortName: 'IE Renewable Heat Obligation',
    fullReference: 'Renewable Heat Obligation Scheme (Department of the Environment, Climate and Comms)',
    establishes: 'Irish supplier obligation for renewable heat blending and GNI green gas registry',
    sourceUrl: 'https://www.gov.ie/decc/',
    verifiedDate: '2026-08-16',
  },
  PT_DECREE_84: {
    shortName: 'PT Decreto-Lei n.º 84/2022',
    fullReference: 'Decreto-Lei n.º 84/2022 que estabelece o regime jurídico aplicável aos gases de origem renovável',
    establishes: 'Portuguese renewable gas guarantees of origin and EEGO / REN registry system',
    sourceUrl: 'https://diariodarepublica.pt/',
    verifiedDate: '2026-08-16',
  },
  HU_GAS_ACT: {
    shortName: 'HU 2008. évi XL. törvény',
    fullReference: '2008. évi XL. törvény a földgázellátásról (Földgáztörvény) és MEKH rendeletek',
    establishes: 'Hungarian biomethane grid injection standards and MEKH regulatory supervision',
    sourceUrl: 'https://njt.hu/',
    verifiedDate: '2026-08-16',
  },
  SK_RES_ACT: {
    shortName: 'SK Zákon č. 309/2009 Z. z.',
    fullReference: 'Zákon o podpore obnoviteľných zdrojov energie a OKTE systém záruk pôvodu plynu',
    establishes: 'Slovak biomethane production support and SPP-distribúcia injection protocol',
    sourceUrl: 'https://www.slov-lex.sk/',
    verifiedDate: '2026-08-16',
  },
  EE_ENERGY_ACT: {
    shortName: 'EE Vedelkütuse seadus',
    fullReference: 'Vedelkütuse seadus ja Välisõhu kaitse seadus (Elering biomethane registry)',
    establishes: 'Estonian transport renewable obligation (100% urban bus biomethane mandate)',
    sourceUrl: 'https://www.riigiteataja.ee/',
    verifiedDate: '2026-08-16',
  },
  LT_ALT_FUELS: {
    shortName: 'LT Alternatyviųjų degalų įstatymas',
    fullReference: 'Lietuvos Respublikos alternatyviųjų degalų įstatymas (Amber Grid registry)',
    establishes: 'Lithuanian transport alternative fuels mandate and Amber Grid GO registry',
    sourceUrl: 'https://e-tar.lt/',
    verifiedDate: '2026-08-16',
  },
  LV_ENERGY_LAW: {
    shortName: 'LV Enerģētikas likums',
    fullReference: 'Enerģētikas likums un Transporta enerģijas likuma projekts (Conexus Baltic Grid)',
    establishes: 'Latvian renewable gas injection rules and Conexus GO certification',
    sourceUrl: 'https://likumi.lv/',
    verifiedDate: '2026-08-16',
  },
  CH_CO2_ACT: {
    shortName: 'CH CO2-Gesetz (SR 641.71)',
    fullReference: 'Bundesgesetz über die Reduktion der CO2-Emissionen (CO2-Gesetz) & Mineralölsteuergesetz',
    establishes: 'Swiss carbon tax compensation and fuel supplier blending. NOTE: Non-EU UDB boundary applies.',
    sourceUrl: 'https://www.fedlex.admin.ch/',
    verifiedDate: '2026-08-16',
  },
  NO_BIOFUEL_QUOTA: {
    shortName: 'NO Produktforskriften Kap 3',
    fullReference: 'Forskrift om begrensning i bruk av helse- og miljøfarlige kjemikalier (Drivstoffkrav)',
    establishes: 'Norwegian biofuel quota mandate for road and marine transport (Miljødirektoratet)',
    sourceUrl: 'https://lovdata.no/',
    verifiedDate: '2026-08-16',
  },
  FUELEU_MARITIME: {
    shortName: 'Regulation (EU) 2023/1805',
    fullReference: 'Regulation (EU) 2023/1805 on the use of renewable and low-carbon fuels in maritime transport',
    establishes: 'FuelEU Maritime GHG intensity targets, Article 21 pooling, and penalty deficit calculations',
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2023/1805/oj',
    verifiedDate: '2026-08-16',
  },
  EU_ETS_DIRECTIVE: {
    shortName: 'Directive 2003/87/EC',
    fullReference: 'Directive 2003/87/EC as amended by Directive (EU) 2023/959',
    establishes: 'EU ETS Phase 1 installation zero-rating and ETS2 fuel suppliers framework',
    sourceUrl: 'https://eur-lex.europa.eu/eli/dir/2003/87/oj',
    verifiedDate: '2026-08-16',
  },
  UK_RTFO: {
    shortName: 'UK RTFO Order 2007',
    fullReference: 'Renewable Transport Fuel Obligations Order 2007 (SI 2007/3072)',
    establishes: 'UK RTFO domestic fuel supplier mandate (~72 dRTFC/MWh standard, ~144 dRTFC/MWh waste derived from LHV 50 MJ/kg)',
    sourceUrl: 'https://www.legislation.gov.uk/uksi/2007/3072/contents',
    verifiedDate: null,
  },
  ISCC_PLUS_SCOPE: {
    shortName: 'ISCC PLUS System Document v3.4',
    fullReference: 'ISCC PLUS Standard for Circular Economy and Bioeconomy',
    establishes: 'Voluntary corporate Scope 1 & materials market scope (NOT recognised for RED III compliance)',
    sourceUrl: 'https://www.iscc-system.org/',
    verifiedDate: '2026-08-16',
  },
};
