/**
 * Master In-Memory Knowledge Vault for Closed-Domain Auditor
 * Distilled from the 11 statutory dossiers and enactments.
 */

export interface KnowledgeDocument {
  id: string;
  title: string;
  sourceFile: string;
  category: 'EU_DIRECTIVE' | 'NATIONAL_QUOTA' | 'UDB_REGISTRY' | 'CONTRACTS' | 'FUELEU';
  content: string;
}

export const KNOWLEDGE_VAULT_DOCS: KnowledgeDocument[] = [
  {
    id: 'red_iii_directive',
    title: 'RED III Directive (EU) 2023/2413 & Gating Architecture',
    sourceFile: '01_EU_Statutory_Directives_and_RED_III.md',
    category: 'EU_DIRECTIVE',
    content: `Article 25(1): Member States shall set an obligation on fuel suppliers to ensure that the share of renewable energy within the final consumption of energy in the transport sector is at least 29% by 2030 or leads to a greenhouse gas intensity reduction of at least 14.5% by 2030.
Article 29(10)(d): Greenhouse gas emissions savings from biofuels, bioliquids and biomass fuels shall be at least 70% for electricity, heating and cooling production from biomass fuels used in installations starting operation from 1 January 2021 to 31 December 2025, and at least 80% for installations starting operation from 1 January 2026.
Transport Fuel GHG Threshold: Biofuels and biomethane must achieve at least a 65% GHG emissions reduction against the fossil fuel comparator baseline of 94.0 gCO2eq/MJ (requiring Carbon Intensity CI <= 32.9 gCO2eq/MJ).
Article 31a(1): The Commission shall ensure that a Union database is established to enable the tracing of liquid and gaseous transport fuels that are eligible for being counted towards the numerator.
Annex IX Part A Feedstocks: Advanced feedstocks eligible for double-counting include algae, biomass fraction of mixed municipal waste, biowaste from private households, straw, animal manure and sewage sludge, palm oil mill effluent, crude glycerine, and tall oil pitch.
Annex IX Part B Feedstocks: Used cooking oil (UCO) and animal fats Category 1 and 2 under Regulation (EC) No 1069/2009.
Energy Crops / Silage Maize: Food and feed crop limits apply (typically capped at 1% above 2020 levels or max 7% in transport). Fully eligible for voluntary Scope 1 and UK RGGO, but strictly excluded or penalized in transport compliance quotas.`
  },
  {
    id: 'fueleu_maritime',
    title: 'FuelEU Maritime Regulation (EU) 2023/1805 & EU ETS Maritime',
    sourceFile: '11_FuelEU_Maritime_and_EU_ETS_Shipping_Desk.md',
    category: 'FUELEU',
    content: `Regulation (EU) 2023/1805 sets decreasing well-to-wake GHG intensity limits for ships above 5,000 gross tonnage calling at EU ports.
Baseline Fossil Carbon Intensity: 91.16 gCO2eq/MJ (VLSFO / MGO).
Target Trajectory: 2025 (-2% = 89.3368 gCO2eq/MJ); 2030 (-6% = 85.6904 gCO2eq/MJ); 2035 (-14.5% = 77.9418 gCO2eq/MJ); 2040 (-31% = 62.9004 gCO2eq/MJ); 2045 (-62% = 34.6408 gCO2eq/MJ); 2050 (-80% = 18.2320 gCO2eq/MJ).
Statutory Penalty Formula: Article 23(2) mandates a statutory non-compliance penalty of €2,400 per tonne VLSFO equivalent energy shortfall.
Energy density of VLSFO: 41,000 MJ/tonne (41.0 MJ/kg). LHV of Bio-LNG: 49,100 MJ/tonne (49.1 MJ/kg).
Compliance Pooling (Article 21): Two or more ships may establish a pool to collectively comply. Surplus generated by zero or deep negative CI Bio-LNG (e.g. Danish manure Bio-LNG at -80 to -100 gCO2eq/MJ) offsets deficits from conventional vessels, eliminating statutory penalties.
EU ETS Maritime (Directive 2023/959): RED III compliant Bio-LNG has an emission factor of 0.000 tCO2/tonne fuel (Zero-rated under EU ETS MRV). Phase-in: 70% in 2025, 100% in 2026.`
  },
  {
    id: 'germany_38_bimschv',
    title: 'German THG-Quote, 38. BImSchV & § 37a BImSchG',
    sourceFile: '02_National_Compliance_Quotas_and_Formulas.md',
    category: 'NATIONAL_QUOTA',
    content: `Under § 37a BImSchG and 38. BImSchV, fuel suppliers in Germany must meet an escalating greenhouse gas reduction quota (THG-Quote).
Manure Methane Avoidance Bonus (e_am): Liquid manure codigested in closed storage receives an avoided methane emissions credit of -45 gCO2eq/MJ, yielding deep negative CI values (-80 to -100 gCO2eq/MJ).
Legal Decoupling of e_am and 2x Multiplier: e_am is a physical lifecycle science credit under RED III Annex V/VI. The 2x double-counting multiplier is an administrative policy mechanism under § 37a BImSchG for Annex IX-A feedstocks. The 2x multiplier applies to the total resulting GHG avoidance (which includes e_am). If Germany repeals double-counting to 1x single counting, the physical e_am credit remains 100% intact.
BLE Nabisy Registration: To surrender biomethane certificates for THG compliance, the consignment Proof of Sustainability (PoS) must be registered with the BLE Nabisy system. Non-EU injected gas cannot clear into Nabisy without physical segregation.`
  },
  {
    id: 'france_cpb_tiruert',
    title: 'France CPB Obligation (Décret 2024-421) & TIRUERT Transport Quota',
    sourceFile: '02_National_Compliance_Quotas_and_Formulas.md',
    category: 'NATIONAL_QUOTA',
    content: `Décret n° 2024-421 establishes the Certificats de Production de Biogaz (CPB) purchasing obligation on French natural gas suppliers.
Statutory Price Ceiling: CPB certificates are subject to a statutory financial penalty ceiling of €100.00/MWh. Any calculated delivered stack above €100.00/MWh must be clamped at €100.00/MWh.
TIRUERT (Transport Tax): Advanced biomethane in transport qualifies for double-counting under the French customs TIRUERT regime.
Feedstock Reality: Over 85% of French biomethane fleet is based on agricultural residues, cover crops (CIVE), and farm slurry connected to GRDF and GRTgaz networks.`
  },
  {
    id: 'netherlands_ere_hbe',
    title: 'Netherlands Wet Milieubeheer & NEA HBE/ERE Regulatory Rules',
    sourceFile: '02_National_Compliance_Quotas_and_Formulas.md',
    category: 'NATIONAL_QUOTA',
    content: `The Nederlandse Emissieautoriteit (NEA) oversees the Dutch renewable transport fuel system based on Hernieuwbare Brandstofeenheden (HBE) and Energie voor Vervoer (ERE).
HBE-G (Gas) Certificates: Issued for biomethane delivered to transport filling stations or injected into the gas grid with corresponding VertiCer registry cancellation.
Advanced Annex IX-A feedstocks (e.g. manure, organic biowaste) generate HBE-G with double-counting multiplier.
VertiCer Cancellation: Green gas certificates must be cancelled in the VertiCer register in favor of the Dutch transport fuel register to generate valid compliance units.`
  },
  {
    id: 'italy_cic_pnrr',
    title: 'Italy DM 15/09/2022 PNRR Biometano & GSE CIC Quota',
    sourceFile: '02_National_Compliance_Quotas_and_Formulas.md',
    category: 'NATIONAL_QUOTA',
    content: `Decreto Ministeriale 15 Settembre 2022 governs Italian biomethane support and transport compliance through GSE (Gestore Servizi Energetici).
Certificati di Immissione in Consumo (CIC): 1 CIC is granted per 10 Gcal (approx 11.63 MWh) of biomethane injected into the SNAM grid for transport use.
Feedstock Eligibility: Advanced biomethane must be produced from organic fraction of municipal solid waste (FORSU) or agricultural slurry/residues.
Tenor: 15-year guaranteed incentive tariff structure.`
  },
  {
    id: 'uk_rtfo_rggo',
    title: 'UK RTFO Order (SI 2007/3072) & Green Gas Certification Scheme (RGGO)',
    sourceFile: '02_National_Compliance_Quotas_and_Formulas.md',
    category: 'NATIONAL_QUOTA',
    content: `The UK Renewable Transport Fuel Obligation (RTFO Order 2007, SI 2007/3072) governs renewable gaseous transport fuels in Great Britain.
Physical Grid Injection Invariant: UK RTFO and UK Green Gas Certification Scheme (RGGO) strictly require injection into the Great Britain (GB) gas grid.
Non-EU Grid Boundary: Non-EU injected gas cannot clear EU Union Database (UDB) mass balance into EU compliance destinations (DE, NL, FR, IT) without physical pipeline segregation.
Yield Factors: 72.0 kg biomethane per MWh. 1 dRTFC per kg standard, 2 dRTFC per kg waste/slurry (144.0 dRTFC per MWh). Buyout penalty: £0.50 per certificate.`
  },
  {
    id: 'udb_mass_balance',
    title: 'Union Database (UDB) & Registry State Machine',
    sourceFile: '03_UDB_and_European_Registry_Architecture.md',
    category: 'UDB_REGISTRY',
    content: `Under RED III Article 31a and Implementing Regulation (EU) 2022/996, gaseous transport fuels in interconnected pipeline grids must maintain a mass balance chain of custody in the UDB.
Consignment Title Transfer Lifecycle:
1. DRAFT: Initial transaction prepared.
2. SUBMITTED: Registered with origin registry and sent to UDB.
3. ESCROW_LOCKED: Gas volume and green attributes locked in origin account to prevent double-spending.
4. TRANSFERRED: Recipient registry confirms credit to buyer account.
5. BLOCKED: Transfer blocked if cross-border mass balance boundary is broken (e.g. UK injection to EU destination without dedicated interconnection).`
  },
  {
    id: 'efet_biomethane_contracts',
    title: 'EFET Biomethane Master Agreement & Offtake Protection',
    sourceFile: '04_EFET_Biomethane_Contract_Term_Sheet_Analysis.md',
    category: 'CONTRACTS',
    content: `EFET Biomethane Master Agreement decouples physical gas molecule delivery from green environmental attributes (Proof of Sustainability / Guarantees of Origin).
Physical Gas Delivery: Settled at Virtual Trading Point (VTP) based on wholesale Day-Ahead index (e.g. TTF).
Sustainability Proof Default: If the seller delivers gas molecules to the grid but fails to deliver valid Proof of Sustainability (PoS) meeting audited RED III criteria (>= 65% GHG savings), the buyer has the contractual right to re-price the trade down to standard TTF natural gas price without paying the green certificate premium.
Cure Period & Indemnity: Seller has 3 business days to cure delayed PoS delivery. Failure to cure grants buyer right to claim replacement certificate cover costs in open market. Termination Event triggered after 10 business days.`
  }
];

export function getFullKnowledgeContext(): string {
  return KNOWLEDGE_VAULT_DOCS.map(doc => 
    `=== DOCUMENT: ${doc.title} (${doc.sourceFile}) ===\n${doc.content}\n`
  ).join('\n\n');
}
