import { registerSW } from 'virtual:pwa-register';
import { showToast } from './DeskToastContainer';

/**
 * Registers the service worker generated by vite-plugin-pwa and wires it to the
 * desk's toast so a trader is told when a new build is ready (rather than silently
 * running stale code) and when the desk becomes usable offline.
 *
 * Only called in production builds — `devOptions.enabled: false` in vite.config.ts
 * means there is no service worker to register in dev anyway, but this also keeps
 * `virtual:pwa-register`'s registration side effects out of the dev/test loop.
 */
export function registerPWA() {
  if (!import.meta.env.PROD) return;

  let registration: ServiceWorkerRegistration | undefined;

  const updateSW = registerSW({
    immediate: true,
    onRegisteredSW(_swUrl, reg) {
      registration = reg;
    },
    onNeedRefresh() {
      showToast('New version available', 'info', {
        actionLabel: 'Reload',
        onAction: () => updateSW(true),
      });
    },
    onOfflineReady() {
      showToast('Desk ready to work offline');
    },
    onRegisterError(error) {
      console.warn('[pwa] service worker registration failed', error);
    },
  });

  const checkForUpdates = () => {
    registration?.update().catch(() => {
      /* offline or transient network failure — try again next interval */
    });
  };

  // Traders often leave the desk open in a pinned tab for hours; poll for a fresh
  // build periodically and whenever the tab regains focus, rather than only on load.
  window.setInterval(checkForUpdates, 60 * 60 * 1000);
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') checkForUpdates();
  });
}
