/**
 * Shared writer for register-check scripts (verify_fr_sirens.ts, verify_dk_cvrs.ts).
 * Each script saves its country's results to data/registration_checks/<cc>.json; this then
 * regenerates src/domain/plants/registrationChecks.generated.ts from every country file.
 */
import * as fs from 'fs';
import * as path from 'path';

export type CheckStatus = 'CONFIRMED' | 'MISMATCH' | 'NOT_FOUND' | 'ERROR';

export interface RegisterHit {
  name: string;
  naf: string | null;
  /** null when the source does not say whether the company is still active */
  active: boolean | null;
  commune: string | null;
}

export interface CheckResult {
  plantId: string;
  plantName: string;
  claimedId: string;
  status: CheckStatus;
  register: RegisterHit | null;
}

export interface CountryCheckFile {
  countryCode: string;
  source: string;
  checkedAt: string;
  results: CheckResult[];
}

const ROOT = path.join(__dirname, '..', '..');
const DATA_DIR = path.join(ROOT, 'data', 'registration_checks');
const OUT_PATH = path.join(ROOT, 'src', 'domain', 'plants', 'registrationChecks.generated.ts');

export function summarise(results: CheckResult[]): Record<string, number> {
  return results.reduce<Record<string, number>>((acc, r) => ((acc[r.status] = (acc[r.status] ?? 0) + 1), acc), {});
}

export function writeCountryChecks(file: CountryCheckFile): void {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(path.join(DATA_DIR, `${file.countryCode.toLowerCase()}.json`), JSON.stringify(file, null, 2));
  regenerate();
}

export function regenerate(): void {
  const files: CountryCheckFile[] = fs
    .readdirSync(DATA_DIR)
    .filter(f => f.endsWith('.json'))
    .sort()
    .map(f => JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8')));

  const header = files
    .map(f => `//   ${f.countryCode}: ${f.source}, checked ${f.checkedAt} — ${JSON.stringify(summarise(f.results))}`)
    .join('\n');

  const entries = files.flatMap(f =>
    f.results.map(r => {
      const reg = r.register
        ? `{ name: ${JSON.stringify(r.register.name)}, naf: ${JSON.stringify(r.register.naf)}, active: ${JSON.stringify(r.register.active)}, commune: ${JSON.stringify(r.register.commune)} }`
        : 'null';
      return `  ${JSON.stringify(r.plantId)}: { status: '${r.status}', claimedId: ${JSON.stringify(r.claimedId)}, source: ${JSON.stringify(f.source)}, checkedAt: '${f.checkedAt}', register: ${reg} },`;
    }),
  );

  const out = `/* eslint-disable */
// GENERATED by scripts/verify_*.ts from data/registration_checks/*.json — do not edit by hand.
${header}
import { RegistrationCheck } from './types';

export const REGISTRATION_CHECKS: Record<string, RegistrationCheck> = {
${entries.join('\n')}
};
`;
  fs.writeFileSync(OUT_PATH, out);
  console.log('Wrote', path.relative(ROOT, OUT_PATH), `(${entries.length} checks)`);
}
