/**
 * Shared writer for register-match scripts (e.g. match_de_mastr.ts/py).
 * Each script saves its country's results to data/registration_matches/<cc>.json; this then
 * regenerates src/domain/plants/registerMatches.generated.ts from every country file.
 */
import * as fs from 'fs';
import * as path from 'path';
import { RegisterMatch, RegisterMatchCandidate, RegisterMatchStatus } from '../../src/domain/plants/types';

export interface PlantMatchResult {
  plantId: string;
  plantName: string;
  status: RegisterMatchStatus;
  best: RegisterMatchCandidate | null;
  candidates: RegisterMatchCandidate[];
}

export interface CountryMatchesFile {
  countryCode: string;
  source: string;
  checkedAt: string;
  results: PlantMatchResult[];
}

const ROOT = path.join(__dirname, '..', '..');
const DATA_DIR = path.join(ROOT, 'data', 'registration_matches');
const OUT_PATH = path.join(ROOT, 'src', 'domain', 'plants', 'registerMatches.generated.ts');

export function summariseMatches(results: PlantMatchResult[]): Record<string, number> {
  return results.reduce<Record<string, number>>((acc, r) => ((acc[r.status] = (acc[r.status] ?? 0) + 1), acc), {});
}

export function writeCountryMatches(file: CountryMatchesFile): void {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(path.join(DATA_DIR, `${file.countryCode.toLowerCase()}.json`), JSON.stringify(file, null, 2));
  regenerate();
}

export function regenerate(): void {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  const files: CountryMatchesFile[] = fs
    .readdirSync(DATA_DIR)
    .filter(f => f.endsWith('.json'))
    .sort()
    .map(f => JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8')));

  const header = files
    .map(f => `//   ${f.countryCode}: ${f.source}, checked ${f.checkedAt} — ${JSON.stringify(summariseMatches(f.results))}`)
    .join('\n');

  const entries = files.flatMap(f =>
    f.results.map(r => {
      const matchObj: RegisterMatch = {
        status: r.status,
        source: f.source,
        checkedAt: f.checkedAt,
        best: r.best,
        candidates: r.candidates,
      };
      return `  ${JSON.stringify(r.plantId)}: ${JSON.stringify(matchObj)},`;
    }),
  );

  const out = `/* eslint-disable */
// GENERATED by scripts/match_*.ts/py from data/registration_matches/*.json — do not edit by hand.
${header}
import { RegisterMatch } from './types';

export const REGISTER_MATCHES: Record<string, RegisterMatch> = {
${entries.join('\n')}
};
`;
  fs.writeFileSync(OUT_PATH, out);
  console.log('Wrote', path.relative(ROOT, OUT_PATH), `(${entries.length} matches)`);
}
