import { ProductClass, ProvenanceTier } from './brokerMarketData';
import { BrokerOrderEntry } from './brokerRuns';

export interface BrokerRunMeta {
  runId: string;
  broker: string;
  receivedOn: string;
  receivedOnIsApproximate: boolean;
}

export const BASELINE_RUN_META: BrokerRunMeta = {
  runId: 'broker-run-2026-08-18',
  broker: 'Broker (name not recorded)',
  receivedOn: '2026-08-18',
  receivedOnIsApproximate: true,
};

export interface PricingBookEntry {
  id: string;
  baselineId?: string | null;
  runId?: string | null;
  country: string;
  class: string;
  productClass: ProductClass;
  feedstock: string;
  vintage: string;
  certified: string;
  /** '—' = the pasted run did not state it. */
  subsidized: 'Subsidised' | 'Unsubsidised' | '—';
  ciScore: string;
  ciNumeric: number | null;
  currency: 'EUR' | 'GBP';
  bidPrice: string;
  offerPrice: string;
  bidPriceNumeric: number | null;
  offerPriceNumeric: number | null;
  bidText?: string | null;
  offerText?: string | null;
  bidVolume: string;
  offerVolume: string;
  bidVolumeGWh: number | null;
  offerVolumeGWh: number | null;
  bidVolumeText?: string | null;
  offerVolumeText?: string | null;
  numericBidEurMwh?: number | null;
  numericOfferEurMwh?: number | null;
  highlight?: boolean;
  isHighInterest?: boolean;
  derivedFrom?: string;
  provenanceTier: ProvenanceTier;
  observedAt?: string | null;
  isTradeable: boolean;
  isReferenceRow?: boolean;
  isMarketReference?: boolean;
  editedAt?: string | null;
  source?: string | null;
}

export function toBrokerOrderEntry(e: PricingBookEntry): BrokerOrderEntry {
  return {
    id: e.baselineId || e.id,
    country: e.country as any,
    // The seed keeps the order-book class (e.g. THG_BUNDLED); the Corporate supply book only knows GO / RGGO.
    class: (e.class === 'RGGO' ? 'RGGO' : 'GO') as BrokerOrderEntry['class'],
    feedstock: e.feedstock as any,
    vintage: e.vintage,
    certified: e.certified as any,
    subsidized: e.subsidized as BrokerOrderEntry['subsidized'],
    ciScore: e.ciScore,
    ciNumeric: e.ciNumeric,
    currency: e.currency,
    bidPrice: e.bidPriceNumeric,
    bidText: e.bidText,
    offerPrice: e.offerPriceNumeric,
    offerText: e.offerText,
    bidVolumeGWh: e.bidVolumeGWh,
    bidVolumeText: e.bidVolumeText,
    offerVolumeGWh: e.offerVolumeGWh,
    offerVolumeText: e.offerVolumeText,
    isHighInterest: e.isHighInterest,
  };
}

/**
 * The certificate offers the Corporate order pricer can buy from: broker rows that came from the
 * baseline GO/RGGO run, plus pasted GO rows. Bundled compliance quotes (THG, ERE, RTFO) are not GO
 * supply and stay out, exactly as they did when the pricer read BASELINE_BROKER_RUNS.
 */
export function toSupplyEntries(book: PricingBookEntry[]): BrokerOrderEntry[] {
  return book
    .filter(e =>
      e.provenanceTier === 'BROKER_RUN' &&
      (e.baselineId != null || (e.productClass === 'GO_VOLUNTARY' && (e.class === 'GO' || e.class === 'RGGO'))))
    .map(toBrokerOrderEntry);
}

export const INITIAL_PRICING_BOOK: PricingBookEntry[] = [
  {
    "id": "uk_1",
    "baselineId": "uk-rggo-1",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<18gCO2/MJ",
    "ciNumeric": 18,
    "currency": "GBP",
    "bidPrice": "",
    "offerPrice": "£25.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 25,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "15GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 15,
    "bidVolumeText": null,
    "offerVolumeText": "15GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 29.38,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_2",
    "baselineId": "uk-rggo-2",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Crop",
    "vintage": "2027",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 30,
    "currency": "GBP",
    "bidPrice": "",
    "offerPrice": "£21.20",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 21.2,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "30GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 30,
    "bidVolumeText": null,
    "offerVolumeText": "30GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 24.91,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_3",
    "baselineId": "uk-rggo-3",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Crop",
    "vintage": "2026",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 20,
    "currency": "GBP",
    "bidPrice": "",
    "offerPrice": "£19.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 19,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "30GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 30,
    "bidVolumeText": null,
    "offerVolumeText": "30GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 22.33,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_4",
    "baselineId": "uk-rggo-4",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2025",
    "certified": "Certified (A9A)",
    "subsidized": "Subsidised",
    "ciScore": "<-20gCO2/MJ",
    "ciNumeric": -20,
    "currency": "GBP",
    "bidPrice": "",
    "offerPrice": "£23.65",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 23.65,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 27.79,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_5",
    "baselineId": "uk-rggo-5",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Crop",
    "vintage": "2025",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<10gCO2/MJ",
    "ciNumeric": 10,
    "currency": "GBP",
    "bidPrice": "£16.30",
    "offerPrice": "",
    "bidPriceNumeric": 16.3,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": null,
    "bidVolumeText": "10GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": 19.15,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_6",
    "baselineId": "uk-rggo-6",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2024",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 20,
    "currency": "GBP",
    "bidPrice": "",
    "offerPrice": "£17.20",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 17.2,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "15GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 15,
    "bidVolumeText": null,
    "offerVolumeText": "15GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 20.21,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_7",
    "baselineId": "uk-rggo-7",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "H224",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<12gCO2/MJ",
    "ciNumeric": 12,
    "currency": "GBP",
    "bidPrice": "",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_8",
    "baselineId": "uk-rggo-8",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Crop",
    "vintage": "2024",
    "certified": "Certified (ISCC)",
    "subsidized": "Subsidised",
    "ciScore": "<10gCO2/MJ",
    "ciNumeric": 10,
    "currency": "GBP",
    "bidPrice": "£15.25",
    "offerPrice": "£15.90",
    "bidPriceNumeric": 15.25,
    "offerPriceNumeric": 15.9,
    "bidText": null,
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "15GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 15,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "15GWh",
    "numericBidEurMwh": 17.92,
    "numericOfferEurMwh": 18.68,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_9",
    "baselineId": "uk-rggo-9",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "H227",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "GBP",
    "bidPrice": "Buyer",
    "offerPrice": "£20.90",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 20.9,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "10GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 10,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 24.56,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_10",
    "baselineId": "uk-rggo-10",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Crop",
    "vintage": "2025",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "GBP",
    "bidPrice": "£15.90",
    "offerPrice": "",
    "bidPriceNumeric": 15.9,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": 18.68,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_11",
    "baselineId": "uk-rggo-11",
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RGGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "GBP",
    "bidPrice": "£17.90",
    "offerPrice": "",
    "bidPriceNumeric": 17.9,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "10GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 10,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": 21.03,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "uk_rtfo",
    "baselineId": null,
    "runId": "broker-run-2026-08-18",
    "country": "UK",
    "class": "RTFO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure & Slurry (Double Counting)",
    "vintage": "2026",
    "certified": "DfT / ISCC EU",
    "subsidized": "Unsubsidised",
    "ciScore": "<-50gCO2/MJ",
    "ciNumeric": 502,
    "currency": "GBP",
    "bidPrice": "£ 0.205/dRTFC",
    "offerPrice": "£ 0.225/dRTFC",
    "bidPriceNumeric": 0.205,
    "offerPriceNumeric": 0.225,
    "bidText": null,
    "offerText": null,
    "bidVolume": "15GWh",
    "offerVolume": "25GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": "15GWh",
    "offerVolumeText": "25GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Argus Biofuels / Marex RTFO Development Fuel Run (~€38/MWh eq)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_1",
    "baselineId": "fr-go-1",
    "runId": "broker-run-2026-08-18",
    "country": "FR",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste/Crop mix (A9a)",
    "vintage": "H226",
    "certified": "Certified (ETS)",
    "subsidized": "Subsidised",
    "ciScore": "<16gCO2/MJ",
    "ciNumeric": 16,
    "currency": "EUR",
    "bidPrice": "€ 26.50",
    "offerPrice": "",
    "bidPriceNumeric": 26.5,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "35GWh",
    "offerVolume": "",
    "bidVolumeGWh": 35,
    "offerVolumeGWh": null,
    "bidVolumeText": "35GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": 26.5,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_2",
    "baselineId": "fr-go-2",
    "runId": "broker-run-2026-08-18",
    "country": "FR",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "H225",
    "certified": "Certified (ETS)",
    "subsidized": "Subsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 20,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "Seller",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": "Seller",
    "bidVolume": "",
    "offerVolume": "20GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 20,
    "bidVolumeText": null,
    "offerVolumeText": "20GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_3",
    "baselineId": "fr-go-3",
    "runId": "broker-run-2026-08-18",
    "country": "FR",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Mix",
    "vintage": "H225",
    "certified": "Certified (Non-ETS)",
    "subsidized": "Subsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 20,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_4",
    "baselineId": "fr-go-4",
    "runId": "broker-run-2026-08-18",
    "country": "FR",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Mix",
    "vintage": "2027",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": null,
    "bidVolumeText": "10GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_5",
    "baselineId": "fr-go-5",
    "runId": "broker-run-2026-08-18",
    "country": "FR",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Mix",
    "vintage": "2026",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "€ 20.50",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 20.5,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "20GWh",
    "offerVolume": "10GWh",
    "bidVolumeGWh": 20,
    "offerVolumeGWh": 10,
    "bidVolumeText": "20GWh",
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 20.5,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_6",
    "baselineId": "fr-go-6",
    "runId": "broker-run-2026-08-18",
    "country": "FR",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Mix",
    "vintage": "H225",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "25GWh",
    "offerVolume": "",
    "bidVolumeGWh": 25,
    "offerVolumeGWh": null,
    "bidVolumeText": "25GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "fr_cpb",
    "baselineId": null,
    "runId": null,
    "country": "FR",
    "class": "CPB",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Intermediate Crops (CIVE) / Agri",
    "vintage": "2026",
    "certified": "EEX / REDcert",
    "subsidized": "Unsubsidised",
    "ciScore": "<35gCO2/MJ",
    "ciNumeric": 352,
    "currency": "EUR",
    "bidPrice": "€ 76.00",
    "offerPrice": "€ 81.00",
    "bidPriceNumeric": 76,
    "offerPriceNumeric": 81,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Code de l’énergie Art. L.446-24 (Statutory Penalty Cap: €100/MWh)",
    "provenanceTier": "STATUTORY_DIRECTIVE",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "fr_tiruert",
    "baselineId": null,
    "runId": null,
    "country": "FR",
    "class": "TIRUERT",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Annex IX-A Waste Biomethane",
    "vintage": "2026",
    "certified": "DGDDI / ISCC",
    "subsidized": "Unsubsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 202,
    "currency": "EUR",
    "bidPrice": "€ 71.50",
    "offerPrice": "€ 76.50",
    "bidPriceNumeric": 71.5,
    "offerPriceNumeric": 76.5,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "DGDDI French Customs Transport Ticket Clearing Bulletin",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "nl_1",
    "baselineId": "nl-go-1",
    "runId": "broker-run-2026-08-18",
    "country": "NL",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<0gCO2/MJ",
    "ciNumeric": 0,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "€ 50.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 50,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "25GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 25,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "25GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 50,
    "highlight": false,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "nl_2",
    "baselineId": "nl-go-2",
    "runId": "broker-run-2026-08-18",
    "country": "NL",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<-17gCO2/MJ",
    "ciNumeric": -17,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "€ 36.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 36,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "10GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 10,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 36,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "nl_3",
    "baselineId": "nl-go-3",
    "runId": "broker-run-2026-08-18",
    "country": "NL",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<-14gCO2/MJ",
    "ciNumeric": -14,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "€ 34.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 34,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "20GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 20,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "20GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 34,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "nl_4",
    "baselineId": "nl-go-4",
    "runId": "broker-run-2026-08-18",
    "country": "NL",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<0gCO2/MJ",
    "ciNumeric": 0,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "€ 30.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 30,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 30,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "nl_5",
    "baselineId": "nl-go-5",
    "runId": "broker-run-2026-08-18",
    "country": "NL",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "Q425",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 20,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "€ 30.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 30,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "15GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 15,
    "bidVolumeText": null,
    "offerVolumeText": "15GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 30,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "nl_ere",
    "baselineId": null,
    "runId": "broker-run-2026-08-18",
    "country": "NL",
    "class": "ERE",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure & Industrial Bio-Waste",
    "vintage": "2026",
    "certified": "NEa REV / VertiCer",
    "subsidized": "Unsubsidised",
    "ciScore": "<-30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 0.330/kg",
    "offerPrice": "€ 0.350/kg",
    "bidPriceNumeric": 0.33,
    "offerPriceNumeric": 0.35,
    "bidText": null,
    "offerText": null,
    "bidVolume": "20GWh",
    "offerVolume": "30GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": "20GWh",
    "offerVolumeText": "30GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "ACT Commodities / STX REV 2026 Delivery Quote",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "de_1",
    "baselineId": "de-go-1",
    "runId": "broker-run-2026-08-18",
    "country": "DE",
    "class": "THG_BUNDLED",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure + Physical Gas",
    "vintage": "H226",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "-100gCO2/MJ",
    "ciNumeric": -100,
    "currency": "EUR",
    "bidPrice": "€ 147.00",
    "offerPrice": "Seller",
    "bidPriceNumeric": 147,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": "Seller",
    "bidVolume": "10GWh",
    "offerVolume": "10GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 10,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": 147,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "de_2",
    "baselineId": "de-go-2",
    "runId": "broker-run-2026-08-18",
    "country": "DE",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 20,
    "currency": "EUR",
    "bidPrice": "€ 35.00",
    "offerPrice": "€ 44.00",
    "bidPriceNumeric": 35,
    "offerPriceNumeric": 44,
    "bidText": null,
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "10GWh",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": 10,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": 35,
    "numericOfferEurMwh": 44,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "de_3",
    "baselineId": "de-go-3",
    "runId": "broker-run-2026-08-18",
    "country": "DE",
    "class": "THG_BUNDLED",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure + Physical Gas",
    "vintage": "H127",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<-92gCO2/MJ",
    "ciNumeric": -92,
    "currency": "EUR",
    "bidPrice": "€ 141.00",
    "offerPrice": "€ 148.00",
    "bidPriceNumeric": 141,
    "offerPriceNumeric": 148,
    "bidText": null,
    "offerText": null,
    "bidVolume": "15GWh",
    "offerVolume": "15GWh",
    "bidVolumeGWh": 15,
    "offerVolumeGWh": 15,
    "bidVolumeText": "15GWh",
    "offerVolumeText": "15GWh",
    "numericBidEurMwh": 141,
    "numericOfferEurMwh": 148,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "de_thg_1",
    "baselineId": null,
    "runId": "broker-run-2026-08-18",
    "country": "DE",
    "class": "THG",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Liquid Manure (Gülle)",
    "vintage": "2026",
    "certified": "dena / ISCC EU",
    "subsidized": "Unsubsidised",
    "ciScore": "-100gCO2/MJ",
    "ciNumeric": 1002,
    "currency": "EUR",
    "bidPrice": "€ 280.00/t",
    "offerPrice": "€ 290.00/t",
    "bidPriceNumeric": 280,
    "offerPriceNumeric": 290,
    "bidText": null,
    "offerText": null,
    "bidVolume": "20GWh",
    "offerVolume": "30GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": "20GWh",
    "offerVolumeText": "30GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex German Quota Run (§38 BImSchV)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "de_thg_2",
    "baselineId": null,
    "runId": "broker-run-2026-08-18",
    "country": "DE",
    "class": "THG",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Energy Crops (Silomaize)",
    "vintage": "2026",
    "certified": "dena / REDcert",
    "subsidized": "Unsubsidised",
    "ciScore": "+42gCO2/MJ",
    "ciNumeric": 422,
    "currency": "EUR",
    "bidPrice": "€ 125.00/t",
    "offerPrice": "€ 135.00/t",
    "bidPriceNumeric": 125,
    "offerPriceNumeric": 135,
    "bidText": null,
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "15GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": "10GWh",
    "offerVolumeText": "15GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "dena Biogasregister Market Assessment",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_1",
    "baselineId": "dk-go-1",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure/Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<-100gCO2/MJ",
    "ciNumeric": -100,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "20GWh",
    "offerVolume": "",
    "bidVolumeGWh": 20,
    "offerVolumeGWh": null,
    "bidVolumeText": "20GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_2",
    "baselineId": "dk-go-2",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure/Waste",
    "vintage": "2026",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<-50gCO2/MJ",
    "ciNumeric": -50,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "30GWh",
    "offerVolume": "",
    "bidVolumeGWh": 30,
    "offerVolumeGWh": null,
    "bidVolumeText": "30GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_3",
    "baselineId": "dk-go-3",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Manure/Waste",
    "vintage": "2027",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<-70gCO2/MJ",
    "ciNumeric": -70,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "Seller",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": "Seller",
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_4",
    "baselineId": "dk-go-4",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Manure/Waste",
    "vintage": "H226",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<-50gCO2/MJ",
    "ciNumeric": -50,
    "currency": "EUR",
    "bidPrice": "€ 44.00",
    "offerPrice": "Seller",
    "bidPriceNumeric": 44,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": "Seller",
    "bidVolume": "20GWh",
    "offerVolume": "20GWh",
    "bidVolumeGWh": 20,
    "offerVolumeGWh": 20,
    "bidVolumeText": "20GWh",
    "offerVolumeText": "20GWh",
    "numericBidEurMwh": 44,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_5",
    "baselineId": "dk-go-5",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2027",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<20gCO2",
    "ciNumeric": 20,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "€ 37.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 37,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 37,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_6",
    "baselineId": "dk-go-6",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste",
    "vintage": "2026",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "Seller",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": "Seller",
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "dk_7",
    "baselineId": "dk-go-7",
    "runId": "broker-run-2026-08-18",
    "country": "DK",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Crop",
    "vintage": "2026",
    "certified": "Uncertified",
    "subsidized": "Subsidised",
    "ciScore": "—",
    "ciNumeric": null,
    "currency": "EUR",
    "bidPrice": "€ 22.50",
    "offerPrice": "",
    "bidPriceNumeric": 22.5,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "10GWh",
    "offerVolume": "",
    "bidVolumeGWh": 10,
    "offerVolumeGWh": null,
    "bidVolumeText": "10GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": 22.5,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "aib_1",
    "baselineId": "aib-go-1",
    "runId": "broker-run-2026-08-18",
    "country": "AIB",
    "class": "GO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure",
    "vintage": "2027",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<-100gCO2/MJ",
    "ciNumeric": -100,
    "currency": "EUR",
    "bidPrice": "€ 126.00",
    "offerPrice": "",
    "bidPriceNumeric": 126,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": null,
    "bidVolume": "15GWh",
    "offerVolume": "",
    "bidVolumeGWh": 15,
    "offerVolumeGWh": null,
    "bidVolumeText": "15GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": 126,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "aib_2",
    "baselineId": "aib-go-2",
    "runId": "broker-run-2026-08-18",
    "country": "AIB",
    "class": "GO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure",
    "vintage": "2027/28",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<-100gCO2/MJ",
    "ciNumeric": -100,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "€ 126.00",
    "bidPriceNumeric": null,
    "offerPriceNumeric": 126,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "30-50GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 40,
    "bidVolumeText": null,
    "offerVolumeText": "30-50GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": 126,
    "highlight": true,
    "isHighInterest": true,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "aib_3",
    "baselineId": "aib-go-3",
    "runId": "broker-run-2026-08-18",
    "country": "AIB",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Waste/Crop",
    "vintage": "2027",
    "certified": "Certified",
    "subsidized": "Unsubsidised",
    "ciScore": "<-5gCO2/MJ",
    "ciNumeric": -5,
    "currency": "EUR",
    "bidPrice": "",
    "offerPrice": "Seller",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": null,
    "offerText": "Seller",
    "bidVolume": "",
    "offerVolume": "10GWh",
    "bidVolumeGWh": null,
    "offerVolumeGWh": 10,
    "bidVolumeText": null,
    "offerVolumeText": "10GWh",
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "aib_4",
    "baselineId": "aib-go-4",
    "runId": "broker-run-2026-08-18",
    "country": "AIB",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Manure/Waste",
    "vintage": "Q426",
    "certified": "Certified",
    "subsidized": "Subsidised",
    "ciScore": "<-25gCO2/MJ",
    "ciNumeric": -25,
    "currency": "EUR",
    "bidPrice": "Buyer",
    "offerPrice": "",
    "bidPriceNumeric": null,
    "offerPriceNumeric": null,
    "bidText": "Buyer",
    "offerText": null,
    "bidVolume": "20-30GWh",
    "offerVolume": "",
    "bidVolumeGWh": 25,
    "offerVolumeGWh": null,
    "bidVolumeText": "20-30GWh",
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "STX / Marex OTC Broker Run (2026/2027)",
    "provenanceTier": "BROKER_RUN",
    "observedAt": "2026-08-18",
    "isTradeable": true,
    "isReferenceRow": false
  },
  {
    "id": "it_1",
    "baselineId": null,
    "runId": null,
    "country": "IT",
    "class": "CIC",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Liquid Manure / Slurry (Advanced)",
    "vintage": "2026",
    "certified": "GSE / ISCC EU",
    "subsidized": "Unsubsidised",
    "ciScore": "<-50gCO2/MJ",
    "ciNumeric": 502,
    "currency": "EUR",
    "bidPrice": "€ 338.00/CIC",
    "offerPrice": "€ 352.00/CIC",
    "bidPriceNumeric": 338,
    "offerPriceNumeric": 352,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": false,
    "derivedFrom": "GSE DM 2 March 2018 Statutory Fix / GME Bilateral (~€29.66/MWh eq)",
    "provenanceTier": "STATUTORY_DIRECTIVE",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "it_2",
    "baselineId": null,
    "runId": null,
    "country": "IT",
    "class": "CIC",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Waste / FORSU",
    "vintage": "2026",
    "certified": "GSE / REDcert",
    "subsidized": "Unsubsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 202,
    "currency": "EUR",
    "bidPrice": "€ 310.00/CIC",
    "offerPrice": "€ 330.00/CIC",
    "bidPriceNumeric": 310,
    "offerPriceNumeric": 330,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "GSE National Biofuel Index (~€26.65/MWh eq)",
    "provenanceTier": "STATUTORY_DIRECTIVE",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "it_3",
    "baselineId": null,
    "runId": null,
    "country": "IT",
    "class": "GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Agro-Industrial Waste",
    "vintage": "2026",
    "certified": "GSE GdO",
    "subsidized": "Subsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 21.00",
    "offerPrice": "€ 24.50",
    "bidPriceNumeric": 21,
    "offerPriceNumeric": 24.5,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "GSE Biomethane Auction Clearing Bulletin",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "es_1",
    "baselineId": null,
    "runId": null,
    "country": "ES",
    "class": "GdO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Pig & Cattle Slurry",
    "vintage": "2026",
    "certified": "Enagás GTS / ISCC EU",
    "subsidized": "Unsubsidised",
    "ciScore": "<-60gCO2/MJ",
    "ciNumeric": 602,
    "currency": "EUR",
    "bidPrice": "€ 48.00",
    "offerPrice": "€ 54.00",
    "bidPriceNumeric": 48,
    "offerPriceNumeric": 54,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": true,
    "isHighInterest": false,
    "derivedFrom": "Enagás GTS / MIBGAS Wholesale Biomethane Bulletin",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "es_2",
    "baselineId": null,
    "runId": null,
    "country": "ES",
    "class": "GdO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Agro-Food Waste",
    "vintage": "2026",
    "certified": "Enagás GTS",
    "subsidized": "Subsidised",
    "ciScore": "<25gCO2/MJ",
    "ciNumeric": 252,
    "currency": "EUR",
    "bidPrice": "€ 42.00",
    "offerPrice": "€ 48.00",
    "bidPriceNumeric": 42,
    "offerPriceNumeric": 48,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Real Decreto 376/2022 PNIEC Transport Mandate",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "se_tax",
    "baselineId": null,
    "runId": null,
    "country": "SE",
    "class": "TAX_EXEMPT",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Sewage Sludge & Food Waste",
    "vintage": "2026",
    "certified": "Energimyndigheten",
    "subsidized": "Unsubsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 202,
    "currency": "EUR",
    "bidPrice": "€ 79.00",
    "offerPrice": "€ 85.00",
    "bidPriceNumeric": 79,
    "offerPriceNumeric": 85,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Skatteverket / Lag (1994:1776) State Aid Exemption",
    "provenanceTier": "STATUTORY_DIRECTIVE",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "at_egg",
    "baselineId": null,
    "runId": null,
    "country": "AT",
    "class": "EGG",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agricultural Waste & Crops",
    "vintage": "2026",
    "certified": "AGCS / ISCC",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 82.00",
    "offerPrice": "€ 88.00",
    "bidPriceNumeric": 82,
    "offerPriceNumeric": 88,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "AGCS / E-Control Erneuerbaren-Gase-Gesetz Quota",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "fi_trans",
    "baselineId": null,
    "runId": null,
    "country": "FI",
    "class": "TRANSPORT",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Municipal Bio-Waste / Manure",
    "vintage": "2026",
    "certified": "Gasgrid Finland",
    "subsidized": "Unsubsidised",
    "ciScore": "<25gCO2/MJ",
    "ciNumeric": 252,
    "currency": "EUR",
    "bidPrice": "€ 68.00",
    "offerPrice": "€ 76.00",
    "bidPriceNumeric": 68,
    "offerPriceNumeric": 76,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Gasgrid Finland Ex-Domain Distribution Report",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "be_trans",
    "baselineId": null,
    "runId": null,
    "country": "BE",
    "class": "TRANSPORT",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agri-Waste & Sewage Sludge",
    "vintage": "2026",
    "certified": "VREG / SPW",
    "subsidized": "Unsubsidised",
    "ciScore": "<25gCO2/MJ",
    "ciNumeric": 252,
    "currency": "EUR",
    "bidPrice": "€ 64.00",
    "offerPrice": "€ 72.00",
    "bidPriceNumeric": 64,
    "offerPriceNumeric": 72,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "VREG Flanders / SPW Wallonia Regional Registry",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "pl_oze",
    "baselineId": null,
    "runId": null,
    "country": "PL",
    "class": "OZE",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agri-Food Residues & Beet Pulp",
    "vintage": "2026",
    "certified": "URE / KZR INiG",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 63.00",
    "offerPrice": "€ 70.00",
    "bidPriceNumeric": 63,
    "offerPriceNumeric": 70,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "URE Polish Energy Regulatory Office Feed-In Act (285 PLN eq)",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "cz_poze",
    "baselineId": null,
    "runId": null,
    "country": "CZ",
    "class": "POZE",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agri-Waste & Energy Crops",
    "vintage": "2026",
    "certified": "OTE / ISCC",
    "subsidized": "Unsubsidised",
    "ciScore": "<35gCO2/MJ",
    "ciNumeric": 352,
    "currency": "EUR",
    "bidPrice": "€ 63.50",
    "offerPrice": "€ 70.50",
    "bidPriceNumeric": 63.5,
    "offerPriceNumeric": 70.5,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "OTE Gas Hub Bulletin / POZE Operational Premium",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "ch_vsg",
    "baselineId": null,
    "runId": null,
    "country": "CH",
    "class": "VSG",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Manure & Municipal Green Waste",
    "vintage": "2026",
    "certified": "Pronovo / VSG",
    "subsidized": "Unsubsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 202,
    "currency": "EUR",
    "bidPrice": "€ 94.00",
    "offerPrice": "€ 102.00",
    "bidPriceNumeric": 94,
    "offerPriceNumeric": 102,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Pronovo / VSG Swiss CO2 Law Index (Non-EU Grid)",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "no_bio",
    "baselineId": null,
    "runId": null,
    "country": "NO",
    "class": "BIOFUEL",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Fish Sludge & Manure (Bio-LNG)",
    "vintage": "2026",
    "certified": "Miljødirektoratet",
    "subsidized": "Unsubsidised",
    "ciScore": "<-40gCO2/MJ",
    "ciNumeric": 402,
    "currency": "EUR",
    "bidPrice": "€ 64.00",
    "offerPrice": "€ 72.00",
    "bidPriceNumeric": 64,
    "offerPriceNumeric": 72,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Miljødirektoratet Road & Maritime Quota Assessment",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "ee_trans",
    "baselineId": null,
    "runId": null,
    "country": "EE",
    "class": "TRANSPORT",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Cattle Slurry & Sewage",
    "vintage": "2026",
    "certified": "Elering",
    "subsidized": "Unsubsidised",
    "ciScore": "<20gCO2/MJ",
    "ciNumeric": 202,
    "currency": "EUR",
    "bidPrice": "€ 60.00",
    "offerPrice": "€ 68.00",
    "bidPriceNumeric": 60,
    "offerPriceNumeric": 68,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Elering 100% Municipal Bus Fleet Obligation",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "lt_alt",
    "baselineId": null,
    "runId": null,
    "country": "LT",
    "class": "ALT_FUELS",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Waste & Manure",
    "vintage": "2026",
    "certified": "Amber Grid",
    "subsidized": "Unsubsidised",
    "ciScore": "<25gCO2/MJ",
    "ciNumeric": 252,
    "currency": "EUR",
    "bidPrice": "€ 58.00",
    "offerPrice": "€ 66.00",
    "bidPriceNumeric": 58,
    "offerPriceNumeric": 66,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Amber Grid Alternative Fuels Transport Mandate",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "lv_con",
    "baselineId": null,
    "runId": null,
    "country": "LV",
    "class": "STORAGE_GO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Agro-Industrial Waste",
    "vintage": "2026",
    "certified": "Conexus",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 55.00",
    "offerPrice": "€ 63.00",
    "bidPriceNumeric": 55,
    "offerPriceNumeric": 63,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Conexus Baltic Grid Inčukalns Storage GO",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "ie_rho",
    "baselineId": null,
    "runId": null,
    "country": "IE",
    "class": "RHO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Grass Silage & Slurry",
    "vintage": "2026",
    "certified": "GNI",
    "subsidized": "Unsubsidised",
    "ciScore": "<35gCO2/MJ",
    "ciNumeric": 352,
    "currency": "EUR",
    "bidPrice": "€ 65.00",
    "offerPrice": "€ 72.00",
    "bidPriceNumeric": 65,
    "offerPriceNumeric": 72,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Gas Networks Ireland / Cost-Plus Parity Model",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "pt_eego",
    "baselineId": null,
    "runId": null,
    "country": "PT",
    "class": "EEGO",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Pig Slurry & Agri-Waste",
    "vintage": "2026",
    "certified": "REN / EEGO",
    "subsidized": "Unsubsidised",
    "ciScore": "<25gCO2/MJ",
    "ciNumeric": 252,
    "currency": "EUR",
    "bidPrice": "€ 53.00",
    "offerPrice": "€ 59.00",
    "bidPriceNumeric": 53,
    "offerPriceNumeric": 59,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "REN / EEGO Support Model (DL 84/2022)",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "hu_mekh",
    "baselineId": null,
    "runId": null,
    "country": "HU",
    "class": "MEKH",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Residues & Maize",
    "vintage": "2026",
    "certified": "MEKH",
    "subsidized": "Unsubsidised",
    "ciScore": "<35gCO2/MJ",
    "ciNumeric": 352,
    "currency": "EUR",
    "bidPrice": "€ 59.00",
    "offerPrice": "€ 65.00",
    "bidPriceNumeric": 59,
    "offerPriceNumeric": 65,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "FGSZ / MEKH Framework Model",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "sk_okte",
    "baselineId": null,
    "runId": null,
    "country": "SK",
    "class": "OKTE",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Biomass",
    "vintage": "2026",
    "certified": "OKTE",
    "subsidized": "Unsubsidised",
    "ciScore": "<35gCO2/MJ",
    "ciNumeric": 352,
    "currency": "EUR",
    "bidPrice": "€ 61.00",
    "offerPrice": "€ 67.00",
    "bidPriceNumeric": 61,
    "offerPriceNumeric": 67,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "OKTE / SPP-D Injection Model",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "ro_trans",
    "baselineId": null,
    "runId": null,
    "country": "RO",
    "class": "TRANSGAZ",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Waste & Straw",
    "vintage": "2026",
    "certified": "ANRE",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 55.00",
    "offerPrice": "€ 61.00",
    "bidPriceNumeric": 55,
    "offerPriceNumeric": 61,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Transgaz Grid Model / ANRE",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "bg_bulg",
    "baselineId": null,
    "runId": null,
    "country": "BG",
    "class": "BULGARTRANS",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Residues",
    "vintage": "2026",
    "certified": "Bulgartransgaz",
    "subsidized": "Unsubsidised",
    "ciScore": "<35gCO2/MJ",
    "ciNumeric": 352,
    "currency": "EUR",
    "bidPrice": "€ 54.00",
    "offerPrice": "€ 60.00",
    "bidPriceNumeric": 54,
    "offerPriceNumeric": 60,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Bulgartransgaz Network Statement Model",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "hr_plin",
    "baselineId": null,
    "runId": null,
    "country": "HR",
    "class": "PLINACRO",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Agro-Food Waste",
    "vintage": "2026",
    "certified": "HROTE",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 58.00",
    "offerPrice": "€ 64.00",
    "bidPriceNumeric": 58,
    "offerPriceNumeric": 64,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "HROTE / Plinacro System Model",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "si_borz",
    "baselineId": null,
    "runId": null,
    "country": "SI",
    "class": "BORZEN",
    "productClass": "GO_VOLUNTARY",
    "feedstock": "Silage & Bio-Waste",
    "vintage": "2026",
    "certified": "Borzen",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 62.00",
    "offerPrice": "€ 68.00",
    "bidPriceNumeric": 62,
    "offerPriceNumeric": 68,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Borzen / Plinovodi Registry Model",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "gr_desf",
    "baselineId": null,
    "runId": null,
    "country": "GR",
    "class": "DESFA",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Olive Pomace & Slurry",
    "vintage": "2026",
    "certified": "DESFA / RAE",
    "subsidized": "Unsubsidised",
    "ciScore": "<25gCO2/MJ",
    "ciNumeric": 252,
    "currency": "EUR",
    "bidPrice": "€ 60.00",
    "offerPrice": "€ 66.00",
    "bidPriceNumeric": 60,
    "offerPriceNumeric": 66,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "DESFA Scheme Model / Greek Law 4951",
    "provenanceTier": "MODELLED_SIMULATED",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "eu_fueleu",
    "baselineId": null,
    "runId": null,
    "country": "EU",
    "class": "FUELEU",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Bio-LNG / Advanced Biomethane",
    "vintage": "2026",
    "certified": "Thetis-MRV / EU DB",
    "subsidized": "Unsubsidised",
    "ciScore": "<-50gCO2/MJ",
    "ciNumeric": 502,
    "currency": "EUR",
    "bidPrice": "€ 270.00/t",
    "offerPrice": "€ 300.00/t",
    "bidPriceNumeric": 270,
    "offerPriceNumeric": 300,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "Regulation (EU) 2023/1805 Statutory Deficit Penalty",
    "provenanceTier": "STATUTORY_DIRECTIVE",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  },
  {
    "id": "eu_ets1",
    "baselineId": null,
    "runId": null,
    "country": "EU",
    "class": "EU_ETS",
    "productClass": "BUNDLED_COMPLIANCE",
    "feedstock": "Industrial Natural Gas Displacement",
    "vintage": "2026",
    "certified": "Union Registry",
    "subsidized": "Unsubsidised",
    "ciScore": "<30gCO2/MJ",
    "ciNumeric": 302,
    "currency": "EUR",
    "bidPrice": "€ 83.90/t",
    "offerPrice": "€ 86.90/t",
    "bidPriceNumeric": 83.9,
    "offerPriceNumeric": 86.9,
    "bidText": null,
    "offerText": null,
    "bidVolume": "",
    "offerVolume": "",
    "bidVolumeGWh": null,
    "offerVolumeGWh": null,
    "bidVolumeText": null,
    "offerVolumeText": null,
    "numericBidEurMwh": null,
    "numericOfferEurMwh": null,
    "highlight": false,
    "isHighInterest": false,
    "derivedFrom": "ICE EUA Dec-26 (GMK Center, 8 Sep 2026; secondary source) (~€17.25/MWh avoided)",
    "provenanceTier": "WEB_INDEX",
    "observedAt": null,
    "isTradeable": false,
    "isReferenceRow": true
  }
];
