export type ProductClass = 'BUNDLED_COMPLIANCE' | 'GO_VOLUNTARY' | 'PHYSICAL_BROWN' | 'TICKET_ONLY';

export type ProvenanceTier = 'BROKER_RUN' | 'WEB_INDEX' | 'STATUTORY_DIRECTIVE' | 'MODELLED_SIMULATED';

export interface BrokerMarketQuote {
  id: string;
  country: string;
  class: string;
  productClass: ProductClass;
  feedstock: string;
  vintage: string;
  certified: string;
  subsidized: 'Subsidised' | 'Unsubsidised';
  ciScore: string;
  bidPrice: string; // e.g. "£16.30", "€147.00", "Buyer", or empty
  offerPrice: string; // e.g. "£25.00", "€50.00", "Seller", or empty
  bidVolume: string; // e.g. "10GWh", "35GWh"
  offerVolume: string; // e.g. "15GWh", "30GWh"
  currency: 'GBP' | 'EUR';
  numericBidEurMwh?: number | null;
  numericOfferEurMwh?: number | null;
  highlight?: boolean;
  derivedFrom?: string; // Exact institutional / market source where price is derived from
  provenanceTier?: ProvenanceTier;
  observedAt?: string; // ISO date or observation date
}

/**
 * Master Pan-European Biomethane Pricing Book
 * Contains all bilateral OTC broker runs (STX, Marex, ACT) plus sovereign compliance quotas,
 * statutory schemes, and regional European hubs with explicit data provenance.
 */
export const INITIAL_BROKER_QUOTES: BrokerMarketQuote[] = [
  // =========================================================================
  // 1. UNITED KINGDOM (RGGO & RTFO)
  // =========================================================================
  { id: 'uk_1', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<18gCO2/MJ', bidPrice: '', offerPrice: '£25.00', bidVolume: '', offerVolume: '15GWh', currency: 'GBP', numericOfferEurMwh: 29.38, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_2', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Crop', vintage: '2027', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<30gCO2/MJ', bidPrice: '', offerPrice: '£21.20', bidVolume: '', offerVolume: '30GWh', currency: 'GBP', numericOfferEurMwh: 24.91, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_3', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Crop', vintage: '2026', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<20gCO2/MJ', bidPrice: '', offerPrice: '£19.00', bidVolume: '', offerVolume: '30GWh', currency: 'GBP', numericOfferEurMwh: 22.33, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_4', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2025', certified: 'Certified (A9A)', subsidized: 'Subsidised', ciScore: '<-20gCO2/MJ', bidPrice: '', offerPrice: '£23.65', bidVolume: '', offerVolume: '10GWh', currency: 'GBP', numericOfferEurMwh: 27.79, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_5', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Crop', vintage: '2025', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<10gCO2/MJ', bidPrice: '£16.30', offerPrice: '', bidVolume: '10GWh', offerVolume: '', currency: 'GBP', numericBidEurMwh: 19.15, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_6', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2024', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<20gCO2/MJ', bidPrice: '', offerPrice: '£17.20', bidVolume: '', offerVolume: '15GWh', currency: 'GBP', numericOfferEurMwh: 20.21, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_7', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: 'H224', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<12gCO2/MJ', bidPrice: '', offerPrice: '', bidVolume: '', offerVolume: '', currency: 'GBP', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_8', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Crop', vintage: '2024', certified: 'Certified (ISCC)', subsidized: 'Subsidised', ciScore: '<10gCO2/MJ', bidPrice: '£15.25', offerPrice: '£15.90', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'GBP', numericBidEurMwh: 17.92, numericOfferEurMwh: 18.68, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_9', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: 'H227', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: 'Buyer', offerPrice: '£20.90', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'GBP', numericOfferEurMwh: 24.56, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_10', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Crop', vintage: '2025', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: '£15.90', offerPrice: '', bidVolume: '', offerVolume: '10GWh', currency: 'GBP', numericBidEurMwh: 18.68, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_11', country: 'UK', class: 'RGGO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: '£17.90', offerPrice: '', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'GBP', numericBidEurMwh: 21.03, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'uk_rtfo', country: 'UK', class: 'RTFO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure & Slurry (Double Counting)', vintage: '2026', certified: 'DfT / ISCC EU', subsidized: 'Unsubsidised', ciScore: '<-50gCO2/MJ', bidPrice: '£ 0.205/dRTFC', offerPrice: '£ 0.225/dRTFC', bidVolume: '15GWh', offerVolume: '25GWh', currency: 'GBP', derivedFrom: 'Argus Biofuels / Marex RTFO Development Fuel Run (~€38/MWh eq)', provenanceTier: 'BROKER_RUN' },

  // =========================================================================
  // 2. FRANCE (GO & COMPLIANCE CPB / TIRUERT)
  // =========================================================================
  { id: 'fr_1', country: 'FR', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste/Crop mix (A9a)', vintage: 'H226', certified: 'Certified (ETS)', subsidized: 'Subsidised', ciScore: '<16gCO2/MJ', bidPrice: '€ 26.50', offerPrice: '', bidVolume: '35GWh', offerVolume: '', currency: 'EUR', numericBidEurMwh: 26.50, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'fr_2', country: 'FR', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: 'H225', certified: 'Certified (ETS)', subsidized: 'Subsidised', ciScore: '<20gCO2/MJ', bidPrice: '', offerPrice: 'Seller', bidVolume: '', offerVolume: '20GWh', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'fr_3', country: 'FR', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Mix', vintage: 'H225', certified: 'Certified (Non-ETS)', subsidized: 'Subsidised', ciScore: '<20gCO2/MJ', bidPrice: '', offerPrice: '', bidVolume: '', offerVolume: '', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'fr_4', country: 'FR', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Mix', vintage: '2027', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: 'Buyer', offerPrice: '', bidVolume: '10GWh', offerVolume: '', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'fr_5', country: 'FR', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Mix', vintage: '2026', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: 'Buyer', offerPrice: '€ 20.50', bidVolume: '20GWh', offerVolume: '10GWh', currency: 'EUR', numericOfferEurMwh: 20.50, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'fr_6', country: 'FR', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Mix', vintage: 'H225', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: 'Buyer', offerPrice: '', bidVolume: '25GWh', offerVolume: '', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'fr_cpb', country: 'FR', class: 'CPB', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Intermediate Crops (CIVE) / Agri', vintage: '2026', certified: 'EEX / REDcert', subsidized: 'Unsubsidised', ciScore: '<35gCO2/MJ', bidPrice: '€ 76.00', offerPrice: '€ 81.00', bidVolume: '30GWh', offerVolume: '50GWh', currency: 'EUR', derivedFrom: 'Code de l’énergie Art. L.446-24 (Statutory Penalty Cap: €100/MWh)', provenanceTier: 'STATUTORY_DIRECTIVE' },
  { id: 'fr_tiruert', country: 'FR', class: 'TIRUERT', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Annex IX-A Waste Biomethane', vintage: '2026', certified: 'DGDDI / ISCC', subsidized: 'Unsubsidised', ciScore: '<20gCO2/MJ', bidPrice: '€ 71.50', offerPrice: '€ 76.50', bidVolume: '20GWh', offerVolume: '40GWh', currency: 'EUR', derivedFrom: 'DGDDI French Customs Transport Ticket Clearing Bulletin', provenanceTier: 'WEB_INDEX' },

  // =========================================================================
  // 3. NETHERLANDS (GO & ERE QUOTA)
  // =========================================================================
  { id: 'nl_1', country: 'NL', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<0gCO2/MJ', bidPrice: 'Buyer', offerPrice: '€ 50.00', bidVolume: '10GWh', offerVolume: '25GWh', currency: 'EUR', numericOfferEurMwh: 50.00, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'nl_2', country: 'NL', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<-17gCO2/MJ', bidPrice: 'Buyer', offerPrice: '€ 36.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', numericOfferEurMwh: 36.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'nl_3', country: 'NL', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<-14gCO2/MJ', bidPrice: 'Buyer', offerPrice: '€ 34.00', bidVolume: '10GWh', offerVolume: '20GWh', currency: 'EUR', numericOfferEurMwh: 34.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'nl_4', country: 'NL', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<0gCO2/MJ', bidPrice: '', offerPrice: '€ 30.00', bidVolume: '', offerVolume: '10GWh', currency: 'EUR', numericOfferEurMwh: 30.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'nl_5', country: 'NL', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: 'Q425', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<20gCO2/MJ', bidPrice: '', offerPrice: '€ 30.00', bidVolume: '', offerVolume: '15GWh', currency: 'EUR', numericOfferEurMwh: 30.00, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'nl_ere', country: 'NL', class: 'ERE', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure & Industrial Bio-Waste', vintage: '2026', certified: 'NEa REV / VertiCer', subsidized: 'Unsubsidised', ciScore: '<-30gCO2/MJ', bidPrice: '€ 0.330/kg', offerPrice: '€ 0.350/kg', bidVolume: '20GWh', offerVolume: '30GWh', currency: 'EUR', highlight: true, derivedFrom: 'ACT Commodities / STX REV 2026 Delivery Quote', provenanceTier: 'BROKER_RUN' },

  // =========================================================================
  // 4. GERMANY (THG BUNDLED & GO)
  // =========================================================================
  { id: 'de_1', country: 'DE', class: 'THG_BUNDLED', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure + Physical Gas', vintage: 'H226', certified: 'Certified (ISCC EU)', subsidized: 'Unsubsidised', ciScore: '-100gCO2/MJ', bidPrice: '€ 147.00', offerPrice: 'Seller', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', numericBidEurMwh: 147.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'de_2', country: 'DE', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<20gCO2/MJ', bidPrice: '€ 35.00', offerPrice: '€ 44.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', numericBidEurMwh: 35.00, numericOfferEurMwh: 44.00, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'de_3', country: 'DE', class: 'THG_BUNDLED', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure + Physical Gas', vintage: 'H127', certified: 'Certified (ISCC EU)', subsidized: 'Unsubsidised', ciScore: '<-92gCO2/MJ', bidPrice: '€ 141.00', offerPrice: '€ 148.00', bidVolume: '15GWh', offerVolume: '15GWh', currency: 'EUR', numericBidEurMwh: 141.00, numericOfferEurMwh: 148.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'de_thg_1', country: 'DE', class: 'THG', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Liquid Manure (Gülle)', vintage: '2026', certified: 'dena / ISCC EU', subsidized: 'Unsubsidised', ciScore: '-100gCO2/MJ', bidPrice: '€ 280.00/t', offerPrice: '€ 290.00/t', bidVolume: '20GWh', offerVolume: '30GWh', currency: 'EUR', highlight: true, derivedFrom: 'STX / Marex German Quota Run (§38 BImSchV)', provenanceTier: 'BROKER_RUN' },
  { id: 'de_thg_2', country: 'DE', class: 'THG', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Energy Crops (Silomaize)', vintage: '2026', certified: 'dena / REDcert', subsidized: 'Unsubsidised', ciScore: '+42gCO2/MJ', bidPrice: '€ 125.00/t', offerPrice: '€ 135.00/t', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'dena Biogasregister Market Assessment', provenanceTier: 'BROKER_RUN' },

  // =========================================================================
  // 5. DENMARK (ENERGINET EXPORT & MASS BALANCE)
  // =========================================================================
  { id: 'dk_1', country: 'DK', class: 'GO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure/Waste', vintage: '2026', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<-100gCO2/MJ', bidPrice: 'Buyer', offerPrice: '', bidVolume: '20GWh', offerVolume: '', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'dk_2', country: 'DK', class: 'GO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure/Waste', vintage: '2026', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<-50gCO2/MJ', bidPrice: 'Buyer', offerPrice: '', bidVolume: '30GWh', offerVolume: '', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'dk_3', country: 'DK', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Manure/Waste', vintage: '2027', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<-70gCO2/MJ', bidPrice: '', offerPrice: 'Seller', bidVolume: '', offerVolume: '10GWh', currency: 'EUR', highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'dk_4', country: 'DK', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Manure/Waste', vintage: 'H226', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<-50gCO2/MJ', bidPrice: '€ 44.00', offerPrice: 'Seller', bidVolume: '20GWh', offerVolume: '20GWh', currency: 'EUR', numericBidEurMwh: 44.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'dk_5', country: 'DK', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2027', certified: 'Certified', subsidized: 'Subsidised', ciScore: '<20gCO2', bidPrice: '', offerPrice: '€ 37.00', bidVolume: '', offerVolume: '10GWh', currency: 'EUR', numericOfferEurMwh: 37.00, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'dk_6', country: 'DK', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste', vintage: '2026', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: '', offerPrice: 'Seller', bidVolume: '', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'dk_7', country: 'DK', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Crop', vintage: '2026', certified: 'Uncertified', subsidized: 'Subsidised', ciScore: '', bidPrice: '€ 22.50', offerPrice: '', bidVolume: '10GWh', offerVolume: '', currency: 'EUR', numericBidEurMwh: 22.50, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },

  // =========================================================================
  // 6. AIB EUROPEAN EECS HUB
  // =========================================================================
  { id: 'aib_1', country: 'AIB', class: 'GO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure', vintage: '2027', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<-100gCO2/MJ', bidPrice: '€ 126.00', offerPrice: '', bidVolume: '15GWh', offerVolume: '', currency: 'EUR', numericBidEurMwh: 126.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'aib_2', country: 'AIB', class: 'GO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure', vintage: '2027/28', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<-100gCO2/MJ', bidPrice: 'Buyer', offerPrice: '€ 126.00', bidVolume: '', offerVolume: '30-50GWh', currency: 'EUR', numericOfferEurMwh: 126.00, highlight: true, derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'aib_3', country: 'AIB', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Waste/Crop', vintage: '2027', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<-5gCO2/MJ', bidPrice: '', offerPrice: 'Seller', bidVolume: '', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },
  { id: 'aib_4', country: 'AIB', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Manure/Waste', vintage: 'Q426', certified: 'Certified', subsidized: 'Unsubsidised', ciScore: '<-25gCO2/MJ', bidPrice: 'Buyer', offerPrice: '', bidVolume: '20-30GWh', offerVolume: '', currency: 'EUR', derivedFrom: 'STX / Marex OTC Broker Run (2026/2027)', provenanceTier: 'BROKER_RUN' },

  // =========================================================================
  // 7. ITALY (GSE CIC & GdO)
  // =========================================================================
  { id: 'it_1', country: 'IT', class: 'CIC', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Liquid Manure / Slurry (Advanced)', vintage: '2026', certified: 'GSE / ISCC EU', subsidized: 'Unsubsidised', ciScore: '<-50gCO2/MJ', bidPrice: '€ 338.00/CIC', offerPrice: '€ 352.00/CIC', bidVolume: '25GWh', offerVolume: '25GWh', currency: 'EUR', highlight: true, derivedFrom: 'GSE DM 2 March 2018 Statutory Fix / GME Bilateral (~€29.66/MWh eq)', provenanceTier: 'STATUTORY_DIRECTIVE' },
  { id: 'it_2', country: 'IT', class: 'CIC', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Waste / FORSU', vintage: '2026', certified: 'GSE / REDcert', subsidized: 'Unsubsidised', ciScore: '<20gCO2/MJ', bidPrice: '€ 310.00/CIC', offerPrice: '€ 330.00/CIC', bidVolume: '20GWh', offerVolume: '30GWh', currency: 'EUR', derivedFrom: 'GSE National Biofuel Index (~€26.65/MWh eq)', provenanceTier: 'STATUTORY_DIRECTIVE' },
  { id: 'it_3', country: 'IT', class: 'GO', productClass: 'GO_VOLUNTARY', feedstock: 'Agro-Industrial Waste', vintage: '2026', certified: 'GSE GdO', subsidized: 'Subsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 21.00', offerPrice: '€ 24.50', bidVolume: '15GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'GSE Biomethane Auction Clearing Bulletin', provenanceTier: 'WEB_INDEX' },

  // =========================================================================
  // 8. SPAIN (ENAGÁS GdO & PNIEC MANDATE)
  // =========================================================================
  { id: 'es_1', country: 'ES', class: 'GdO', productClass: 'GO_VOLUNTARY', feedstock: 'Pig & Cattle Slurry', vintage: '2026', certified: 'Enagás GTS / ISCC EU', subsidized: 'Unsubsidised', ciScore: '<-60gCO2/MJ', bidPrice: '€ 48.00', offerPrice: '€ 54.00', bidVolume: '20GWh', offerVolume: '30GWh', currency: 'EUR', highlight: true, derivedFrom: 'Enagás GTS / MIBGAS Wholesale Biomethane Bulletin', provenanceTier: 'WEB_INDEX' },
  { id: 'es_2', country: 'ES', class: 'GdO', productClass: 'GO_VOLUNTARY', feedstock: 'Agro-Food Waste', vintage: '2026', certified: 'Enagás GTS', subsidized: 'Subsidised', ciScore: '<25gCO2/MJ', bidPrice: '€ 42.00', offerPrice: '€ 48.00', bidVolume: '10GWh', offerVolume: '25GWh', currency: 'EUR', derivedFrom: 'Real Decreto 376/2022 PNIEC Transport Mandate', provenanceTier: 'WEB_INDEX' },

  // =========================================================================
  // 9. NORDICS & WESTERN EUROPE (SWEDEN, AUSTRIA, FINLAND, BELGIUM)
  // =========================================================================
  { id: 'se_tax', country: 'SE', class: 'TAX_EXEMPT', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Sewage Sludge & Food Waste', vintage: '2026', certified: 'Energimyndigheten', subsidized: 'Unsubsidised', ciScore: '<20gCO2/MJ', bidPrice: '€ 79.00', offerPrice: '€ 85.00', bidVolume: '15GWh', offerVolume: '20GWh', currency: 'EUR', derivedFrom: 'Skatteverket / Lag (1994:1776) State Aid Exemption', provenanceTier: 'STATUTORY_DIRECTIVE' },
  { id: 'at_egg', country: 'AT', class: 'EGG', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agricultural Waste & Crops', vintage: '2026', certified: 'AGCS / ISCC', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 82.00', offerPrice: '€ 88.00', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'AGCS / E-Control Erneuerbaren-Gase-Gesetz Quota', provenanceTier: 'WEB_INDEX' },
  { id: 'fi_trans', country: 'FI', class: 'TRANSPORT', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Municipal Bio-Waste / Manure', vintage: '2026', certified: 'Gasgrid Finland', subsidized: 'Unsubsidised', ciScore: '<25gCO2/MJ', bidPrice: '€ 68.00', offerPrice: '€ 76.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Gasgrid Finland Ex-Domain Distribution Report', provenanceTier: 'WEB_INDEX' },
  { id: 'be_trans', country: 'BE', class: 'TRANSPORT', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agri-Waste & Sewage Sludge', vintage: '2026', certified: 'VREG / SPW', subsidized: 'Unsubsidised', ciScore: '<25gCO2/MJ', bidPrice: '€ 64.00', offerPrice: '€ 72.00', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'VREG Flanders / SPW Wallonia Regional Registry', provenanceTier: 'WEB_INDEX' },

  // =========================================================================
  // 10. CENTRAL & EASTERN EUROPE (POLAND, CZECHIA, SWITZERLAND, NORWAY)
  // =========================================================================
  { id: 'pl_oze', country: 'PL', class: 'OZE', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agri-Food Residues & Beet Pulp', vintage: '2026', certified: 'URE / KZR INiG', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 63.00', offerPrice: '€ 70.00', bidVolume: '15GWh', offerVolume: '25GWh', currency: 'EUR', derivedFrom: 'URE Polish Energy Regulatory Office Feed-In Act (285 PLN eq)', provenanceTier: 'WEB_INDEX' },
  { id: 'cz_poze', country: 'CZ', class: 'POZE', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agri-Waste & Energy Crops', vintage: '2026', certified: 'OTE / ISCC', subsidized: 'Unsubsidised', ciScore: '<35gCO2/MJ', bidPrice: '€ 63.50', offerPrice: '€ 70.50', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'OTE Gas Hub Bulletin / POZE Operational Premium', provenanceTier: 'WEB_INDEX' },
  { id: 'ch_vsg', country: 'CH', class: 'VSG', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Manure & Municipal Green Waste', vintage: '2026', certified: 'Pronovo / VSG', subsidized: 'Unsubsidised', ciScore: '<20gCO2/MJ', bidPrice: '€ 94.00', offerPrice: '€ 102.00', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'Pronovo / VSG Swiss CO2 Law Index (Non-EU Grid)', provenanceTier: 'WEB_INDEX' },
  { id: 'no_bio', country: 'NO', class: 'BIOFUEL', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Fish Sludge & Manure (Bio-LNG)', vintage: '2026', certified: 'Miljødirektoratet', subsidized: 'Unsubsidised', ciScore: '<-40gCO2/MJ', bidPrice: '€ 64.00', offerPrice: '€ 72.00', bidVolume: '10GWh', offerVolume: '20GWh', currency: 'EUR', derivedFrom: 'Miljødirektoratet Road & Maritime Quota Assessment', provenanceTier: 'WEB_INDEX' },

  // =========================================================================
  // 11. BALTIC GRIDS (ESTONIA, LITHUANIA, LATVIA)
  // =========================================================================
  { id: 'ee_trans', country: 'EE', class: 'TRANSPORT', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Cattle Slurry & Sewage', vintage: '2026', certified: 'Elering', subsidized: 'Unsubsidised', ciScore: '<20gCO2/MJ', bidPrice: '€ 60.00', offerPrice: '€ 68.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Elering 100% Municipal Bus Fleet Obligation', provenanceTier: 'WEB_INDEX' },
  { id: 'lt_alt', country: 'LT', class: 'ALT_FUELS', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Waste & Manure', vintage: '2026', certified: 'Amber Grid', subsidized: 'Unsubsidised', ciScore: '<25gCO2/MJ', bidPrice: '€ 58.00', offerPrice: '€ 66.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Amber Grid Alternative Fuels Transport Mandate', provenanceTier: 'WEB_INDEX' },
  { id: 'lv_con', country: 'LV', class: 'STORAGE_GO', productClass: 'GO_VOLUNTARY', feedstock: 'Agro-Industrial Waste', vintage: '2026', certified: 'Conexus', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 55.00', offerPrice: '€ 63.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Conexus Baltic Grid Inčukalns Storage GO', provenanceTier: 'WEB_INDEX' },

  // =========================================================================
  // 12. EMERGING SOUTHERN & CEE (IE, PT, HU, SK, RO, BG, HR, SI, GR)
  // =========================================================================
  { id: 'ie_rho', country: 'IE', class: 'RHO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Grass Silage & Slurry', vintage: '2026', certified: 'GNI', subsidized: 'Unsubsidised', ciScore: '<35gCO2/MJ', bidPrice: '€ 65.00', offerPrice: '€ 72.00', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'Gas Networks Ireland / Cost-Plus Parity Model', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'pt_eego', country: 'PT', class: 'EEGO', productClass: 'GO_VOLUNTARY', feedstock: 'Pig Slurry & Agri-Waste', vintage: '2026', certified: 'REN / EEGO', subsidized: 'Unsubsidised', ciScore: '<25gCO2/MJ', bidPrice: '€ 53.00', offerPrice: '€ 59.00', bidVolume: '10GWh', offerVolume: '15GWh', currency: 'EUR', derivedFrom: 'REN / EEGO Support Model (DL 84/2022)', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'hu_mekh', country: 'HU', class: 'MEKH', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Residues & Maize', vintage: '2026', certified: 'MEKH', subsidized: 'Unsubsidised', ciScore: '<35gCO2/MJ', bidPrice: '€ 59.00', offerPrice: '€ 65.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'FGSZ / MEKH Framework Model', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'sk_okte', country: 'SK', class: 'OKTE', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Biomass', vintage: '2026', certified: 'OKTE', subsidized: 'Unsubsidised', ciScore: '<35gCO2/MJ', bidPrice: '€ 61.00', offerPrice: '€ 67.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'OKTE / SPP-D Injection Model', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'ro_trans', country: 'RO', class: 'TRANSGAZ', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Waste & Straw', vintage: '2026', certified: 'ANRE', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 55.00', offerPrice: '€ 61.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Transgaz Grid Model / ANRE', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'bg_bulg', country: 'BG', class: 'BULGARTRANS', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Residues', vintage: '2026', certified: 'Bulgartransgaz', subsidized: 'Unsubsidised', ciScore: '<35gCO2/MJ', bidPrice: '€ 54.00', offerPrice: '€ 60.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Bulgartransgaz Network Statement Model', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'hr_plin', country: 'HR', class: 'PLINACRO', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Agro-Food Waste', vintage: '2026', certified: 'HROTE', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 58.00', offerPrice: '€ 64.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'HROTE / Plinacro System Model', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'si_borz', country: 'SI', class: 'BORZEN', productClass: 'GO_VOLUNTARY', feedstock: 'Silage & Bio-Waste', vintage: '2026', certified: 'Borzen', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 62.00', offerPrice: '€ 68.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'Borzen / Plinovodi Registry Model', provenanceTier: 'MODELLED_SIMULATED' },
  { id: 'gr_desf', country: 'GR', class: 'DESFA', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Olive Pomace & Slurry', vintage: '2026', certified: 'DESFA / RAE', subsidized: 'Unsubsidised', ciScore: '<25gCO2/MJ', bidPrice: '€ 60.00', offerPrice: '€ 66.00', bidVolume: '10GWh', offerVolume: '10GWh', currency: 'EUR', derivedFrom: 'DESFA Scheme Model / Greek Law 4951', provenanceTier: 'MODELLED_SIMULATED' },

  // =========================================================================
  // 13. PAN-EUROPEAN MARITIME & CARBON (FUELEU & EU ETS)
  // =========================================================================
  { id: 'eu_fueleu', country: 'EU', class: 'FUELEU', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Bio-LNG / Advanced Biomethane', vintage: '2026', certified: 'Thetis-MRV / EU DB', subsidized: 'Unsubsidised', ciScore: '<-50gCO2/MJ', bidPrice: '€ 270.00/t', offerPrice: '€ 300.00/t', bidVolume: '25GWh', offerVolume: '50GWh', currency: 'EUR', derivedFrom: 'Regulation (EU) 2023/1805 Statutory Deficit Penalty', provenanceTier: 'STATUTORY_DIRECTIVE' },
  { id: 'eu_ets1', country: 'EU', class: 'EU_ETS', productClass: 'BUNDLED_COMPLIANCE', feedstock: 'Industrial Natural Gas Displacement', vintage: '2026', certified: 'Union Registry', subsidized: 'Unsubsidised', ciScore: '<30gCO2/MJ', bidPrice: '€ 71.00/t', offerPrice: '€ 74.00/t', bidVolume: '50GWh', offerVolume: '100GWh', currency: 'EUR', derivedFrom: 'EEX EUA Daily Carbon Settlement (~€14.65/MWh avoided)', provenanceTier: 'WEB_INDEX' },
];
