export type BrokerCountry = 'UK' | 'FR' | 'NL' | 'DE' | 'DK' | 'AIB';
export type CertificateClass = 'RGGO' | 'GO';
export type FeedstockLabel = 
  | 'Waste' 
  | 'Crop' 
  | 'Waste/Crop mix (A9a)' 
  | 'Mix' 
  | 'Manure + Physical Gas' 
  | 'Manure/Waste' 
  | 'Manure'
  | 'Waste/Crop';

export type CertificationLabel = 
  | 'Certified (ISCC)' 
  | 'Certified (A9A)' 
  | 'Certified (ETS)' 
  | 'Certified (Non-ETS)' 
  | 'Certified' 
  | 'Uncertified';

export type SubsidyStatus = 'Subsidised' | 'Unsubsidised';

export interface BrokerOrderEntry {
  id: string;
  country: BrokerCountry;
  class: CertificateClass;
  feedstock: FeedstockLabel;
  vintage: string;
  certified: CertificationLabel;
  subsidized: SubsidyStatus;
  ciScore: string;
  ciNumeric: number | null; // e.g. -100, -92, -70, -50, 0, 10, 12, 16, 18, 20, 30
  currency: 'EUR' | 'GBP';
  bidPrice: number | null;
  bidText?: string | null; // e.g. "Buyer", "buyer"
  offerPrice: number | null;
  offerText?: string | null; // e.g. "Seller"
  bidVolumeGWh: number | null;
  bidVolumeText?: string | null;
  offerVolumeGWh: number | null;
  offerVolumeText?: string | null;
  isHighInterest?: boolean; // Highlighted yellow rows from trader sheet
}

/**
 * Baseline real-world European Biomethane Broker Run Dataset
 * Extracted directly from European OTC Broker pricing runs (UK RGGOs and EU GOs)
 */
export const BASELINE_BROKER_RUNS: BrokerOrderEntry[] = [
  // --- UK RGGOs (£/MWh) ---
  {
    id: 'uk-rggo-1',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<18gCO2/MJ',
    ciNumeric: 18,
    currency: 'GBP',
    bidPrice: null,
    offerPrice: 25.00,
    bidVolumeGWh: null,
    offerVolumeGWh: 15,
  },
  {
    id: 'uk-rggo-2',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Crop',
    vintage: '2027',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<30gCO2/MJ',
    ciNumeric: 30,
    currency: 'GBP',
    bidPrice: null,
    offerPrice: 21.20,
    bidVolumeGWh: null,
    offerVolumeGWh: 30,
  },
  {
    id: 'uk-rggo-3',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Crop',
    vintage: '2026',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<20gCO2/MJ',
    ciNumeric: 20,
    currency: 'GBP',
    bidPrice: null,
    offerPrice: 19.00,
    bidVolumeGWh: null,
    offerVolumeGWh: 30,
  },
  {
    id: 'uk-rggo-4',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Waste',
    vintage: '2025',
    certified: 'Certified (A9A)',
    subsidized: 'Subsidised',
    ciScore: '<-20gCO2/MJ',
    ciNumeric: -20,
    currency: 'GBP',
    bidPrice: null,
    offerPrice: 23.65,
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
  },
  {
    id: 'uk-rggo-5',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Crop',
    vintage: '2025',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<10gCO2/MJ',
    ciNumeric: 10,
    currency: 'GBP',
    bidPrice: 16.30,
    offerPrice: null,
    bidVolumeGWh: 10,
    offerVolumeGWh: null,
  },
  {
    id: 'uk-rggo-6',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Waste',
    vintage: '2024',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<20gCO2/MJ',
    ciNumeric: 20,
    currency: 'GBP',
    bidPrice: null,
    offerPrice: 17.20,
    bidVolumeGWh: null,
    offerVolumeGWh: 15,
  },
  {
    id: 'uk-rggo-7',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Waste',
    vintage: 'H224',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<12gCO2/MJ',
    ciNumeric: 12,
    currency: 'GBP',
    bidPrice: null,
    offerPrice: null,
    bidVolumeGWh: null,
    offerVolumeGWh: null,
  },
  {
    id: 'uk-rggo-8',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Crop',
    vintage: '2024',
    certified: 'Certified (ISCC)',
    subsidized: 'Subsidised',
    ciScore: '<10gCO2/MJ',
    ciNumeric: 10,
    currency: 'GBP',
    bidPrice: 15.25,
    offerPrice: 15.90,
    bidVolumeGWh: 10,
    offerVolumeGWh: 15,
  },
  {
    id: 'uk-rggo-9',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Waste',
    vintage: 'H227',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'GBP',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: 20.90,
    bidVolumeGWh: 10,
    offerVolumeGWh: 10,
  },
  {
    id: 'uk-rggo-10',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Crop',
    vintage: '2025',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'GBP',
    bidPrice: 15.90,
    offerPrice: null,
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
  },
  {
    id: 'uk-rggo-11',
    country: 'UK',
    class: 'RGGO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'GBP',
    bidPrice: 17.90,
    offerPrice: null,
    bidVolumeGWh: 10,
    offerVolumeGWh: 10,
  },

  // --- FRANCE GOs (€/MWh) ---
  {
    id: 'fr-go-1',
    country: 'FR',
    class: 'GO',
    feedstock: 'Waste/Crop mix (A9a)',
    vintage: 'H226',
    certified: 'Certified (ETS)',
    subsidized: 'Subsidised',
    ciScore: '<16gCO2/MJ',
    ciNumeric: 16,
    currency: 'EUR',
    bidPrice: 26.50,
    offerPrice: null,
    bidVolumeGWh: 35,
    offerVolumeGWh: null,
  },
  {
    id: 'fr-go-2',
    country: 'FR',
    class: 'GO',
    feedstock: 'Waste',
    vintage: 'H225',
    certified: 'Certified (ETS)',
    subsidized: 'Subsidised',
    ciScore: '<20gCO2/MJ',
    ciNumeric: 20,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: null,
    offerText: 'Seller',
    bidVolumeGWh: null,
    offerVolumeGWh: 20,
  },
  {
    id: 'fr-go-3',
    country: 'FR',
    class: 'GO',
    feedstock: 'Mix',
    vintage: 'H225',
    certified: 'Certified (Non-ETS)',
    subsidized: 'Subsidised',
    ciScore: '<20gCO2/MJ',
    ciNumeric: 20,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: null,
    bidVolumeGWh: null,
    offerVolumeGWh: null,
  },
  {
    id: 'fr-go-4',
    country: 'FR',
    class: 'GO',
    feedstock: 'Mix',
    vintage: '2027',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: null,
    bidVolumeGWh: 10,
    offerVolumeGWh: null,
  },
  {
    id: 'fr-go-5',
    country: 'FR',
    class: 'GO',
    feedstock: 'Mix',
    vintage: '2026',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: 20.50,
    bidVolumeGWh: 20,
    offerVolumeGWh: 10,
  },
  {
    id: 'fr-go-6',
    country: 'FR',
    class: 'GO',
    feedstock: 'Mix',
    vintage: 'H225',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: null,
    bidVolumeGWh: 25,
    offerVolumeGWh: null,
  },

  // --- NETHERLANDS GOs (€/MWh) ---
  {
    id: 'nl-go-1',
    country: 'NL',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<0gCO2/MJ',
    ciNumeric: 0,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: 50.00,
    bidVolumeGWh: 10,
    offerVolumeGWh: 25,
    isHighInterest: true,
  },
  {
    id: 'nl-go-2',
    country: 'NL',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<-17gCO2/MJ',
    ciNumeric: -17,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: 36.00,
    bidVolumeGWh: 10,
    offerVolumeGWh: 10,
    isHighInterest: true,
  },
  {
    id: 'nl-go-3',
    country: 'NL',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<-14gCO2/MJ',
    ciNumeric: -14,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: 34.00,
    bidVolumeGWh: 10,
    offerVolumeGWh: 20,
    isHighInterest: true,
  },
  {
    id: 'nl-go-4',
    country: 'NL',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<0gCO2/MJ',
    ciNumeric: 0,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: 30.00,
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
  },
  {
    id: 'nl-go-5',
    country: 'NL',
    class: 'GO',
    feedstock: 'Waste',
    vintage: 'Q425',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<20gCO2/MJ',
    ciNumeric: 20,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: 30.00,
    bidVolumeGWh: null,
    offerVolumeGWh: 15,
  },

  // --- GERMANY GOs (€/MWh) ---
  {
    id: 'de-go-1',
    country: 'DE',
    class: 'GO',
    feedstock: 'Manure + Physical Gas',
    vintage: 'H226',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '-100gCO2/MJ',
    ciNumeric: -100,
    currency: 'EUR',
    bidPrice: 147.00,
    offerPrice: null,
    offerText: 'Seller',
    bidVolumeGWh: 10,
    offerVolumeGWh: 10,
    isHighInterest: true,
  },
  {
    id: 'de-go-2',
    country: 'DE',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<20gCO2/MJ',
    ciNumeric: 20,
    currency: 'EUR',
    bidPrice: 35.00,
    offerPrice: 44.00,
    bidVolumeGWh: 10,
    offerVolumeGWh: 10,
  },
  {
    id: 'de-go-3',
    country: 'DE',
    class: 'GO',
    feedstock: 'Manure + Physical Gas',
    vintage: 'H127',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<-92gCO2/MJ',
    ciNumeric: -92,
    currency: 'EUR',
    bidPrice: 141.00,
    offerPrice: 148.00,
    bidVolumeGWh: 15,
    offerVolumeGWh: 15,
    isHighInterest: true,
  },

  // --- DENMARK GOs (€/MWh) ---
  {
    id: 'dk-go-1',
    country: 'DK',
    class: 'GO',
    feedstock: 'Manure/Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<-100gCO2/MJ',
    ciNumeric: -100,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: null,
    bidVolumeGWh: 20,
    offerVolumeGWh: null,
  },
  {
    id: 'dk-go-2',
    country: 'DK',
    class: 'GO',
    feedstock: 'Manure/Waste',
    vintage: '2026',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<-50gCO2/MJ',
    ciNumeric: -50,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: null,
    bidVolumeGWh: 30,
    offerVolumeGWh: null,
  },
  {
    id: 'dk-go-3',
    country: 'DK',
    class: 'GO',
    feedstock: 'Manure/Waste',
    vintage: '2027',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<-70gCO2/MJ',
    ciNumeric: -70,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: null,
    offerText: 'Seller',
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
    isHighInterest: true,
  },
  {
    id: 'dk-go-4',
    country: 'DK',
    class: 'GO',
    feedstock: 'Manure/Waste',
    vintage: 'H226',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<-50gCO2/MJ',
    ciNumeric: -50,
    currency: 'EUR',
    bidPrice: 44.00,
    offerPrice: null,
    offerText: 'Seller',
    bidVolumeGWh: 20,
    offerVolumeGWh: 20,
    isHighInterest: true,
  },
  {
    id: 'dk-go-5',
    country: 'DK',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2027',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<20gCO2',
    ciNumeric: 20,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: 37.00,
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
  },
  {
    id: 'dk-go-6',
    country: 'DK',
    class: 'GO',
    feedstock: 'Waste',
    vintage: '2026',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: null,
    offerText: 'Seller',
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
  },
  {
    id: 'dk-go-7',
    country: 'DK',
    class: 'GO',
    feedstock: 'Crop',
    vintage: '2026',
    certified: 'Uncertified',
    subsidized: 'Subsidised',
    ciScore: '—',
    ciNumeric: null,
    currency: 'EUR',
    bidPrice: 22.50,
    offerPrice: null,
    bidVolumeGWh: 10,
    offerVolumeGWh: null,
  },

  // --- PAN-EUROPEAN AIB GOs (€/MWh) ---
  {
    id: 'aib-go-1',
    country: 'AIB',
    class: 'GO',
    feedstock: 'Manure',
    vintage: '2027',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<-100gCO2/MJ',
    ciNumeric: -100,
    currency: 'EUR',
    bidPrice: 126.00,
    offerPrice: null,
    bidVolumeGWh: 15,
    offerVolumeGWh: null,
    isHighInterest: true,
  },
  {
    id: 'aib-go-2',
    country: 'AIB',
    class: 'GO',
    feedstock: 'Manure',
    vintage: '2027/28',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<-100gCO2/MJ',
    ciNumeric: -100,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: 126.00,
    bidVolumeGWh: null,
    offerVolumeGWh: 40,
    offerVolumeText: '30-50GWh',
    isHighInterest: true,
  },
  {
    id: 'aib-go-3',
    country: 'AIB',
    class: 'GO',
    feedstock: 'Waste/Crop',
    vintage: '2027',
    certified: 'Certified',
    subsidized: 'Unsubsidised',
    ciScore: '<-5gCO2/MJ',
    ciNumeric: -5,
    currency: 'EUR',
    bidPrice: null,
    offerPrice: null,
    offerText: 'Seller',
    bidVolumeGWh: null,
    offerVolumeGWh: 10,
  },
  {
    id: 'aib-go-4',
    country: 'AIB',
    class: 'GO',
    feedstock: 'Manure/Waste',
    vintage: 'Q426',
    certified: 'Certified',
    subsidized: 'Subsidised',
    ciScore: '<-25gCO2/MJ',
    ciNumeric: -25,
    currency: 'EUR',
    bidPrice: null,
    bidText: 'Buyer',
    offerPrice: null,
    bidVolumeGWh: 25,
    bidVolumeText: '20-30GWh',
    offerVolumeGWh: null,
  },
];
