import { UnitOfAccount } from './types';

export type ProvenanceTier = 'BROKER_RUN' | 'WEB_INDEX' | 'STATUTORY_DIRECTIVE' | 'MODELLED_SIMULATED';

export interface MarketBenchmarkQuote {
  marketId: string;
  name: string;
  shortName: string;
  country: string;
  countryName: string;
  status: 'ACTIVE' | 'EMERGING' | 'FUTURE';
  deskCategory: 'COMPLIANCE' | 'VOLUNTARY' | 'REGIONAL';
  unitOfAccount: UnitOfAccount;
  unitLabel: string;
  bidPrice: number;
  offerPrice: number;
  midPrice: number;
  currency: 'EUR' | 'GBP';
  provenanceTier: ProvenanceTier;
  sourceName: string;
  sourceUrl?: string;
  observedAt: string;
  provenanceNote: string;
  registry: string;
  annualProductionTWh?: number;
  productionPlants?: number;
  ceilingEurMwh?: number | null;
}

export const EUROPEAN_MARKET_BENCHMARKS: MarketBenchmarkQuote[] = [
  {
    marketId: 'DE_THG',
    name: 'Germany THG Quota (Treibhausgasquote)',
    shortName: 'DE THG',
    country: 'DE',
    countryName: 'Germany',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    bidPrice: 280.00,
    offerPrice: 290.00,
    midPrice: 285.00,
    currency: 'EUR',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'STX / Marex Broker Sheet',
    observedAt: '2026-08-20',
    provenanceNote: 'OTC broker run quotes for 2026/2027 compliance year (38. BImSchV).',
    registry: 'dena Biogasregister / UBA',
    annualProductionTWh: 11.8,
    productionPlants: 242,
  },
  {
    marketId: 'NL_ERE',
    name: 'Netherlands ERE (Emissiereductie-eenheden)',
    shortName: 'NL ERE',
    country: 'NL',
    countryName: 'Netherlands',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_KG_CO2E',
    unitLabel: '€/kgCO₂e',
    bidPrice: 0.330,
    offerPrice: 0.350,
    midPrice: 0.340,
    currency: 'EUR',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'ACT Commodities / STX Run',
    observedAt: '2026-08-19',
    provenanceNote: 'REV / myVertiCer 2026 delivery quote (Wet milieubeheer).',
    registry: 'NEa REV / myVertiCer',
    annualProductionTWh: 3.2,
    productionPlants: 82,
  },
  {
    marketId: 'FR_CPB',
    name: 'France CPB (Certificats de Production de Biogaz)',
    shortName: 'FR CPB',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 76.00,
    offerPrice: 81.00,
    midPrice: 78.50,
    currency: 'EUR',
    provenanceTier: 'STATUTORY_DIRECTIVE',
    sourceName: 'Code de l’énergie Art. L.446-24 / EEX',
    observedAt: '2026-08-18',
    provenanceNote: 'Supplier quota session with statutory ceiling cap of €100.00/MWh.',
    registry: 'EEX',
    ceilingEurMwh: 100.00,
    annualProductionTWh: 10.4,
    productionPlants: 652,
  },
  {
    marketId: 'FR_TIRUERT',
    name: 'France TIRUERT / IRICC (Transport Obligation)',
    shortName: 'FR TIRUERT',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 71.50,
    offerPrice: 76.50,
    midPrice: 74.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'DGDDI Customs Bulletin / Trade Press',
    observedAt: '2026-08-15',
    provenanceNote: 'Customs transport ticket clearing for Annex IX advanced biomethane.',
    registry: 'DGDDI',
    annualProductionTWh: 10.4,
    productionPlants: 652,
  },
  {
    marketId: 'IT_CIC',
    name: 'Italy CIC (Certificati di Immissione in Consumo)',
    shortName: 'IT CIC',
    country: 'IT',
    countryName: 'Italy',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_CIC',
    unitLabel: '€/CIC',
    bidPrice: 338.00,
    offerPrice: 352.00,
    midPrice: 345.00,
    currency: 'EUR',
    provenanceTier: 'STATUTORY_DIRECTIVE',
    sourceName: 'GSE DM 2 March 2018 / GME Index',
    observedAt: '2026-08-16',
    provenanceNote: 'GSE statutory fixed withdrawal value / GME bilateral session (~€29.66/MWh eq).',
    registry: 'GSE',
    annualProductionTWh: 4.8,
    productionPlants: 135,
  },
  {
    marketId: 'UK_RTFO',
    name: 'United Kingdom RTFO (Renewable Transport Fuel Obligation)',
    shortName: 'UK RTFO',
    country: 'GB',
    countryName: 'United Kingdom',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'GBP_PER_RTFC',
    unitLabel: '£/RTFC',
    bidPrice: 0.205,
    offerPrice: 0.225,
    midPrice: 0.215,
    currency: 'GBP',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'Argus Biofuels / Marex Broker Sheet',
    observedAt: '2026-08-20',
    provenanceNote: 'UK RTFO standard renewable transport fuel certificates with double counting (~€38/MWh eq).',
    registry: 'DfT RTFO Registry / GGCS',
    annualProductionTWh: 6.2,
    productionPlants: 124,
  },
  {
    marketId: 'FUELEU',
    name: 'FuelEU Maritime (Regulation EU 2023/1805)',
    shortName: 'FuelEU Maritime',
    country: 'EU',
    countryName: 'European Union',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_TCO2E_DEFICIT',
    unitLabel: '€/tCO₂e',
    bidPrice: 270.00,
    offerPrice: 300.00,
    midPrice: 285.00,
    currency: 'EUR',
    provenanceTier: 'STATUTORY_DIRECTIVE',
    sourceName: 'Regulation (EU) 2023/1805 / Argus Marine',
    observedAt: '2026-08-12',
    provenanceNote: 'Deficit-closure mechanism (€2,400/t VLSFO-eq statutory penalty reference).',
    registry: 'Thetis-MRV / EU Database',
  },
  {
    marketId: 'EU_ETS1',
    name: 'EU ETS Phase 1 Installation Zero-Rating',
    shortName: 'EU ETS1',
    country: 'EU',
    countryName: 'European Union',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    bidPrice: 71.00,
    offerPrice: 74.00,
    midPrice: 72.50,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'EEX EUA Daily Carbon Settlement',
    observedAt: '2026-08-21',
    provenanceNote: 'EEX European Union Allowance (EUA) spot mark (~€14.65/MWh avoided allowance cost).',
    registry: 'Union Registry',
  },
  {
    marketId: 'EU_ETS2',
    name: 'EU ETS2 (Buildings & Road Transport Forward)',
    shortName: 'EU ETS2',
    country: 'EU',
    countryName: 'European Union',
    status: 'FUTURE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    bidPrice: 50.00,
    offerPrice: 60.00,
    midPrice: 55.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'ICIS / Carbon Pulse ETS2 Forward Report',
    observedAt: '2026-08-10',
    provenanceNote: 'Forward curve indication for ETS2 compliance (formally postponed to 2028).',
    registry: 'Union Registry',
  },
  {
    marketId: 'SE_TAX',
    name: 'Sweden Energy & Carbon Tax Exemption',
    shortName: 'SE Tax',
    country: 'SE',
    countryName: 'Sweden',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 79.00,
    offerPrice: 85.00,
    midPrice: 82.00,
    currency: 'EUR',
    provenanceTier: 'STATUTORY_DIRECTIVE',
    sourceName: 'Skatteverket / Lag (1994:1776)',
    observedAt: '2026-08-14',
    provenanceNote: 'Swedish state aid re-approved biomethane energy and CO2 tax exemption value.',
    registry: 'Energimyndigheten',
    annualProductionTWh: 2.1,
    productionPlants: 72,
  },
  {
    marketId: 'AT_EGG',
    name: 'Austria EGG (Erneuerbaren-Gase-Gesetz)',
    shortName: 'AT EGG',
    country: 'AT',
    countryName: 'Austria',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 82.00,
    offerPrice: 88.00,
    midPrice: 85.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'AGCS / E-Control Statement',
    observedAt: '2026-08-15',
    provenanceNote: 'Austrian green gas supplier quota target value (rising to 7.7% by 2030).',
    registry: 'AGCS',
    annualProductionTWh: 0.45,
    productionPlants: 16,
  },
  {
    marketId: 'FI_TRANSPORT',
    name: 'Finland Distribution Obligation',
    shortName: 'FI Transport',
    country: 'FI',
    countryName: 'Finland',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 68.00,
    offerPrice: 76.00,
    midPrice: 72.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Gasgrid Finland Ex-Domain Report',
    observedAt: '2026-08-11',
    provenanceNote: 'Finnish transport distribution mandate cleared via Gasgrid Finland cancellations.',
    registry: 'Gasgrid Finland',
    annualProductionTWh: 0.55,
    productionPlants: 26,
  },
  {
    marketId: 'BE_TRANSPORT',
    name: 'Belgium Transport & Regional Quotas',
    shortName: 'BE Transport',
    country: 'BE',
    countryName: 'Belgium',
    status: 'ACTIVE',
    deskCategory: 'COMPLIANCE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 64.00,
    offerPrice: 72.00,
    midPrice: 68.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'VREG / SPW Regional Registry Report',
    observedAt: '2026-08-12',
    provenanceNote: 'Flanders / Wallonia transport compliance & Port of Antwerp bunkering.',
    registry: 'VREG / SPW',
    annualProductionTWh: 0.38,
    productionPlants: 12,
  },

  {
    marketId: 'AIB_GO',
    name: 'Pan-European AIB EECS Guarantees of Origin',
    shortName: 'AIB EECS GO',
    country: 'EU',
    countryName: 'Pan-European (AIB)',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 23.00,
    offerPrice: 26.00,
    midPrice: 24.50,
    currency: 'EUR',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'STX / AIB Member Indications',
    observedAt: '2026-08-21',
    provenanceNote: 'European Energy Certificate System (EECS) cross-border transferable GO.',
    registry: 'AIB EECS Gas Scheme',
  },
  {
    marketId: 'DE_GO',
    name: 'Germany dena Biogasregister Guarantees of Origin',
    shortName: 'dena GO',
    country: 'DE',
    countryName: 'Germany',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 24.50,
    offerPrice: 27.50,
    midPrice: 26.00,
    currency: 'EUR',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'dena Biogasregister Trading Bulletin',
    observedAt: '2026-08-20',
    provenanceNote: 'dena registered certificates for corporate Scope 1 & heating.',
    registry: 'dena Biogasregister',
  },
  {
    marketId: 'NL_GO',
    name: 'Netherlands VertiCer Guarantees of Origin',
    shortName: 'VertiCer GO',
    country: 'NL',
    countryName: 'Netherlands',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 24.00,
    offerPrice: 27.00,
    midPrice: 25.50,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'VertiCer Market Report / ACT Run',
    observedAt: '2026-08-19',
    provenanceNote: 'Dutch statutory Guarantees of Origin for grid-injected biomethane.',
    registry: 'VertiCer',
  },
  {
    marketId: 'FR_GO',
    name: 'France EEX Biomethane Guarantees of Origin',
    shortName: 'EEX France GO',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 22.00,
    offerPrice: 25.00,
    midPrice: 23.50,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'EEX French State GO Auction Clearing',
    observedAt: '2026-08-18',
    provenanceNote: 'Monthly national auction of subsidised biomethane GOs conducted by EEX.',
    registry: 'EEX Registre National GO',
  },
  {
    marketId: 'UK_RGGO',
    name: 'United Kingdom Renewable Gas Guarantees of Origin',
    shortName: 'UK RGGO',
    country: 'GB',
    countryName: 'United Kingdom',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 21.00,
    offerPrice: 24.00,
    midPrice: 22.50,
    currency: 'GBP',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'Green Gas Certification Scheme (GGCS)',
    observedAt: '2026-08-20',
    provenanceNote: 'GGCS green gas certificates (£19.15/MWh mid converted at 1.17 FX).',
    registry: 'GGCS / REAL',
  },
  {
    marketId: 'DK_GO',
    name: 'Denmark Energinet Wholesale & Export GO',
    shortName: 'DK Export',
    country: 'DK',
    countryName: 'Denmark',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 22.50,
    offerPrice: 25.50,
    midPrice: 24.00,
    currency: 'EUR',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'Energinet / STX Danish Export Sheet',
    observedAt: '2026-08-19',
    provenanceNote: 'Danish transmission grid export GOs.',
    registry: 'Energinet',
    annualProductionTWh: 5.6,
    productionPlants: 64,
  },
  {
    marketId: 'VOL_SCOPE1',
    name: 'Voluntary Corporate Scope 1 / GHG Protocol Claim',
    shortName: 'Voluntary Scope 1',
    country: 'EU',
    countryName: 'Pan-European / Global',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 22.00,
    offerPrice: 26.00,
    midPrice: 24.00,
    currency: 'EUR',
    provenanceTier: 'BROKER_RUN',
    sourceName: 'Corporate ESG Broker Composite Index',
    observedAt: '2026-08-20',
    provenanceNote: 'Book-and-Claim corporate voluntary decarbonization certificate premium.',
    registry: 'National & Voluntary Registries',
  },
  {
    marketId: 'VOL_EU_ETS',
    name: 'EU ETS Industrial Scope 1 Zero-Rating (Avoided EUAs)',
    shortName: 'EU ETS Scope 1',
    country: 'EU',
    countryName: 'Pan-European (EU ETS)',
    status: 'ACTIVE',
    deskCategory: 'VOLUNTARY',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    bidPrice: 71.00,
    offerPrice: 74.00,
    midPrice: 72.50,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'EEX EUA Daily Carbon Settlement',
    observedAt: '2026-08-21',
    provenanceNote: 'Industrial fuel switching zero-rating under MRR rules (0.202 tCO2e/MWh natural gas).',
    registry: 'Union Registry',
  },

  {
    marketId: 'ES_GDO',
    name: 'Spain Enagás GdO & PNIEC Mandate',
    shortName: 'ES GdO',
    country: 'ES',
    countryName: 'Spain',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 45.00,
    offerPrice: 51.00,
    midPrice: 48.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Enagás GTS / MIBGAS Bulletin',
    observedAt: '2026-08-16',
    provenanceNote: 'Spanish wholesale grid injection indication (Real Decreto 376/2022).',
    registry: 'Enagás GTS',
    annualProductionTWh: 0.85,
    productionPlants: 24,
  },
  {
    marketId: 'PL_OZE',
    name: 'Poland OZE Support & Injection Act',
    shortName: 'PL OZE',
    country: 'PL',
    countryName: 'Poland',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 63.00,
    offerPrice: 70.00,
    midPrice: 66.50,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'URE Polish Energy Regulatory Office',
    observedAt: '2026-08-15',
    provenanceNote: 'Polish RES Act direct injection reference price (285 PLN/MWh equivalent).',
    registry: 'URE / KZR INiG',
    annualProductionTWh: 0.32,
    productionPlants: 8,
  },
  {
    marketId: 'CZ_POZE',
    name: 'Czech Republic POZE & OTE Registry',
    shortName: 'CZ POZE',
    country: 'CZ',
    countryName: 'Czech Republic',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 63.50,
    offerPrice: 70.50,
    midPrice: 67.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'OTE Gas Hub Bulletin / Zákon č. 165/2012',
    observedAt: '2026-08-14',
    provenanceNote: 'Czech POZE operational feed-in premium and OTE registry.',
    registry: 'OTE',
    annualProductionTWh: 0.42,
    productionPlants: 11,
  },
  {
    marketId: 'EE_TRANSPORT',
    name: 'Estonia Elering 100% Bus Obligation',
    shortName: 'EE Transport',
    country: 'EE',
    countryName: 'Estonia',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 60.00,
    offerPrice: 68.00,
    midPrice: 64.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Elering Green Gas Assessment',
    observedAt: '2026-08-12',
    provenanceNote: '100% municipal bus fleet mandate cleared via Elering registry.',
    registry: 'Elering',
    annualProductionTWh: 0.28,
    productionPlants: 7,
  },
  {
    marketId: 'LT_ALT_FUELS',
    name: 'Lithuania Amber Grid Transport Mandate',
    shortName: 'LT AmberGrid',
    country: 'LT',
    countryName: 'Lithuania',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 58.00,
    offerPrice: 66.00,
    midPrice: 62.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Amber Grid Alternative Fuels Statement',
    observedAt: '2026-08-13',
    provenanceNote: 'Lithuanian Alternative Fuels Law transport obligation.',
    registry: 'Amber Grid',
    annualProductionTWh: 0.22,
    productionPlants: 6,
  },
  {
    marketId: 'LV_CONEXUS',
    name: 'Latvia Conexus Baltic Registry',
    shortName: 'LV Conexus',
    country: 'LV',
    countryName: 'Latvia',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 55.00,
    offerPrice: 63.00,
    midPrice: 59.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Conexus Baltic Grid Market Assessment',
    observedAt: '2026-08-11',
    provenanceNote: 'Regional gas storage hub (Inčukalns UGS) renewable gas certificate.',
    registry: 'Conexus Baltic Grid',
    annualProductionTWh: 0.15,
    productionPlants: 4,
  },
  {
    marketId: 'CH_VSG',
    name: 'Switzerland Pronovo / VSG (Non-EU Grid)',
    shortName: 'CH VSG',
    country: 'CH',
    countryName: 'Switzerland',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 94.00,
    offerPrice: 102.00,
    midPrice: 98.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Pronovo / VSG Clearing Bulletin',
    observedAt: '2026-08-16',
    provenanceNote: 'Swiss domestic CO2 law compliance (ineligible for EU UDB mass balance).',
    registry: 'Pronovo / VSG',
    annualProductionTWh: 0.52,
    productionPlants: 41,
  },
  {
    marketId: 'NO_STATNETT',
    name: 'Norway Biofuel Quota (Non-EU / EEA)',
    shortName: 'NO Quota',
    country: 'NO',
    countryName: 'Norway',
    status: 'ACTIVE',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 64.00,
    offerPrice: 72.00,
    midPrice: 68.00,
    currency: 'EUR',
    provenanceTier: 'WEB_INDEX',
    sourceName: 'Miljødirektoratet Quota Assessment',
    observedAt: '2026-08-14',
    provenanceNote: 'Domestic transport quota for heavy transport and maritime Bio-LNG.',
    registry: 'Miljødirektoratet',
    annualProductionTWh: 0.40,
    productionPlants: 10,
  },

  {
    marketId: 'IE_RHO',
    name: 'Ireland Renewable Heat Obligation',
    shortName: 'IE RHO',
    country: 'IE',
    countryName: 'Ireland',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 65.00,
    offerPrice: 72.00,
    midPrice: 68.50,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'Gas Networks Ireland / Modelled Cost-Plus',
    observedAt: '2026-08-10',
    provenanceNote: 'Simulated Irish import parity based on UK/DK wheeling + RHO target.',
    registry: 'Gas Networks Ireland (GNI)',
    annualProductionTWh: 0.18,
    productionPlants: 5,
  },
  {
    marketId: 'PT_EEGO',
    name: 'Portugal EEGO / REN Market',
    shortName: 'PT EEGO',
    country: 'PT',
    countryName: 'Portugal',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 53.00,
    offerPrice: 59.00,
    midPrice: 56.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'REN / EEGO Support Model',
    observedAt: '2026-08-10',
    provenanceNote: 'Modelled Iberian feed-in economics under Decreto-Lei n.º 84/2022.',
    registry: 'REN / EEGO',
    annualProductionTWh: 0.14,
    productionPlants: 4,
  },
  {
    marketId: 'HU_MEKH',
    name: 'Hungary MEKH Green Gas Framework',
    shortName: 'HU MEKH',
    country: 'HU',
    countryName: 'Hungary',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 59.00,
    offerPrice: 65.00,
    midPrice: 62.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'FGSZ / MEKH Framework Model',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled CEE agricultural upgrading economics.',
    registry: 'MEKH',
    annualProductionTWh: 0.16,
    productionPlants: 5,
  },
  {
    marketId: 'SK_OKTE',
    name: 'Slovakia OKTE / SPP-D Support',
    shortName: 'SK OKTE',
    country: 'SK',
    countryName: 'Slovakia',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 61.00,
    offerPrice: 67.00,
    midPrice: 64.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'OKTE / SPP-D Injection Model',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled Slovak agricultural biomethane production economics.',
    registry: 'OKTE',
    annualProductionTWh: 0.12,
    productionPlants: 4,
  },
  {
    marketId: 'RO_TRANSGAZ',
    name: 'Romania Transgaz Emerging Pool',
    shortName: 'RO Transgaz',
    country: 'RO',
    countryName: 'Romania',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 55.00,
    offerPrice: 61.00,
    midPrice: 58.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'Transgaz Grid Model / ANRE',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled Romanian agro-biomass grid injection economics.',
    registry: 'ANRE / Transgaz',
    annualProductionTWh: 0.09,
    productionPlants: 3,
  },
  {
    marketId: 'BG_BULGARTRANSGAZ',
    name: 'Bulgaria Bulgartransgaz Framework',
    shortName: 'BG Market',
    country: 'BG',
    countryName: 'Bulgaria',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 54.00,
    offerPrice: 60.00,
    midPrice: 57.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'Bulgartransgaz Network Statement',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled Bulgarian renewable gas injection estimate.',
    registry: 'Bulgartransgaz',
    annualProductionTWh: 0.06,
    productionPlants: 2,
  },
  {
    marketId: 'HR_PLINACRO',
    name: 'Croatia Plinacro / HROTE System',
    shortName: 'HR Plinacro',
    country: 'HR',
    countryName: 'Croatia',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 58.00,
    offerPrice: 64.00,
    midPrice: 61.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'HROTE / Plinacro System Model',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled Croatian HROTE green gas tariff estimate.',
    registry: 'HROTE / Plinacro',
    annualProductionTWh: 0.08,
    productionPlants: 3,
  },
  {
    marketId: 'SI_PLINOVODI',
    name: 'Slovenia Plinovodi / Borzen System',
    shortName: 'SI Borzen',
    country: 'SI',
    countryName: 'Slovenia',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 62.00,
    offerPrice: 68.00,
    midPrice: 65.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'Borzen / Plinovodi Registry Model',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled Slovenian Borzen GO support estimate.',
    registry: 'Borzen / Plinovodi',
    annualProductionTWh: 0.05,
    productionPlants: 2,
  },
  {
    marketId: 'GR_DESFA',
    name: 'Greece DESFA Biomethane Scheme',
    shortName: 'GR DESFA',
    country: 'GR',
    countryName: 'Greece',
    status: 'EMERGING',
    deskCategory: 'REGIONAL',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    bidPrice: 60.00,
    offerPrice: 66.00,
    midPrice: 63.00,
    currency: 'EUR',
    provenanceTier: 'MODELLED_SIMULATED',
    sourceName: 'DESFA Scheme Model / Law 4951',
    observedAt: '2026-08-08',
    provenanceNote: 'Modelled Greek DESFA biomethane licensing scheme estimate.',
    registry: 'DESFA / RAE',
    annualProductionTWh: 0.05,
    productionPlants: 2,
  },
];

export function getBenchmarkForMarket(marketId: string): MarketBenchmarkQuote | undefined {
  return EUROPEAN_MARKET_BENCHMARKS.find(b => b.marketId === marketId);
}
