import { Market, Uncertainty } from './types';

const deDoubleCounting: Uncertainty = {
  id: 'DE_DOUBLE_COUNTING',
  title: 'Double counting of advanced biofuels',
  description: 'Double counting eliminated from 2026 compliance year (Cabinet draft, 10 December 2025). Whether biomethane specifically retains double counting is unresolved.',
  branches: [
    { id: 'DC_OFF', label: 'Without double counting', description: 'Single counting only (1×)', multiplier: 1 },
    { id: 'DC_ON', label: 'With double counting', description: 'Advanced biofuel double counting retained for biomethane (2×)', multiplier: 2 },
  ],
  persistentNote: 'IMPORTANT DISTINCTION: Double counting is a POLICY MULTIPLIER — it is being removed. Manure\'s negative carbon intensity is a property of the GHG CALCULATION (avoided methane emissions from conventional manure management) — it is unaffected by changes to double counting.',
  source: '§37a BImSchG, 38. BImSchV; Cabinet draft 10 December 2025',
  lastUpdated: '2026-08-16',
};

export const MARKETS: Market[] = [
  // ACTIVE
  {
    id: 'DE_THG',
    name: 'Germany THG Quota',
    shortName: 'DE THG',
    country: 'DE',
    countryName: 'Germany',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    notes: 'Has uncertainty for double counting (model both branches).',
    legalBasis: '§37a BImSchG, 38. BImSchV',
    registry: 'UBA',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [deDoubleCounting],
  },
  {
    id: 'NL_ERE',
    name: 'Netherlands ERE',
    shortName: 'NL ERE',
    country: 'NL',
    countryName: 'Netherlands',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_KG_CO2E',
    unitLabel: '€/kgCO₂e',
    notes: 'Replaced HBE. 1 ERE = 1 kg CO2e avoided.',
    legalBasis: 'Wet milieubeheer, Regeling energie vervoer',
    registry: 'NEa REV',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'FR_CPB',
    name: 'France CPB',
    shortName: 'FR CPB',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Live 1 Jan 2026. Binds suppliers >400 GWh/yr in 2026.',
    legalBasis: 'Code de l\'énergie, Art. L.446-24 et seq.',
    registry: 'EEX',
    ceilingEurMwh: 100,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'FR_TIRUERT',
    name: 'France TIRUERT',
    shortName: 'FR TIRUERT',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Transitioning to GHG-based IRICC in 2027. Treat as contested.',
    legalBasis: 'Code des douanes',
    registry: null,
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'IT_CIC',
    name: 'Italy CIC',
    shortName: 'IT CIC',
    country: 'IT',
    countryName: 'Italy',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_CIC',
    unitLabel: '€/CIC',
    notes: '1 CIC = 10 Gcal conventional / 5 Gcal advanced. SNAM injection rules.',
    legalBasis: 'DM 2 March 2018',
    registry: 'GSE',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'AT_EGG',
    name: 'Austria EGG',
    shortName: 'AT EGG',
    country: 'AT',
    countryName: 'Austria',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Green gas supplier quota rising to 7.7% by 2030.',
    legalBasis: 'Erneuerbaren-Gase-Gesetz',
    registry: 'AGCS',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'SE_TAX',
    name: 'Sweden Tax Exemption',
    shortName: 'SE Tax',
    country: 'SE',
    countryName: 'Sweden',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Value = tax avoided. Annulled by EU courts, re-approved by Commission.',
    legalBasis: 'Swedish Energy Tax Act',
    registry: null,
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'FI_TRANSPORT',
    name: 'Finland Transport Obligation',
    shortName: 'FI Transport',
    country: 'FI',
    countryName: 'Finland',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Via ex-domain cancellation. Gasgrid publishes instructions.',
    legalBasis: 'Distribution Obligation Act',
    registry: 'Gasgrid',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'BE_TRANSPORT',
    name: 'Belgium Transport Blending',
    shortName: 'BE Transport',
    country: 'BE',
    countryName: 'Belgium',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Dual-region SPW/VREG. Antwerp bunkering adjacency.',
    legalBasis: 'Regional Decrees',
    registry: 'SPW/VREG',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'DK_GO',
    name: 'Denmark GO / Export',
    shortName: 'DK GO',
    country: 'DK',
    countryName: 'Denmark',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Structurally long, export-driven. Northern European wholesale benchmark.',
    legalBasis: 'Danish Energy Act',
    registry: 'Energinet',
    ceilingEurMwh: null,
    requiresMassBalance: false, // GO specific
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'FUELEU',
    name: 'FuelEU Maritime',
    shortName: 'FuelEU',
    country: 'EU',
    countryName: 'European Union',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_TCO2E_DEFICIT',
    unitLabel: '€/tCO₂e',
    notes: 'Penalty €2400/t VLSFO-eq. NOT capped at €210/MWh. Escalates 10%/20%/30%.',
    legalBasis: 'Regulation (EU) 2023/1805',
    registry: null,
    ceilingEurMwh: null, // Effectively higher
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: true,
    uncertainties: [],
  },
  {
    id: 'EU_ETS1',
    name: 'EU ETS Phase 1',
    shortName: 'ETS1',
    country: 'EU',
    countryName: 'European Union',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    notes: 'Installation-level zero rating. Requires RED compliance and actual combustion.',
    legalBasis: 'Directive 2003/87/EC',
    registry: 'Union Registry',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: true,
    uncertainties: [],
  },
  {
    id: 'UK_RTFO',
    name: 'UK RTFO',
    shortName: 'UK RTFO',
    country: 'UK',
    countryName: 'United Kingdom',
    status: 'ACTIVE',
    unitOfAccount: 'GBP_PER_DRTFC',
    unitLabel: '£/dRTFC',
    notes: 'Non-EU, requires FX conversion.',
    legalBasis: 'Renewable Transport Fuel Obligations Order 2007',
    registry: 'DfT RTFO Registry',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'VOL_SCOPE1',
    name: 'Voluntary Scope 1',
    shortName: 'Voluntary Scope 1',
    country: 'EU',
    countryName: 'Global',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Most permissive — accepts book-and-claim. GHG Protocol market-based.',
    legalBasis: 'GHG Protocol',
    registry: null,
    ceilingEurMwh: null,
    requiresMassBalance: false,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
  
  // FUTURE
  {
    id: 'EU_ETS2',
    name: 'EU ETS2',
    shortName: 'ETS2',
    country: 'EU',
    countryName: 'European Union',
    status: 'FUTURE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    notes: 'Buildings and road transport. POSTPONED TO 2028.',
    legalBasis: 'Directive (EU) 2023/959',
    registry: 'Union Registry',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: true,
    uncertainties: [],
  },

  // EMERGING
  ...['ES', 'IE', 'PL', 'PT', 'CZ', 'SK', 'HU', 'RO', 'BG', 'HR', 'SI', 'GR', 'LT', 'LV', 'EE', 'CH', 'NO'].map(country => ({
    id: `${country}_EMERGING`,
    name: `${country} Emerging Market`,
    shortName: country,
    country,
    countryName: country,
    status: 'EMERGING' as const,
    unitOfAccount: 'EUR_PER_MWH' as const,
    unitLabel: '€/MWh',
    notes: 'Demand nascent / Timing slipped / Specifics TBD.',
    legalBasis: 'Various',
    registry: null,
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  })),

  // NONE
  ...['CY', 'MT', 'LU', 'UA'].map(country => ({
    id: `${country}_NONE`,
    name: `${country} No Market`,
    shortName: country,
    country,
    countryName: country,
    status: 'NONE' as const,
    unitOfAccount: 'EUR_PER_MWH' as const,
    unitLabel: '-',
    notes: 'No domestic production / Off-grid island.',
    legalBasis: 'N/A',
    registry: null,
    ceilingEurMwh: null,
    requiresMassBalance: false,
    requiresUDB: false,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
  }))
];

export function getMarketById(id: string): Market | undefined {
  return MARKETS.find(m => m.id === id);
}
