import { Market, Uncertainty } from './types';

const deDoubleCounting: Uncertainty = {
  id: 'DE_DOUBLE_COUNTING',
  title: 'Double counting of advanced biofuels in Germany',
  description: 'Double counting eliminated from 2026 compliance year (Cabinet draft, 10 December 2025). Whether biomethane specifically retains double counting remains unresolved.',
  branches: [
    { id: 'DC_OFF', label: 'Without double counting (1×)', description: 'Single counting only (1× multiplier)', multiplier: 1 },
    { id: 'DC_ON', label: 'With double counting (2×)', description: 'Double counting multiplier retained for biomethane (2×)', multiplier: 2 },
  ],
  persistentNote: 'IMPORTANT DISTINCTION: Double counting is a POLICY MULTIPLIER — it is being removed. Manure\'s negative carbon intensity is a property of the GHG CALCULATION (avoided methane emissions from conventional manure management) — it is unaffected by changes to double counting.',
  source: '§37a BImSchG, 38. BImSchV; Cabinet draft 10 December 2025',
  lastUpdated: '2026-08-16',
};

export const MARKETS: Market[] = [
  // -------------------------------------------------------------
  // 1. ACTIVE TIER-1 COMPLIANCE MARKETS (Primary Trading Pools)
  // -------------------------------------------------------------
  {
    id: 'DE_THG',
    name: 'Germany THG Quota',
    shortName: 'DE THG',
    country: 'DE',
    countryName: 'Germany',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    notes: 'Largest compliance market in Europe. ~240 plants, ~11.5 TWh/yr. Double counting status unresolved for 2026.',
    legalBasis: '§37a BImSchG, 38. BImSchV',
    registry: 'dena Biogasregister / UBA',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [deDoubleCounting],
    productionPlants: 242,
    annualProductionTWh: 11.8,
    keyFeedstocks: 'Manure, energy crops, agricultural residues, bio-waste',
    gridInterconnection: 'THE (Trading Hub Europe) interconnected grid. Full UDB & ERGaR compatibility.',
  },
  {
    id: 'NL_ERE',
    name: 'Netherlands ERE',
    shortName: 'NL ERE',
    country: 'NL',
    countryName: 'Netherlands',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_KG_CO2E',
    unitLabel: '€/kgCO₂e',
    notes: 'Replaced HBE from 1 Jan 2026. 1 ERE = 1 kg CO₂e avoided. Structurally advantages low-CI molecules. No multipliers.',
    legalBasis: 'Wet milieubeheer, Regeling energie vervoer',
    registry: 'NEa REV / myVertiCer',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 82,
    annualProductionTWh: 3.2,
    keyFeedstocks: 'Manure, co-substrates, industrial bio-waste, sewage sludge',
    gridInterconnection: 'TTF hub grid. VertiCer registry integrated with UDB single mass balance area.',
  },
  {
    id: 'FR_CPB',
    name: 'France CPB (Certificats de Production de Biogaz)',
    shortName: 'FR CPB',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'In force 1 Jan 2026. Binds natural gas suppliers >400 GWh/yr in 2026 (falling to 0 by yr 5). Hard penalty cap: €100/MWh.',
    legalBasis: 'Code de l\'énergie, Art. L.446-24 et seq.',
    registry: 'EEX',
    ceilingEurMwh: 100,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 652,
    annualProductionTWh: 10.4,
    keyFeedstocks: 'Agricultural waste, intermediate crops (CIVE), sewage, food waste',
    gridInterconnection: 'GRDF / GRTgaz / Teréga interconnected grid. Registry managed by EEX.',
  },
  {
    id: 'FR_TIRUERT',
    name: 'France TIRUERT / IRICC',
    shortName: 'FR TIRUERT',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Transport ticket obligation transitioning to GHG-based IRICC in 2027.',
    legalBasis: 'Code des douanes, Art. 266 quindecies',
    registry: 'DGDDI',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 652,
    annualProductionTWh: 10.4,
    keyFeedstocks: 'Annex IX-A waste & advanced agricultural residues',
    gridInterconnection: 'French interconnected gas grid.',
  },
  {
    id: 'IT_CIC',
    name: 'Italy CIC (Certificati di Immissione in Consumo)',
    shortName: 'IT CIC',
    country: 'IT',
    countryName: 'Italy',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_CIC',
    unitLabel: '€/CIC',
    notes: '1 CIC = 10 Gcal conventional (11.63 MWh) / 5 Gcal advanced (5.815 MWh) under DM 2 March 2018 / PNRR rules.',
    legalBasis: 'DM 2 March 2018 & DM 15 Sept 2022',
    registry: 'GSE',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 135,
    annualProductionTWh: 4.8,
    keyFeedstocks: 'Manure, agro-industrial residues, sewage sludge',
    gridInterconnection: 'SNAM Rete Gas grid injection. GSE certification registry.',
  },
  {
    id: 'DK_GO',
    name: 'Denmark Energinet Wholesale & Export',
    shortName: 'DK Export',
    country: 'DK',
    countryName: 'Denmark',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Highest biomethane grid share in Europe (>35%). Heavy structural exporter to Germany and Sweden.',
    legalBasis: 'Lov om fremme af vedvarende energi (VE-loven)',
    registry: 'Energinet',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 64,
    annualProductionTWh: 5.6,
    keyFeedstocks: 'Manure & slurry, straw, industrial organic waste',
    gridInterconnection: 'Energinet transmission grid interconnected with Germany (Ellund) and Sweden (Dragør).',
  },
  {
    id: 'AT_EGG',
    name: 'Austria EGG (Erneuerbaren-Gase-Gesetz)',
    shortName: 'AT EGG',
    country: 'AT',
    countryName: 'Austria',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Green gas supplier quota rising to 7.7% by 2030 (~7.5 TWh/yr). OMV anchor buyer.',
    legalBasis: 'Erneuerbaren-Gase-Gesetz (EGG)',
    registry: 'AGCS',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 16,
    annualProductionTWh: 0.45,
    keyFeedstocks: 'Agricultural waste, energy crops, food waste',
    gridInterconnection: 'Austrian Gas Grid (TAG/WAG) with AGCS registry.',
  },
  {
    id: 'SE_TAX',
    name: 'Sweden Energy & Carbon Tax Exemption',
    shortName: 'SE Tax',
    country: 'SE',
    countryName: 'Sweden',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Full tax exemption re-approved by European Commission State Aid decision. Major market for Danish exports.',
    legalBasis: 'Lag (1994:1776) om skatt på energi',
    registry: 'Energimyndigheten',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 72,
    annualProductionTWh: 2.1,
    keyFeedstocks: 'Sewage sludge, municipal solid waste, food waste, manure',
    gridInterconnection: 'Swedegas western grid + off-grid bio-CNG/LNG virtual pipelines.',
  },
  {
    id: 'FI_TRANSPORT',
    name: 'Finland Distribution Obligation',
    shortName: 'FI Transport',
    country: 'FI',
    countryName: 'Finland',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Transport distribution mandate cleared via Gasgrid Finland Ex-Domain cancellations.',
    legalBasis: 'Laki uusiutuvien polttoaineiden käytön edistämisestä liikenteessä (446/2007)',
    registry: 'Gasgrid Finland',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 26,
    annualProductionTWh: 0.55,
    keyFeedstocks: 'Municipal bio-waste, manure, industrial wastewater, e-methane',
    gridInterconnection: 'Gasgrid Finland transmission grid + Balticconnector to Estonia.',
  },
  {
    id: 'BE_TRANSPORT',
    name: 'Belgium Transport & Regional Quotas',
    shortName: 'BE Transport',
    country: 'BE',
    countryName: 'Belgium',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Dual regional registries (VREG in Flanders, SPW in Wallonia). Key bunkering gateway at Port of Antwerp.',
    legalBasis: 'Flamisch Energiedecreet & Décret wallon gaz',
    registry: 'VREG / SPW',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 12,
    annualProductionTWh: 0.38,
    keyFeedstocks: 'Agricultural waste, sewage, municipal bio-waste',
    gridInterconnection: 'Fluxys transmission grid.',
  },
  {
    id: 'ES_GDO',
    name: 'Spain Enagás GdO & PNIEC Mandate',
    shortName: 'ES GdO',
    country: 'ES',
    countryName: 'Spain',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Widest origination spread in Europe. Enagás GdO operational since 2023. Rapidly scaling 200+ project pipeline.',
    legalBasis: 'Real Decreto 376/2022',
    registry: 'Enagás GTS',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 18,
    annualProductionTWh: 0.85,
    keyFeedstocks: 'Pig and cattle slurry, agro-food residues, sewage',
    gridInterconnection: 'Enagás / Nedgia gas transmission grid + Ex-domain export capability.',
  },
  {
    id: 'PL_OZE',
    name: 'Poland OZE Support & Injection Act',
    shortName: 'PL OZE',
    country: 'PL',
    countryName: 'Poland',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'RES Act amendment enables direct injection & feed-in tariffs up to 1 MW. Largest biomass potential in CEE.',
    legalBasis: 'Ustawa o odnawialnych źródłach energii',
    registry: 'URE / KZR INiG',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 8,
    annualProductionTWh: 0.32,
    keyFeedstocks: 'Agri-food waste, sugar beet pulp, distilleries, manure',
    gridInterconnection: 'Gaz-System / PSG gas distribution networks.',
  },
  {
    id: 'CZ_POZE',
    name: 'Czech Republic POZE & OTE Registry',
    shortName: 'CZ POZE',
    country: 'CZ',
    countryName: 'Czech Republic',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Operational feed-in premium for biomethane grid injection. OTE green gas registry.',
    legalBasis: 'Zákon č. 165/2012 Sb. (POZE)',
    registry: 'OTE',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 11,
    annualProductionTWh: 0.42,
    keyFeedstocks: 'Agricultural waste, energy crops, sewage',
    gridInterconnection: 'GasNet / NET4GAS interconnected grid.',
  },
  {
    id: 'EE_TRANSPORT',
    name: 'Estonia Elering 100% Bus Obligation',
    shortName: 'EE Transport',
    country: 'EE',
    countryName: 'Estonia',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: '100% of municipal bus fleets run on domestic biomethane. Elering green gas registry.',
    legalBasis: 'Vedelkütuse seadus',
    registry: 'Elering',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 7,
    annualProductionTWh: 0.28,
    keyFeedstocks: 'Cattle slurry, sewage sludge, bio-waste',
    gridInterconnection: 'Elering gas transmission system.',
  },
  {
    id: 'LT_ALT_FUELS',
    name: 'Lithuania Amber Grid Transport Mandate',
    shortName: 'LT AmberGrid',
    country: 'LT',
    countryName: 'Lithuania',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Alternative Fuels Law transport obligations. Amber Grid GO registry.',
    legalBasis: 'Alternatyviųjų degalų įstatymas',
    registry: 'Amber Grid',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 6,
    annualProductionTWh: 0.22,
    keyFeedstocks: 'Agricultural residues, manure, sewage',
    gridInterconnection: 'Amber Grid (GIPL interconnector with Poland).',
  },
  {
    id: 'LV_CONEXUS',
    name: 'Latvia Conexus Baltic Registry',
    shortName: 'LV Conexus',
    country: 'LV',
    countryName: 'Latvia',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Regional gas storage hub (Inčukalns UGS). Conexus Baltic Grid GO registry.',
    legalBasis: 'Enerģētikas likums',
    registry: 'Conexus Baltic Grid',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 4,
    annualProductionTWh: 0.15,
    keyFeedstocks: 'Agricultural waste, energy crops',
    gridInterconnection: 'Conexus Baltic Grid pipeline system.',
  },
  {
    id: 'CH_VSG',
    name: 'Switzerland Pronovo / VSG (Non-EU Grid)',
    shortName: 'CH VSG',
    country: 'CH',
    countryName: 'Switzerland',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Non-EU market. Biomethane injected into Swiss grid CANNOT clear EU compliance via UDB. Must be used domestically or exported physically.',
    legalBasis: 'CO2-Gesetz (SR 641.71)',
    registry: 'Pronovo / VSG',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 41,
    annualProductionTWh: 0.52,
    keyFeedstocks: 'Sewage sludge, municipal organic waste, manure',
    gridInterconnection: 'Swissgas / Transitgas (Non-EU regulatory boundary).',
  },
  {
    id: 'NO_STATNETT',
    name: 'Norway Biofuel Quota (Non-EU / EEA)',
    shortName: 'NO Quota',
    country: 'NO',
    countryName: 'Norway',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Domestic transport quota. Bio-LNG heavy transport focus.',
    legalBasis: 'Produktforskriften Kap 3',
    registry: 'Miljødirektoratet',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 10,
    annualProductionTWh: 0.40,
    keyFeedstocks: 'Fish waste & silage, food waste, sewage',
    gridInterconnection: 'Gassco offshore system + off-grid bio-LNG bunkering.',
  },
  {
    id: 'UK_RTFO',
    name: 'United Kingdom RTFO',
    shortName: 'UK RTFO',
    country: 'GB',
    countryName: 'United Kingdom',
    status: 'ACTIVE',
    unitOfAccount: 'GBP_PER_DRTFC',
    unitLabel: '£/dRTFC',
    notes: 'Non-EU grid. 120+ plants. Biomethane injected in UK grid CANNOT clear EU UDB. Highly lucrative domestic RTFO market.',
    legalBasis: 'Renewable Transport Fuel Obligations Order 2007',
    registry: 'DfT RTFO Registry / GGCS',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 124,
    annualProductionTWh: 6.8,
    keyFeedstocks: 'Food waste, manure, energy crops, sewage',
    gridInterconnection: 'National Grid Gas (Non-EU regulatory boundary).',
  },

  // -------------------------------------------------------------
  // 2. EMERGING & DEVELOPING PRODUCING MARKETS
  // -------------------------------------------------------------
  {
    id: 'IE_RHO',
    name: 'Ireland Renewable Heat Obligation',
    shortName: 'IE RHO',
    country: 'IE',
    countryName: 'Ireland',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Renewable Heat Obligation turning Ireland into net importer. Major 5.7 TWh 2030 target under Climate Action Plan.',
    legalBasis: 'Renewable Heat Obligation Scheme',
    registry: 'Gas Networks Ireland (GNI)',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 5,
    annualProductionTWh: 0.18,
    keyFeedstocks: 'Cattle slurry, grass silage, food waste',
    gridInterconnection: 'Gas Networks Ireland grid.',
  },
  {
    id: 'PT_EEGO',
    name: 'Portugal EEGO / REN Market',
    shortName: 'PT EEGO',
    country: 'PT',
    countryName: 'Portugal',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Decree-Law 84/2022 framework. First grid-injected plants commissioned.',
    legalBasis: 'Decreto-Lei n.º 84/2022',
    registry: 'REN / EEGO',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 4,
    annualProductionTWh: 0.14,
    keyFeedstocks: 'Urban waste, livestock slurry, agro-food',
    gridInterconnection: 'REN gas transmission grid.',
  },
  {
    id: 'HU_MEKH',
    name: 'Hungary MEKH Green Gas Framework',
    shortName: 'HU MEKH',
    country: 'HU',
    countryName: 'Hungary',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Support framework in preparation. Interconnected grid with FGSZ.',
    legalBasis: '2008. évi XL. törvény (Földgáztörvény)',
    registry: 'MEKH',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 5,
    annualProductionTWh: 0.16,
    keyFeedstocks: 'Agricultural residues, animal manure',
    gridInterconnection: 'FGSZ gas transmission network.',
  },
  {
    id: 'SK_OKTE',
    name: 'Slovakia OKTE / SPP-D Support',
    shortName: 'SK OKTE',
    country: 'SK',
    countryName: 'Slovakia',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Biomethane injection protocol established with SPP-distribúcia.',
    legalBasis: 'Zákon č. 309/2009 Z. z.',
    registry: 'OKTE',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 4,
    annualProductionTWh: 0.12,
    keyFeedstocks: 'Agricultural waste, energy crops',
    gridInterconnection: 'Eustream / SPP-distribúcia.',
  },
  {
    id: 'RO_TRANSGAZ',
    name: 'Romania Transgaz Emerging Pool',
    shortName: 'RO Transgaz',
    country: 'RO',
    countryName: 'Romania',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'High biomass availability. Transgaz grid injection regulations under transposition.',
    legalBasis: 'Legea energiei nr. 123/2012',
    registry: 'ANRE / Transgaz',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 3,
    annualProductionTWh: 0.09,
    keyFeedstocks: 'Agricultural biomass, cereal straw',
    gridInterconnection: 'Transgaz national gas network.',
  },
  {
    id: 'BG_BULGARTRANSGAZ',
    name: 'Bulgaria Bulgartransgaz Framework',
    shortName: 'BG Market',
    country: 'BG',
    countryName: 'Bulgaria',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Energy from Renewable Sources Act amendments for biomethane grid access.',
    legalBasis: 'Energy from Renewable Sources Act (ZEVI)',
    registry: 'Bulgartransgaz',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 2,
    annualProductionTWh: 0.06,
    keyFeedstocks: 'Agricultural residues, livestock manure',
    gridInterconnection: 'Bulgartransgaz pipeline grid.',
  },
  {
    id: 'HR_PLINACRO',
    name: 'Croatia Plinacro / HROTE System',
    shortName: 'HR Plinacro',
    country: 'HR',
    countryName: 'Croatia',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'HROTE registry for green gases. First commercial grid injections active.',
    legalBasis: 'Zakon o obnovljivim izvorima energije',
    registry: 'HROTE / Plinacro',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 3,
    annualProductionTWh: 0.08,
    keyFeedstocks: 'Agricultural manure, agro-industrial waste',
    gridInterconnection: 'Plinacro gas transmission network.',
  },
  {
    id: 'SI_PLINOVODI',
    name: 'Slovenia Plinovodi / Borzen System',
    shortName: 'SI Borzen',
    country: 'SI',
    countryName: 'Slovenia',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Borzen registry of renewable gas guarantees of origin.',
    legalBasis: 'Zakon o oskrbi s plini (ZOP)',
    registry: 'Borzen / Plinovodi',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 2,
    annualProductionTWh: 0.05,
    keyFeedstocks: 'Sewage, municipal organic waste',
    gridInterconnection: 'Plinovodi gas transmission network.',
  },
  {
    id: 'GR_DESFA',
    name: 'Greece DESFA Biomethane Scheme',
    shortName: 'GR DESFA',
    country: 'GR',
    countryName: 'Greece',
    status: 'EMERGING',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Law 4951/2022 framework for biomethane plant licensing and DESFA grid injection.',
    legalBasis: 'Law 4951/2022',
    registry: 'DESFA / RAE',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: false,
    uncertainties: [],
    productionPlants: 2,
    annualProductionTWh: 0.05,
    keyFeedstocks: 'Livestock manure, olive pomace, agro-waste',
    gridInterconnection: 'DESFA Greek national gas system.',
  },

  // -------------------------------------------------------------
  // 3. PAN-EUROPEAN & VOLUNTARY CLEARING MECHANISMS
  // -------------------------------------------------------------
  {
    id: 'FUELEU',
    name: 'FuelEU Maritime (Regulation EU 2023/1805)',
    shortName: 'FuelEU Maritime',
    country: 'EU',
    countryName: 'European Union',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_TCO2E_DEFICIT',
    unitLabel: '€/tCO₂e',
    notes: 'Deficit-closure mechanism. Penalty €2,400/t VLSFO-eq (escalates 10%/20%/30% for consecutive non-compliant years). Small low-CI bio-LNG volume neutralises fleet deficit.',
    legalBasis: 'Regulation (EU) 2023/1805',
    registry: 'FuelEU Maritime Database / Thetis-MRV',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: true,
    uncertainties: [],
  },
  {
    id: 'EU_ETS1',
    name: 'EU ETS Phase 1 Installation Zero-Rating',
    shortName: 'EU ETS1',
    country: 'EU',
    countryName: 'European Union',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    notes: 'Industrial zero-rating (chemicals, steel, cement). Requires RED III sustainability compliance and actual combustion displacing fossil gas.',
    legalBasis: 'Directive 2003/87/EC',
    registry: 'Union Registry',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: true,
    uncertainties: [],
  },
  {
    id: 'EU_ETS2',
    name: 'EU ETS2 (Buildings & Road Transport)',
    shortName: 'EU ETS2',
    country: 'EU',
    countryName: 'European Union',
    status: 'FUTURE',
    unitOfAccount: 'EUR_PER_TCO2E',
    unitLabel: '€/tCO₂e',
    notes: 'Applies to commercial fuel distributors. Formally POSTPONED TO 2028 by European Council and Parliament (March 2026). Not currently tradeable.',
    legalBasis: 'Directive (EU) 2023/959',
    registry: 'Union Registry',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: true,
    acceptsBookAndClaim: false,
    isEUScope: true,
    uncertainties: [],
  },
  {
    id: 'VOL_SCOPE1',
    name: 'Voluntary Corporate Scope 1 / GHG Protocol',
    shortName: 'Voluntary Scope 1',
    country: 'EU',
    countryName: 'Pan-European / Global',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Most permissive market. Accepts Book-and-Claim, all certification schemes (including ISCC PLUS), no UDB mandatory recording.',
    legalBasis: 'GHG Protocol Corporate Standard (Market-Based Scope 1)',
    registry: 'AIB EECS Gas / National GO Registries',
    ceilingEurMwh: null,
    requiresMassBalance: false,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'AIB_GO',
    name: 'Pan-European AIB EECS Guarantees of Origin',
    shortName: 'AIB EECS GO',
    country: 'EU',
    countryName: 'Pan-European (AIB)',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'European Energy Certificate System (EECS) standard for voluntary corporate Scope 1 & green gas supply across AIB member states.',
    legalBasis: 'AIB EECS Rules & CEN - EN 16325',
    registry: 'AIB EECS Gas Scheme',
    ceilingEurMwh: null,
    requiresMassBalance: false,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: true,
    uncertainties: [],
  },
  {
    id: 'UK_RGGO',
    name: 'United Kingdom Renewable Gas Guarantees of Origin (RGGO)',
    shortName: 'UK RGGO',
    country: 'GB',
    countryName: 'United Kingdom',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'Green Gas Certification Scheme (GGCS) tracking biomethane injected into the UK gas grid for corporate voluntary Scope 1 reporting.',
    legalBasis: 'Green Gas Certification Scheme (GGCS)',
    registry: 'GGCS / Renewable Energy Assurance Limited',
    ceilingEurMwh: null,
    requiresMassBalance: false,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'DE_GO',
    name: 'Germany dena Biogasregister Guarantees of Origin',
    shortName: 'dena GO',
    country: 'DE',
    countryName: 'Germany',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'dena Biogasregister certificates for unsubsidised and subsidised green gas supply to German corporate industrials & utilities.',
    legalBasis: 'dena Biogasregister Satzung / EEG / EWärmeG',
    registry: 'dena Biogasregister',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'NL_GO',
    name: 'Netherlands VertiCer Guarantees of Origin',
    shortName: 'VertiCer GO',
    country: 'NL',
    countryName: 'Netherlands',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'VertiCer statutory Guarantees of Origin for Dutch biomethane grid injections, heat, and corporate Scope 1 use.',
    legalBasis: 'Gaswet Art. 52a',
    registry: 'VertiCer',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
  {
    id: 'FR_GO',
    name: 'France EEX / Powernext Biomethane Guarantees of Origin',
    shortName: 'EEX France GO',
    country: 'FR',
    countryName: 'France',
    status: 'ACTIVE',
    unitOfAccount: 'EUR_PER_MWH',
    unitLabel: '€/MWh',
    notes: 'National French biomethane registry operated by EEX under Ministry mandate. Auctions and bilateral transfers for voluntary green gas.',
    legalBasis: 'Code de l\'énergie, Art. L.446-18',
    registry: 'EEX Registre National des Garanties d\'Origine',
    ceilingEurMwh: null,
    requiresMassBalance: true,
    requiresUDB: false,
    acceptsBookAndClaim: true,
    isEUScope: false,
    uncertainties: [],
  },
];

export function getMarketById(id: string): Market | undefined {
  return MARKETS.find(m => m.id === id);
}

export function isVoluntaryMarket(marketId: string): boolean {
  const voluntaryIds = new Set([
    'UK_RGGO', 'DE_GO', 'NL_GO', 'FR_GO', 'DK_GO', 'ES_GDO', 'VOL_SCOPE1',
    'IE_RHO', 'PT_EEGO', 'HU_MEKH', 'SK_OKTE'
  ]);
  if (voluntaryIds.has(marketId)) return true;
  const market = getMarketById(marketId);
  return Boolean(market?.deskCategory === 'VOLUNTARY' || (market?.acceptsBookAndClaim && !market?.requiresUDB));
}

export function getMarketsByDeskCategory(category: 'COMPLIANCE' | 'VOLUNTARY'): Market[] {
  if (category === 'VOLUNTARY') {
    return MARKETS.filter(m => isVoluntaryMarket(m.id));
  }
  return MARKETS.filter(m => !isVoluntaryMarket(m.id));
}

