"""
Builds src/domain/ets1/installationsData.generated.ts from the EUETS.INFO release of the
EU Transaction Log (EUTL) — installation, operator and verified-emissions tables.

Source: https://euets-info-public.s3.eu-central-1.amazonaws.com/eutl_2024.zip
        (EUETS.INFO, Jan Abrell; data extracted from the EU Union Registry / EUTL, Aug 2024)

Usage:  python scripts/build_ets1_installations.py path/to/eutl_2024.zip

Scope: stationary installations in the EU ETS (not aircraft or maritime operators), EU/EEA
countries (GB excluded — it left the EU ETS in 2021), with verified emissions > 0 in the latest
year available. Each row keeps the operator (the account holder of the installation's
Operator Holding Account), the parent company where EUETS.INFO provides one, location,
activity and NACE codes, and verified emissions for the latest two years.

Nothing is estimated here: the EUTL does not split emissions by fuel, so gas use is NOT
derived. The sector / biomethane-fit grouping is done in the app, from the NACE and
activity codes, and labelled as a heuristic.
"""

import csv
import io
import json
import sys
import zipfile
from collections import defaultdict

OUT = 'src/domain/ets1/installationsData.generated.ts'


def read(z: zipfile.ZipFile, name: str):
    with z.open(name) as f:
        yield from csv.DictReader(io.TextIOWrapper(f, encoding='utf-8'))


def main(path: str) -> None:
    z = zipfile.ZipFile(path)

    installations = {
        r['id']: r
        for r in read(z, 'installation.csv')
        if r['tradingSystem_id'] == 'euets'
        and r['isAircraftOperator'] != 'True'
        and r['isMaritimeOperator'] != 'True'
        and r['country_id'] != 'GB'
    }

    verified: dict[str, dict[int, float]] = defaultdict(dict)
    for r in read(z, 'compliance.csv'):
        if r['installation_id'] not in installations or not r['verified']:
            continue
        try:
            verified[r['installation_id']][int(r['year'])] = float(r['verified'])
        except ValueError:
            continue

    latest = max(y for v in verified.values() for y, t in v.items() if t > 0)
    previous = latest - 1

    holders = {r['id']: r['name'] for r in read(z, 'account_holder.csv')}
    operator: dict[str, tuple[bool, str, str]] = {}
    for r in read(z, 'account.csv'):
        iid = r['installation_id']
        if iid not in installations or r['accountType_id'] != '100-7':
            continue
        holder_id = (r['accountHolder_id'] or '').split('.')[0]
        name = holders.get(holder_id, '') or r['name']
        key = (r['isOpen'] == 'True', r['openingDate'] or '', name)
        if iid not in operator or key > operator[iid]:
            operator[iid] = key

    rows = []
    for iid, inst in installations.items():
        v = verified.get(iid, {})
        if v.get(latest, 0) <= 0:
            continue
        rows.append([
            iid,
            inst['name'].strip(),
            operator.get(iid, (False, '', ''))[2].strip(),
            (inst['parentCompany'] or '').strip() if (inst['parentCompany'] or '').strip() not in ('-', '') else '',
            inst['country_id'],
            (inst['city'] or '').strip() if inst['city'] not in ('-', None) else '',
            int(inst['activity_id']) if inst['activity_id'] else None,
            inst['nace_id'] or '',
            round(v.get(latest, 0)),
            round(v[previous]) if previous in v else None,
        ])

    rows.sort(key=lambda r: -r[8])
    header = (
        '/**\n'
        ' * GENERATED by scripts/build_ets1_installations.py — do not hand-edit.\n'
        ' * Source: EUETS.INFO release eutl_2024.zip (EU Transaction Log, extracted Aug 2024),\n'
        ' * https://euets-info-public.s3.eu-central-1.amazonaws.com/eutl_2024.zip\n'
        f' * Stationary EU ETS installations with verified emissions > 0 in {latest}: {len(rows)} rows.\n'
        ' * Row: [id, name, operator, parentCompany, country, city, activityId, nace, verifiedLatest, verifiedPrevious]\n'
        ' */\n'
    )
    body = (
        f'export const ETS1_LATEST_YEAR = {latest};\n'
        f'export const ETS1_PREVIOUS_YEAR = {previous};\n'
        "export const ETS1_SOURCE_URL = 'https://euets-info-public.s3.eu-central-1.amazonaws.com/eutl_2024.zip';\n"
        'export type Ets1InstallationRow = [string, string, string, string, string, string, number | null, string, number, number | null];\n'
        'export const ETS1_INSTALLATION_ROWS: Ets1InstallationRow[] = '
        # '?' only occurs inside strings here; escaping it keeps garbled source names ("??")
        # from looking like code to the architecture guards.
        + json.dumps(rows, ensure_ascii=False, separators=(',', ':')).replace('?', '\\u003f')
        + ';\n'
    )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(header + body)
    print(f'{len(rows)} installations, latest year {latest}, written to {OUT}')


if __name__ == '__main__':
    main(sys.argv[1])
