/**
 * Builds src/domain/fueleu/lngShipsData.ts: the per-ship LNG vessel book — every ship flagged
 * isLng in data/fueleu_mrv_2025_ships.json (EU MRV 2025, ship-level extract), with FuelEU
 * compliance figures computed via the app's own calculator so the dataset can't drift from it.
 *
 * Run: npx tsx scripts/build_fueleu_lng_ships.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { calculateVesselExposure } from '../src/domain/fueleu/calculator';
import { fuelEuPoolBidPriceEurPerTco2e } from '../src/domain/assumptions/registry';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.join(__dirname, '..');
const SHIPS_JSON_PATH = path.join(REPO_ROOT, 'data', 'fueleu_mrv_2025_ships.json');
const GROUP_MAP_PATH = path.join(REPO_ROOT, 'data', 'fueleu_group_map.json');
const OUT_PATH = path.join(REPO_ROOT, 'src', 'domain', 'fueleu', 'lngShipsData.ts');

interface MrvShip {
  imo: string;
  name: string;
  shipType: string;
  company_imo: string;
  scopeShare: number;
  in_scope_vlsfo_t: number;
  in_scope_mgo_t: number;
  in_scope_lng_t: number;
  isLng: boolean;
}

interface ShipsFile {
  ships: MrvShip[];
}

interface GroupMapGroup {
  group_id: string;
  company_imos: string[];
}
interface GroupMapFile {
  groups: GroupMapGroup[];
}

const round = (x: number, dp: number) => Number(x.toFixed(dp));

const shipsFile: ShipsFile = JSON.parse(fs.readFileSync(SHIPS_JSON_PATH, 'utf8'));

const companyImoToGroupId = new Map<string, string>();
if (fs.existsSync(GROUP_MAP_PATH)) {
  const groupMap: GroupMapFile = JSON.parse(fs.readFileSync(GROUP_MAP_PATH, 'utf8'));
  for (const g of groupMap.groups) {
    for (const imo of g.company_imos) companyImoToGroupId.set(imo, g.group_id);
  }
}

const bidPrice = fuelEuPoolBidPriceEurPerTco2e();

const lngShips = shipsFile.ships.filter(s => s.isLng);

export interface LngShipRow {
  imo: string;
  name: string;
  shipType: string;
  company_imo: string;
  group_id: string;
  scopeShare: number;
  in_scope_vlsfo_t: number;
  in_scope_mgo_t: number;
  in_scope_lng_t: number;
  ghgie: number;
  balance2026Tco2e: number;
  penalty2026Y1Eur: number;
  bioLngNeededTonnes: number;
  bioLngNeededMwh: number;
  extraSurplusIfFullBioLngTco2e: number;
  extraSurplusValueEurAtBid: number;
}

const rows: LngShipRow[] = lngShips.map((s): LngShipRow => {
  const base = {
    vlsfoTonnes: s.in_scope_vlsfo_t,
    mgoTonnes: s.in_scope_mgo_t,
    lngTonnes: s.in_scope_lng_t,
    bioLngTonnes: 0,
    bioLngCi: -100,
    targetYear: 2026,
    consecutiveYearsNonCompliant: 1,
    shareThirdCountryVoyages: 0, // ship's in_scope_* tonnes are already Art. 2(1)-scoped
  };
  const r = calculateVesselExposure(base);

  // Full Bio-LNG substitution: displace all fossil LNG mass 1:1 with -100 CI Bio-LNG on the same ship.
  const fullBio = calculateVesselExposure({ ...base, lngTonnes: 0, bioLngTonnes: s.in_scope_lng_t });
  const extraSurplusIfFullBioLngTco2e = Math.max(0, round(fullBio.complianceBalanceTco2e, 1));

  return {
    imo: s.imo,
    name: s.name,
    shipType: s.shipType,
    company_imo: s.company_imo,
    group_id: companyImoToGroupId.get(s.company_imo) ?? `unmapped-${s.company_imo}`,
    scopeShare: s.scopeShare,
    in_scope_vlsfo_t: s.in_scope_vlsfo_t,
    in_scope_mgo_t: s.in_scope_mgo_t,
    in_scope_lng_t: s.in_scope_lng_t,
    ghgie: round(r.weightedGhgie, 2),
    balance2026Tco2e: round(r.complianceBalanceTco2e, 1),
    penalty2026Y1Eur: Math.round(r.statutoryPenaltyY1Eur),
    bioLngNeededTonnes: round(r.bioLngRequiredNeg100Tonnes, 1),
    bioLngNeededMwh: Math.round(r.bioLngRequiredNeg100Mwh),
    extraSurplusIfFullBioLngTco2e,
    extraSurplusValueEurAtBid: Math.round(extraSurplusIfFullBioLngTco2e * bidPrice),
  };
});

const lines: string[] = [];
lines.push('/**');
lines.push(' * Generated by scripts/build_fueleu_lng_ships.ts from data/fueleu_mrv_2025_ships.json');
lines.push(' * (EU MRV / THETIS-MRV public emission report, reporting year 2025, ship-level extract).');
lines.push(' * Every isLng ship. DO NOT hand-edit — regenerate instead.');
lines.push(' *');
lines.push(' * bioLngNeededTonnes/Mwh: -100 CI Bio-LNG (default engine class) needed to bring the 2026');
lines.push(' * compliance balance to exactly 0, displacing fossil LNG 1:1 by energy — 0 if the ship is');
lines.push(' * already in surplus. extraSurplusIfFullBioLngTco2e/extraSurplusValueEurAtBid: the resulting');
lines.push(' * compliance surplus (0 if none) and its value at the register bid if the ship burned 100%');
lines.push(' * of its in-scope LNG as -100 CI Bio-LNG instead.');
lines.push(' */');
lines.push('export interface LngShipRow {');
lines.push('  imo: string;');
lines.push('  name: string;');
lines.push('  shipType: string;');
lines.push('  company_imo: string;');
lines.push('  group_id: string;');
lines.push('  scopeShare: number;');
lines.push('  in_scope_vlsfo_t: number;');
lines.push('  in_scope_mgo_t: number;');
lines.push('  in_scope_lng_t: number;');
lines.push('  ghgie: number;');
lines.push('  balance2026Tco2e: number;');
lines.push('  penalty2026Y1Eur: number;');
lines.push('  bioLngNeededTonnes: number;');
lines.push('  bioLngNeededMwh: number;');
lines.push('  extraSurplusIfFullBioLngTco2e: number;');
lines.push('  extraSurplusValueEurAtBid: number;');
lines.push('}');
lines.push('');
lines.push('export const FUEL_EU_LNG_SHIPS: LngShipRow[] = [');
for (const row of rows) lines.push(JSON.stringify(row) + ',');
lines.push('];');
lines.push('');

fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');

console.log(`Wrote ${OUT_PATH}`);
console.log(`LNG ship count: ${rows.length}`);
const top5 = [...rows].sort((a, b) => b.bioLngNeededTonnes - a.bioLngNeededTonnes).slice(0, 5);
console.log('Top 5 by Bio-LNG needed:');
for (const r of top5) {
  console.log(`  ${r.name} (IMO ${r.imo}) — ${r.bioLngNeededTonnes.toLocaleString()} t Bio-LNG needed, balance=${r.balance2026Tco2e} tCO2e`);
}
