// scripts/route-audit/generate.mjs
// Compiles audited route matrix data into deterministic TypeScript domain artifacts.
// Run via: npm run routes:generate

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { COUNTRIES, POS_DEST_SCHEMES } from './rules.mjs';
import { computeGoPair, computePosPair } from './compute.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '../..');
const TARGET_FILE = path.join(ROOT_DIR, 'src', 'domain', 'routes', 'routeMatrix.generated.ts');

function dedupeSources(sources) {
  if (!sources || !Array.isArray(sources)) return [];
  const seen = new Set();
  const result = [];
  for (const s of sources) {
    if (!s) continue;
    const key = `${s.url || ''}|${s.claim || ''}`;
    if (!seen.has(key)) {
      seen.add(key);
      const clean = {
        claim: s.claim || '',
        url: s.url || '',
        quote: s.quote || '',
        grade: s.grade || 'PRIMARY',
      };
      result.push(clean);
    }
  }
  return result;
}

console.log('[generate] Computing biomethane route matrix for 28 countries (756 ordered pairs)...');

const sortedCountries = [...COUNTRIES].sort();

// Collect all 756 ordered pairs (orig !== dest) sorted deterministically
const pairKeys = [];
for (const orig of sortedCountries) {
  for (const dest of sortedCountries) {
    if (orig === dest) continue;
    pairKeys.push({ orig, dest, key: `${orig}_${dest}` });
  }
}
pairKeys.sort((a, b) => a.key.localeCompare(b.key));

const goRoutes = {};
const posRoutes = {};

for (const { orig, dest, key } of pairKeys) {
  const goRes = computeGoPair(orig, dest);
  const posRes = computePosPair(orig, dest, goRes);

  // Map GO status 'OPEN' to 'AWAITING_REGISTRY'
  const goStatus = goRes.status === 'OPEN' ? 'AWAITING_REGISTRY' : goRes.status;
  const goVia = goRes.via || 'NONE';

  const goRecord = {
    origin: orig,
    destination: dest,
    status: goStatus,
    via: goVia,
    grade: goRes.grade,
    reason: goRes.reason,
  };
  if (goRes.condition) {
    goRecord.condition = goRes.condition;
    goRecord.conditions = [goRes.condition];
  } else if (goRes.conditions && goRes.conditions.length > 0) {
    goRecord.conditions = goRes.conditions;
  }
  if (goRes.workaround) {
    goRecord.workaround = goRes.workaround;
  }
  if (goRes.openQuestionId) {
    goRecord.openQuestionId = goRes.openQuestionId;
  }
  goRecord.sources = dedupeSources(goRes.sources);

  goRoutes[key] = goRecord;

  // POS record
  const summary = {
    status: posRes.summary.status,
  };
  if (posRes.summary.schemeId) {
    summary.schemeId = posRes.summary.schemeId;
  }
  if (posRes.summary.schemeName) {
    summary.schemeName = posRes.summary.schemeName;
  }
  if (posRes.summary.conditions) {
    summary.conditions = posRes.summary.conditions;
  }
  summary.reason = posRes.summary.reason;

  const schemes = (posRes.schemes || []).map(s => {
    const sc = {
      schemeId: s.schemeId,
      schemeName: s.schemeName,
    };
    if (s.legalBasis) sc.legalBasis = s.legalBasis;
    sc.status = s.status;
    if (s.conditions) sc.conditions = s.conditions;
    sc.reason = s.reason;
    if (s.openQuestionId) sc.openQuestionId = s.openQuestionId;
    sc.sources = dedupeSources(s.sources);
    return sc;
  });
  schemes.sort((a, b) => a.schemeId.localeCompare(b.schemeId));

  posRoutes[key] = {
    origin: orig,
    destination: dest,
    summary,
    schemes,
  };
}

// Build POS_SCHEMES
const allSchemes = [];
for (const country of sortedCountries) {
  const list = POS_DEST_SCHEMES[country] || [];
  for (const s of list) {
    allSchemes.push({ ...s, country });
  }
}
allSchemes.sort((a, b) => a.id.localeCompare(b.id));

const posSchemes = {};
for (const s of allSchemes) {
  const rec = {
    id: s.id,
    name: s.name,
    country: s.country,
    legalBasis: s.legalBasis,
    acceptsForeign: s.acceptsForeign,
  };
  if (s.originScope) rec.originScope = s.originScope;
  if (s.conditions) rec.conditions = s.conditions;
  rec.reason = s.reason;
  rec.sources = dedupeSources(s.sources);
  if (s.openQuestionId) rec.openQuestionId = s.openQuestionId;
  if (s.goRequiredInRegistry) rec.goRequiredInRegistry = s.goRequiredInRegistry;

  posSchemes[s.id] = rec;
}

const fileHeader = `/* eslint-disable */
// GENERATED FILE - DO NOT EDIT MANUALLY
// Audit snapshot: 2026-10-04
// Generated by scripts/route-audit/generate.mjs

import type {
  GoRouteRecord,
  PosRouteRecord,
  PosSchemeRecord,
} from './types';

export const ROUTE_AUDIT_ACCESSED = '2026-10-04' as const;
`;

const fileContent = [
  fileHeader,
  `export const GO_ROUTES: Record<string, GoRouteRecord> = ${JSON.stringify(goRoutes, null, 2)};`,
  `export const POS_ROUTES: Record<string, PosRouteRecord> = ${JSON.stringify(posRoutes, null, 2)};`,
  `export const POS_SCHEMES: Record<string, PosSchemeRecord> = ${JSON.stringify(posSchemes, null, 2)};`,
  `export type * from './types';`,
  ''
].join('\n');

// Standardize CRLF line endings
const normalizedContent = fileContent.replace(/\r?\n/g, '\r\n');

fs.mkdirSync(path.dirname(TARGET_FILE), { recursive: true });
fs.writeFileSync(TARGET_FILE, normalizedContent, 'utf-8');

console.log(`[generate] Successfully generated: ${TARGET_FILE}`);
console.log(`[generate] GO_ROUTES: ${Object.keys(goRoutes).length} corridors`);
console.log(`[generate] POS_ROUTES: ${Object.keys(posRoutes).length} corridors`);
console.log(`[generate] POS_SCHEMES: ${Object.keys(posSchemes).length} statutory schemes`);
console.log(`[generate] Output size: ${(Buffer.byteLength(normalizedContent, 'utf-8') / 1024 / 1024).toFixed(2)} MB`);
