import {
  RegistryId,
  RegistryMetadata,
  InjectionBatch,
  RegistryAccount,
  BalanceOfTradeSummary,
  ProtocolInteroperability,
} from './types';

export const REGISTRY_METADATA_TABLE: Record<RegistryId, RegistryMetadata> = {
  DENA: {
    id: 'DENA',
    name: 'dena Biogasregister',
    operator: 'Deutsche Energie-Agentur GmbH (dena) / UBA',
    countryCode: 'DE',
    countryName: 'Germany',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    hubConnection: 'Trading Hub Europe (THE)',
    statutoryLegalBasis: '§37a BImSchG / 38. BImSchV & Biokraft-NachV',
    udbDirectIntegration: true,
  },
  VERTICER: {
    id: 'VERTICER',
    name: 'VertiCer & NEa REV',
    operator: 'VertiCer B.V. / Nederlandse Emissieautoriteit (NEa)',
    countryCode: 'NL',
    countryName: 'Netherlands',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    hubConnection: 'Title Transfer Facility (TTF)',
    statutoryLegalBasis: 'Wet milieubeheer / Regeling energie vervoer (ERE)',
    udbDirectIntegration: true,
  },
  ENERGINET: {
    id: 'ENERGINET',
    name: 'Energinet Biometangasregister',
    operator: 'Energinet Gas TSO A/S',
    countryCode: 'DK',
    countryName: 'Denmark',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Danish Gas System / Ellund & Dragør IPs',
    statutoryLegalBasis: 'Danish Natural Gas Supply Act & VE-Direktiv',
    udbDirectIntegration: true,
  },
  ENAGAS: {
    id: 'ENAGAS',
    name: 'Enagás GTS Sistema de Garantías de Origen',
    operator: 'Enagás GTS S.A.',
    countryCode: 'ES',
    countryName: 'Spain',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Punto Virtual de Balance (PVB)',
    statutoryLegalBasis: 'Real Decreto 376/2022 & Circular 1/2022 CNMC',
    udbDirectIntegration: true,
  },
  GSE: {
    id: 'GSE',
    name: 'GSE Piattaforma Biometano',
    operator: 'Gestore dei Servizi Energetici GSE S.p.A. / SNAM',
    countryCode: 'IT',
    countryName: 'Italy',
    isEUSingleArea: true,
    primaryProtocols: ['AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER', 'BILATERAL_RECOGNITION'],
    hubConnection: 'Punto di Scambio Virtuale (PSV)',
    statutoryLegalBasis: 'D.M. 02/03/2018 & PNRR D.M. 15/09/2022',
    udbDirectIntegration: true,
  },
  EEX: {
    id: 'EEX',
    name: 'EEX French National Biomethane Registry',
    operator: 'European Energy Exchange AG (Powernext) / DGDDI / ODRE',
    countryCode: 'FR',
    countryName: 'France',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Point d’Échange de Gaz (PEG)',
    statutoryLegalBasis: 'Code de l’énergie Art. L.446-24 / TIRUERT',
    udbDirectIntegration: true,
  },
  AGCS: {
    id: 'AGCS',
    name: 'AGCS Biomethane Registry Austria',
    operator: 'AGCS Gas Clearing and Settlement AG / E-Control',
    countryCode: 'AT',
    countryName: 'Austria',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Central European Gas Hub (CEGH)',
    statutoryLegalBasis: 'Erneuerbaren-Ausbau-Gesetz (EAG)',
    udbDirectIntegration: true,
  },
  GGCS_UK: {
    id: 'GGCS_UK',
    name: 'Green Gas Certification Scheme (GGCS) / RTFO',
    operator: 'Renewable Energy Assurance Ltd (REAL) / DfT',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    isEUSingleArea: false,
    primaryProtocols: ['DOMESTIC_ONLY', 'BILATERAL_RECOGNITION'],
    hubConnection: 'National Balancing Point (NBP)',
    statutoryLegalBasis: 'Energy Act 2004 / RTFO Order 2007 (SI 2007/3072)',
    udbDirectIntegration: false,
  },
  BRUGEL_BE: {
    id: 'BRUGEL_BE',
    name: 'Brugel / VREG / CWaPE Biomethane Registry',
    operator: 'Brugel / VREG / CWaPE / Fluxys Belgium',
    countryCode: 'BE',
    countryName: 'Belgium',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Zeebrugge Trading Point (ZTP)',
    statutoryLegalBasis: 'Energiedecreet & Décret wallon relatif à l’organisation du marché du gaz',
    udbDirectIntegration: true,
  },
  ENERGISVERIGE_SE: {
    id: 'ENERGISVERIGE_SE',
    name: 'Energigas Sverige / Swedegas GO Register',
    operator: 'Energigas Sverige / Nordion Energi (Swedegas)',
    countryCode: 'SE',
    countryName: 'Sweden',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Swedish Gas Network (Västgas)',
    statutoryLegalBasis: 'Lag (1994:1776) om skatt på energi / HBG System',
    udbDirectIntegration: true,
  },
  PRONOVO_CH: {
    id: 'PRONOVO_CH',
    name: 'Pronovo / VSG Biomethane Clearing',
    operator: 'Pronovo AG / Verband der Schweizerischen Gasindustrie (VSG)',
    countryCode: 'CH',
    countryName: 'Switzerland',
    isEUSingleArea: false,
    primaryProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    hubConnection: 'Swiss Gas Grid (Transitgas)',
    statutoryLegalBasis: 'Mineralölsteuergesetz (MinStG Art. 2a / 12b)',
    udbDirectIntegration: false,
  },
  GASGRID_FI: {
    id: 'GASGRID_FI',
    name: 'Gasgrid Finland GO Register',
    operator: 'Gasgrid Finland Oy / Energiavirasto',
    countryCode: 'FI',
    countryName: 'Finland',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Finnish Gas Hub (Balticconnector)',
    statutoryLegalBasis: 'Jakeluvelvoitelaki (446/2007) & Laki biopolttoaineista (393/2013)',
    udbDirectIntegration: true,
  },
  GASSCO_NO: {
    id: 'GASSCO_NO',
    name: 'Gassco / Statnett GO Registry',
    operator: 'Gassco AS / Statnett SF / NVE',
    countryCode: 'NO',
    countryName: 'Norway',
    isEUSingleArea: false,
    primaryProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    hubConnection: 'Norwegian Gas System (Gassled)',
    statutoryLegalBasis: 'Produktforskriften kap. 3 / Lov om opprinnelsesgarantier',
    udbDirectIntegration: false,
  },
  URE_PL: {
    id: 'URE_PL',
    name: 'Urząd Regulacji Energetyki (URE) / GAZ-SYSTEM',
    operator: 'Urząd Regulacji Energetyki (URE) / Operator Gazociągów Przesyłowych GAZ-SYSTEM S.A.',
    countryCode: 'PL',
    countryName: 'Poland',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Polish Power Exchange (TGE / Gas Hub)',
    statutoryLegalBasis: 'Ustawa o odnawialnych źródłach energii (Dz.U. 2023 poz. 1436)',
    udbDirectIntegration: true,
  },
  OTE_CZ: {
    id: 'OTE_CZ',
    name: 'OTE a.s. Biomethane Registry',
    operator: 'OTE, a.s. (Czech Electricity and Gas Market Operator) / NET4GAS',
    countryCode: 'CZ',
    countryName: 'Czechia',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Czech Gas Hub (OTE Virtual Point)',
    statutoryLegalBasis: 'Zákon č. 165/2012 Sb., o podporovaných zdrojích energie',
    udbDirectIntegration: true,
  },
  REN_PT: {
    id: 'REN_PT',
    name: 'REN - Redes Energéticas Nacionais GdO',
    operator: 'REN - Gasodutos S.A. / DGEG',
    countryCode: 'PT',
    countryName: 'Portugal',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'MIBGAS PT (Mercado Ibérico de Gás)',
    statutoryLegalBasis: 'Decreto-Lei n.º 84/2022 & Regulamento n.º 849/2022 ERSE',
    udbDirectIntegration: true,
  },
  GNI_IE: {
    id: 'GNI_IE',
    name: 'Gas Networks Ireland (GNI) Renewable Gas Registry',
    operator: 'Gas Networks Ireland / Commission for Regulation of Utilities (CRU)',
    countryCode: 'IE',
    countryName: 'Ireland',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Irish Balancing Point (IBP)',
    statutoryLegalBasis: 'National Oil Reserves Agency Act 2007 (Part 5A) & Renewable Transport Fuel Obligation',
    udbDirectIntegration: true,
  },
  MEKH_HU: {
    id: 'MEKH_HU',
    name: 'MEKH / CEEGEX GO Platform',
    operator: 'Magyar Energetikai és Közmű-szabályozási Hivatal (MEKH) / CEEGEX',
    countryCode: 'HU',
    countryName: 'Hungary',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Central Eastern European Gas Exchange (CEEGEX)',
    statutoryLegalBasis: '2007. évi LXXXVI. törvény a földgázellátásról (GET)',
    udbDirectIntegration: true,
  },
  ELERING_EE: {
    id: 'ELERING_EE',
    name: 'Elering Biomethane Register',
    operator: 'Elering AS / Konkurentsiamet',
    countryCode: 'EE',
    countryName: 'Estonia',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Baltic Gas Hub (Estonia-Latvia Interconnection)',
    statutoryLegalBasis: 'Vedelkütuse seadus § 2¹ & Maagaasiseadus',
    udbDirectIntegration: true,
  },
  CONEXUS_LV: {
    id: 'CONEXUS_LV',
    name: 'Conexus Baltic Grid GO Register',
    operator: 'AS Conexus Baltic Grid / SPRK',
    countryCode: 'LV',
    countryName: 'Latvia',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Inčukalns Underground Gas Storage / Baltic Hub',
    statutoryLegalBasis: 'Enerģētikas likums 42. pants & Ministru kabineta noteikumi',
    udbDirectIntegration: true,
  },
  AMBERGRID_LT: {
    id: 'AMBERGRID_LT',
    name: 'Amber Grid Biomethane GO Platform',
    operator: 'AB Amber Grid / Valstybinė energetikos reguliavimo taryba (VERT)',
    countryCode: 'LT',
    countryName: 'Lithuania',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Lithuanian Gas Hub (GIPL / Klaipėda)',
    statutoryLegalBasis: 'Lietuvos Respublikos atsinaujinančių išteklių energetikos įstatymas',
    udbDirectIntegration: true,
  },
  OKTE_SK: {
    id: 'OKTE_SK',
    name: 'SPP-distribúcia / OKTE GO Platform',
    operator: 'OKTE, a.s. / SPP - distribúcia, a.s. / ÚRSO',
    countryCode: 'SK',
    countryName: 'Slovakia',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Slovakian Gas Hub (Baumgarten Entry / Veľké Kapušany)',
    statutoryLegalBasis: 'Zákon č. 309/2009 Z. z. o podpore obnoviteľných zdrojov energie',
    udbDirectIntegration: true,
  },
};

export const BASELINE_INJECTION_BATCHES: InjectionBatch[] = [
  // --- DENMARK (Energinet) ---
  {
    id: 'BATCH-DK-2026-001',
    plantId: 'PLANT-DK-GLANSAGER',
    plantName: 'Nature Energy Glansager',
    originCountry: 'DK',
    registryId: 'ENERGINET',
    injectionPointId: 'DK-IP-ELLUND-01',
    meteringPeriod: { startDate: '2026-08-01', endDate: '2026-08-15' },
    volumeMWh: 48500,
    volumeNm3: 4490740,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Manure & Agricultural Slurry',
    feedstockDetails: '75% Liquid bovine manure, 25% deep litter straw',
    annexClassification: 'IX_A',
    verifiedCI: -95.2,
    sustainabilityProofId: 'ISCC-EU-POS-2026-DK-99210',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-DK-2026-0891',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-16T08:30:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DK-2026-002',
    plantId: 'PLANT-DK-HOLSTED',
    plantName: 'Nature Energy Holsted',
    originCountry: 'DK',
    registryId: 'ENERGINET',
    injectionPointId: 'DK-IP-ELLUND-02',
    meteringPeriod: { startDate: '2026-07-15', endDate: '2026-07-31' },
    volumeMWh: 62000,
    volumeNm3: 5767440,
    grossCalorificValueKwhNm3: 10.75,
    feedstockCategory: 'Manure & Organic Residues',
    feedstockDetails: '80% Swine/Cattle slurry, 20% certified organic waste',
    annexClassification: 'IX_A',
    verifiedCI: -88.4,
    sustainabilityProofId: 'REDC-EU-POS-2026-DK-44120',
    certificationScheme: 'REDcert EU',
    udbRegistrationId: 'UDB-DK-2026-1044',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-01T10:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DK-2026-003',
    plantId: 'PLANT-DK-VINKEL',
    plantName: 'Vinkel Bioenergi Skive',
    originCountry: 'DK',
    registryId: 'ENERGINET',
    injectionPointId: 'DK-IP-SKIVE-01',
    meteringPeriod: { startDate: '2026-08-01', endDate: '2026-08-15' },
    volumeMWh: 35000,
    volumeNm3: 3271028,
    grossCalorificValueKwhNm3: 10.7,
    feedstockCategory: 'Manure & Catch Crops',
    feedstockDetails: '70% Slurry, 30% intermediate agricultural catch crops',
    annexClassification: 'IX_A',
    verifiedCI: -104.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-DK-77119',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-DK-2026-0955',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-16T09:15:00Z',
    status: 'ISSUED',
  },

  // --- GERMANY (dena) ---
  {
    id: 'BATCH-DE-2026-001',
    plantId: 'PLANT-DE-GUESTROW',
    plantName: 'Bioenergie Park Güstrow',
    originCountry: 'DE',
    registryId: 'DENA',
    injectionPointId: 'DE-ONTRAS-GUESTROW-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 42000,
    volumeNm3: 3962264,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Agricultural Residues & Slurry',
    feedstockDetails: '60% Slurry, 40% agricultural straw & residue',
    annexClassification: 'IX_A',
    verifiedCI: -82.0,
    sustainabilityProofId: 'REDC-EU-POS-2026-DE-11045',
    certificationScheme: 'REDcert EU',
    udbRegistrationId: 'UDB-DE-2026-3042',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-05T14:20:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DE-2026-002',
    plantId: 'PLANT-DE-KOENNERN',
    plantName: 'Biomethananlage Könnern',
    originCountry: 'DE',
    registryId: 'DENA',
    injectionPointId: 'DE-MITNETZ-KOENNERN-02',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 28000,
    volumeNm3: 2641509,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Energy Crops (Maize/Sorghum)',
    feedstockDetails: '85% Silage maize, 15% whole crop rye',
    annexClassification: 'CROP',
    verifiedCI: 24.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-DE-88201',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-DE-2026-3088',
    gridInterconnectionStatus: 'DSO_DISTRIBUTION',
    issuedAt: '2026-08-05T14:30:00Z',
    status: 'ISSUED',
  },

  // --- NETHERLANDS (VertiCer) ---
  {
    id: 'BATCH-NL-2026-001',
    plantId: 'PLANT-NL-WIJSTER',
    plantName: 'Attero Wijster Bio-Gasification',
    originCountry: 'NL',
    registryId: 'VERTICER',
    injectionPointId: 'NL-GTS-WIJSTER-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 31000,
    volumeNm3: 2952380,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Municipal Organic Waste (OFMSW)',
    feedstockDetails: 'Source-separated municipal food waste & green waste',
    annexClassification: 'IX_A',
    verifiedCI: 11.2,
    sustainabilityProofId: 'ISCC-EU-POS-2026-NL-33120',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-NL-2026-0412',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-08T11:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-NL-2026-002',
    plantId: 'PLANT-NL-VIERVERLATEN',
    plantName: 'Cosun Beet Company Vierverlaten',
    originCountry: 'NL',
    registryId: 'VERTICER',
    injectionPointId: 'NL-GTS-VIERV-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 22000,
    volumeNm3: 2095238,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Agro-Industrial Residues (Sugar Beet Pulp)',
    feedstockDetails: '100% Sugar beet processing pulp and water-wash residue',
    annexClassification: 'IX_A',
    verifiedCI: 18.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-NL-33145',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-NL-2026-0455',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-08T11:15:00Z',
    status: 'ISSUED',
  },

  // --- SPAIN (Enagás) ---
  {
    id: 'BATCH-ES-2026-001',
    plantId: 'PLANT-ES-TORREGROSA',
    plantName: 'Torregrossa Biometano Lleida',
    originCountry: 'ES',
    registryId: 'ENAGAS',
    injectionPointId: 'ES-ENAGAS-LLEIDA-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 24000,
    volumeNm3: 2242990,
    grossCalorificValueKwhNm3: 10.7,
    feedstockCategory: 'Pig Slurry & Agro-Residues',
    feedstockDetails: '85% Catalan porcine manure, 15% olive pomace residue',
    annexClassification: 'IX_A',
    verifiedCI: -84.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-ES-55012',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-ES-2026-0901',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-10T16:00:00Z',
    status: 'ISSUED',
  },

  // --- ITALY (GSE) ---
  {
    id: 'BATCH-IT-2026-001',
    plantId: 'PLANT-IT-CALVENZANO',
    plantName: 'Calvenzano Biometano (Bergamo)',
    originCountry: 'IT',
    registryId: 'GSE',
    injectionPointId: 'IT-SNAM-BG-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 27000,
    volumeNm3: 2547169,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Bovine Slurry & Agri-byproducts',
    feedstockDetails: '70% Bovine slurry, 30% silomais secondary crop',
    annexClassification: 'IX_A',
    verifiedCI: -72.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-IT-91024',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-IT-2026-0188',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-12T09:00:00Z',
    status: 'ISSUED',
  },

  // --- FRANCE (EEX) ---
  {
    id: 'BATCH-FR-2026-001',
    plantId: 'PLANT-FR-BEAUCE',
    plantName: 'Beauce Biométhane (Eure-et-Loir)',
    originCountry: 'FR',
    registryId: 'EEX',
    injectionPointId: 'FR-GRTGAZ-BEAUCE-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 29500,
    volumeNm3: 2809523,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'CIVE (Intermediate Catch Crops) & Manure',
    feedstockDetails: '65% Winter intermediate crops (CIVE), 35% cattle manure',
    annexClassification: 'IX_A',
    verifiedCI: 8.5,
    sustainabilityProofId: '2BSVS-EU-POS-2026-FR-1049',
    certificationScheme: '2BSvs',
    udbRegistrationId: 'UDB-FR-2026-5501',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-14T10:30:00Z',
    status: 'ISSUED',
  },

  // --- AUSTRIA (AGCS) ---
  {
    id: 'BATCH-AT-2026-001',
    plantId: 'PLANT-AT-MARG_EINSIEDL',
    plantName: 'Biogas Margarethen am Moos',
    originCountry: 'AT',
    registryId: 'AGCS',
    injectionPointId: 'AT-TAG-MARG-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 14000,
    volumeNm3: 1320754,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Agricultural Silage & Manure',
    feedstockDetails: '50% Manure, 50% clover grass silage',
    annexClassification: 'IX_A',
    verifiedCI: -45.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-AT-7740',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-AT-2026-0120',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-11T12:00:00Z',
    status: 'ISSUED',
  },

  // --- BELGIUM (Brugel / Fluxys) ---
  {
    id: 'BATCH-BE-2026-001',
    plantId: 'PLANT-BE-ZEEBRUGGE',
    plantName: 'Bio-Accelerate Oostende Bio-Upgrading',
    originCountry: 'BE',
    registryId: 'BRUGEL_BE',
    injectionPointId: 'BE-FLUXYS-ZEE-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 16500,
    volumeNm3: 1571428,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Organic Bio-Waste & Slurry',
    feedstockDetails: '60% Food industrial waste, 40% Flemish cattle slurry',
    annexClassification: 'IX_A',
    verifiedCI: 12.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-BE-1920',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-BE-2026-0104',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-15T09:00:00Z',
    status: 'ISSUED',
  },

  // --- SWEDEN (Energigas Sverige) ---
  {
    id: 'BATCH-SE-2026-001',
    plantId: 'PLANT-SE-JORDANSTORP',
    plantName: 'Jordberga Biogas (Skåne)',
    originCountry: 'SE',
    registryId: 'ENERGISVERIGE_SE',
    injectionPointId: 'SE-SWEDEGAS-SKA-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 21000,
    volumeNm3: 1981132,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Manure & Sugar Residues',
    feedstockDetails: '70% Swine manure, 30% sugar beet residues',
    annexClassification: 'IX_A',
    verifiedCI: -86.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-SE-4481',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-SE-2026-0309',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-14T08:00:00Z',
    status: 'ISSUED',
  },

  // --- SWITZERLAND (Pronovo - Non-EU) ---
  {
    id: 'BATCH-CH-2026-001',
    plantId: 'PLANT-CH-VOLKETSWIL',
    plantName: 'Biogas Zürich / Volketswil Hub',
    originCountry: 'CH',
    registryId: 'PRONOVO_CH',
    injectionPointId: 'CH-TRANSITGAS-ZH-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 12000,
    volumeNm3: 1142857,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Green Waste & Food Scraps',
    feedstockDetails: '100% Municipal biowaste from Canton Zürich',
    annexClassification: 'IX_A',
    verifiedCI: 14.2,
    sustainabilityProofId: 'CH-PRONOVO-POS-2026-8812',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: null,
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-10T11:00:00Z',
    status: 'ISSUED',
  },

  // --- FINLAND (Gasgrid Finland) ---
  {
    id: 'BATCH-FI-2026-001',
    plantId: 'PLANT-FI-LAHTI',
    plantName: 'Lahti Kujala Biogas Injection',
    originCountry: 'FI',
    registryId: 'GASGRID_FI',
    injectionPointId: 'FI-GASGRID-LAH-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 15500,
    volumeNm3: 1462264,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Sewage Sludge & Bio-waste',
    feedstockDetails: '55% Municipal wastewater sludge, 45% regional food waste',
    annexClassification: 'IX_A',
    verifiedCI: 6.8,
    sustainabilityProofId: 'ISCC-EU-POS-2026-FI-0912',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-FI-2026-0112',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-12T07:45:00Z',
    status: 'ISSUED',
  },

  // --- NORWAY (Gassco - Non-EU) ---
  {
    id: 'BATCH-NO-2026-001',
    plantId: 'PLANT-NO-RENSVOLL',
    plantName: 'Ragn-Sells Biogass Mjøsa',
    originCountry: 'NO',
    registryId: 'GASSCO_NO',
    injectionPointId: 'NO-GASSCO-MJO-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 9800,
    volumeNm3: 933333,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Fish Processing Sludge & Manure',
    feedstockDetails: '60% Aquaculture fish sludge, 40% cattle manure',
    annexClassification: 'IX_A',
    verifiedCI: -68.0,
    sustainabilityProofId: 'NO-GASSCO-POS-2026-1021',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: null,
    gridInterconnectionStatus: 'OFF_GRID_SEGREGATED',
    issuedAt: '2026-08-09T13:00:00Z',
    status: 'ISSUED',
  },

  // --- POLAND (URE / GAZ-SYSTEM) ---
  {
    id: 'BATCH-PL-2026-001',
    plantId: 'PLANT-PL-BRODNICA',
    plantName: 'Brodnica Biometan Hub',
    originCountry: 'PL',
    registryId: 'URE_PL',
    injectionPointId: 'PL-GAZSYSTEM-BROD-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 18500,
    volumeNm3: 1745283,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Distillery Residues & Manure',
    feedstockDetails: '50% Stillage from bioethanol production, 50% swine manure',
    annexClassification: 'IX_A',
    verifiedCI: -62.0,
    sustainabilityProofId: 'REDcert-EU-POS-2026-PL-4402',
    certificationScheme: 'REDcert EU',
    udbRegistrationId: 'UDB-PL-2026-0044',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-16T11:00:00Z',
    status: 'ISSUED',
  },

  // --- CZECHIA (OTE / NET4GAS) ---
  {
    id: 'BATCH-CZ-2026-001',
    plantId: 'PLANT-CZ-RAPOTIN',
    plantName: 'Energy Centre Rapotín',
    originCountry: 'CZ',
    registryId: 'OTE_CZ',
    injectionPointId: 'CZ-NET4GAS-RAP-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 11500,
    volumeNm3: 1084905,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Food Waste & Biodegradable Slurry',
    feedstockDetails: '70% Commercial kitchen & supermarket waste, 30% cattle manure',
    annexClassification: 'IX_A',
    verifiedCI: 10.4,
    sustainabilityProofId: 'ISCC-EU-POS-2026-CZ-8831',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-CZ-2026-0089',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-13T15:00:00Z',
    status: 'ISSUED',
  },

  // --- PORTUGAL (REN) ---
  {
    id: 'BATCH-PT-2026-001',
    plantId: 'PLANT-PT-SANTAREM',
    plantName: 'Santarém Bio-Val Micro-Grid',
    originCountry: 'PT',
    registryId: 'REN_PT',
    injectionPointId: 'PT-REN-SAN-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 8200,
    volumeNm3: 780952,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Olive Mill Wastewater & Pig Slurry',
    feedstockDetails: '55% Olive bagasse and wastewater, 45% porcine slurry',
    annexClassification: 'IX_A',
    verifiedCI: -70.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-PT-1120',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-PT-2026-0022',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-11T14:30:00Z',
    status: 'ISSUED',
  },

  // --- IRELAND (GNI) ---
  {
    id: 'BATCH-IE-2026-001',
    plantId: 'PLANT-IE-CUSH',
    plantName: 'Cush Renewable Gas Entry Facility (Kildare)',
    originCountry: 'IE',
    registryId: 'GNI_IE',
    injectionPointId: 'IE-GNI-CUSH-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 10500,
    volumeNm3: 990566,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Bovine Slurry & Multi-species Sward Grass',
    feedstockDetails: '70% Bovine slurry, 30% sustainable multi-species swards',
    annexClassification: 'IX_A',
    verifiedCI: -80.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-IE-9912',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-IE-2026-0035',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-15T11:00:00Z',
    status: 'ISSUED',
  },

  // --- HUNGARY (MEKH / CEEGEX) ---
  {
    id: 'BATCH-HU-2026-001',
    plantId: 'PLANT-HU-SZEGED',
    plantName: 'Szeged Agro-Biometán Központ',
    originCountry: 'HU',
    registryId: 'MEKH_HU',
    injectionPointId: 'HU-FGSZ-SZEG-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 9400,
    volumeNm3: 886792,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Agricultural Residues & Manure',
    feedstockDetails: '60% Poultry manure, 40% corn stover residues',
    annexClassification: 'IX_A',
    verifiedCI: -58.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-HU-6601',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-HU-2026-0041',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-10T10:00:00Z',
    status: 'ISSUED',
  },

  // --- ESTONIA (Elering) ---
  {
    id: 'BATCH-EE-2026-001',
    plantId: 'PLANT-EE-VINNI',
    plantName: 'Vinni Biogaasijaam (Lääne-Virumaa)',
    originCountry: 'EE',
    registryId: 'ELERING_EE',
    injectionPointId: 'EE-ELERING-VIN-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 7800,
    volumeNm3: 735849,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Cattle Slurry & Straw',
    feedstockDetails: '80% Cattle manure, 20% agricultural straw residue',
    annexClassification: 'IX_A',
    verifiedCI: -91.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-EE-0019',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-EE-2026-0018',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-12T08:30:00Z',
    status: 'ISSUED',
  },

  // --- LATVIA (Conexus Baltic Grid) ---
  {
    id: 'BATCH-LV-2026-001',
    plantId: 'PLANT-LV-JELGAVA',
    plantName: 'Jelgava Bio-Gāze Injection Station',
    originCountry: 'LV',
    registryId: 'CONEXUS_LV',
    injectionPointId: 'LV-CONEXUS-JEL-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 6500,
    volumeNm3: 613207,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Animal Manure & Grain Residues',
    feedstockDetails: '70% Porcine slurry, 30% grain processing screening residues',
    annexClassification: 'IX_A',
    verifiedCI: -78.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-LV-0042',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-LV-2026-0015',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-13T09:00:00Z',
    status: 'ISSUED',
  },

  // --- LITHUANIA (Amber Grid) ---
  {
    id: 'BATCH-LT-2026-001',
    plantId: 'PLANT-LT-PASVALYS',
    plantName: 'Kurana Pasvalys Bio-Refinery Hub',
    originCountry: 'LT',
    registryId: 'AMBERGRID_LT',
    injectionPointId: 'LT-AMBER-PASV-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 8900,
    volumeNm3: 839622,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Bioethanol Stillage & Manure',
    feedstockDetails: '60% Wheat stillage, 40% dairy cattle manure',
    annexClassification: 'IX_A',
    verifiedCI: -65.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-LT-0182',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-LT-2026-0027',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-14T10:00:00Z',
    status: 'ISSUED',
  },

  // --- SLOVAKIA (OKTE / SPP) ---
  {
    id: 'BATCH-SK-2026-001',
    plantId: 'PLANT-SK-JEKPO',
    plantName: 'Jelšava Biometán s.r.o.',
    originCountry: 'SK',
    registryId: 'OKTE_SK',
    injectionPointId: 'SK-SPP-JEL-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 7200,
    volumeNm3: 679245,
    grossCalorificValueKwhNm3: 10.6,
    feedstockCategory: 'Agricultural Residues & Slurry',
    feedstockDetails: '55% Cattle slurry, 45% cereal straw & husk residue',
    annexClassification: 'IX_A',
    verifiedCI: -54.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-SK-0081',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-SK-2026-0019',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-12T14:00:00Z',
    status: 'ISSUED',
  },

  // --- UNITED KINGDOM (GGCS - Non-EU) ---
  {
    id: 'BATCH-GB-2026-001',
    plantId: 'PLANT-GB-RAINBARROW',
    plantName: 'Rainbarrow Farm (Poundbury)',
    originCountry: 'GB',
    registryId: 'GGCS_UK',
    injectionPointId: 'GB-SGN-DORSET-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 18000,
    volumeNm3: 1714285,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Food Waste & Farm Slurry',
    feedstockDetails: '70% Dorset commercial food waste, 30% farm slurry',
    annexClassification: 'IX_A',
    verifiedCI: 15.0,
    sustainabilityProofId: 'REAL-GGCS-POS-2026-0812',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: null,
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-01T12:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-GB-2026-002',
    plantId: 'PLANT-GB-BARKSTON',
    plantName: 'Barkston Heath Biomethane Facility',
    originCountry: 'GB',
    registryId: 'GGCS_UK',
    injectionPointId: 'GB-CADENT-LINCS-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-31' },
    volumeMWh: 39000,
    volumeNm3: 3714285,
    grossCalorificValueKwhNm3: 10.5,
    feedstockCategory: 'Energy Crops (Maize & Rye)',
    feedstockDetails: '80% Silage maize, 20% hybrid rye',
    annexClassification: 'CROP',
    verifiedCI: 36.5,
    sustainabilityProofId: 'REAL-GGCS-POS-2026-0899',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: null,
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-02T15:00:00Z',
    status: 'ISSUED',
  },
];

export const BASELINE_ACCOUNTS: RegistryAccount[] = [
  {
    registryId: 'DENA',
    registryName: 'dena Biogasregister',
    countryCode: 'DE',
    accountHolderId: 'ACC-DE-DESK-01',
    accountHolderName: 'Continental Gas Desk GmbH',
    currentBalanceMWh: 125000,
    availableForExportMWh: 35000,
    reservedEscrowMWh: 12000,
    activeBatchesCount: 2,
  },
  {
    registryId: 'ENERGINET',
    registryName: 'Energinet Biometangasregister',
    countryCode: 'DK',
    accountHolderId: 'ACC-DK-DESK-01',
    accountHolderName: 'Nordic Renewable Commodities A/S',
    currentBalanceMWh: 210000,
    availableForExportMWh: 175000,
    reservedEscrowMWh: 25000,
    activeBatchesCount: 3,
  },
  {
    registryId: 'VERTICER',
    registryName: 'VertiCer & NEa REV',
    countryCode: 'NL',
    accountHolderId: 'ACC-NL-DESK-01',
    accountHolderName: 'Low Carbon Commodities B.V.',
    currentBalanceMWh: 83000,
    availableForExportMWh: 18000,
    reservedEscrowMWh: 8500,
    activeBatchesCount: 2,
  },
  {
    registryId: 'ENAGAS',
    registryName: 'Enagás GTS Sistema de GdO',
    countryCode: 'ES',
    accountHolderId: 'ACC-ES-DESK-01',
    accountHolderName: 'Iberian Renewable Gas Trading S.L.',
    currentBalanceMWh: 58000,
    availableForExportMWh: 45000,
    reservedEscrowMWh: 6000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'GSE',
    registryName: 'GSE Piattaforma Biometano',
    countryCode: 'IT',
    accountHolderId: 'ACC-IT-DESK-01',
    accountHolderName: 'Trans-Alpine Gas Desk S.r.l.',
    currentBalanceMWh: 93000,
    availableForExportMWh: 40000,
    reservedEscrowMWh: 15000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'EEX',
    registryName: 'EEX French Registry',
    countryCode: 'FR',
    accountHolderId: 'ACC-FR-DESK-01',
    accountHolderName: 'Hexagone Biométhane SAS',
    currentBalanceMWh: 58000,
    availableForExportMWh: 12000,
    reservedEscrowMWh: 4000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'AGCS',
    registryName: 'AGCS Biomethane Registry Austria',
    countryCode: 'AT',
    accountHolderId: 'ACC-AT-DESK-01',
    accountHolderName: 'Alps-Danube Energy Trading GmbH',
    currentBalanceMWh: 34000,
    availableForExportMWh: 14000,
    reservedEscrowMWh: 3000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'GGCS_UK',
    registryName: 'Green Gas Certification Scheme (UK)',
    countryCode: 'GB',
    accountHolderId: 'ACC-GB-DESK-01',
    accountHolderName: 'UK Renewable Fuels Desk Ltd',
    currentBalanceMWh: 57000,
    availableForExportMWh: 57000,
    reservedEscrowMWh: 0,
    activeBatchesCount: 2,
  },
  {
    registryId: 'BRUGEL_BE',
    registryName: 'Brugel / VREG Registry (Belgium)',
    countryCode: 'BE',
    accountHolderId: 'ACC-BE-DESK-01',
    accountHolderName: 'Belgian Green Gas Trader NV',
    currentBalanceMWh: 32000,
    availableForExportMWh: 12000,
    reservedEscrowMWh: 2500,
    activeBatchesCount: 1,
  },
  {
    registryId: 'ENERGISVERIGE_SE',
    registryName: 'Energigas Sverige GO (Sweden)',
    countryCode: 'SE',
    accountHolderId: 'ACC-SE-DESK-01',
    accountHolderName: 'Scandic Biogas Trading AB',
    currentBalanceMWh: 45000,
    availableForExportMWh: 22000,
    reservedEscrowMWh: 4000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'PRONOVO_CH',
    registryName: 'Pronovo / VSG (Switzerland)',
    countryCode: 'CH',
    accountHolderId: 'ACC-CH-DESK-01',
    accountHolderName: 'Helvetia Renewable Gas AG',
    currentBalanceMWh: 18000,
    availableForExportMWh: 0,
    reservedEscrowMWh: 0,
    activeBatchesCount: 1,
  },
  {
    registryId: 'GASGRID_FI',
    registryName: 'Gasgrid Finland GO (Finland)',
    countryCode: 'FI',
    accountHolderId: 'ACC-FI-DESK-01',
    accountHolderName: 'Fennoscandia Biomethane Oy',
    currentBalanceMWh: 24000,
    availableForExportMWh: 14000,
    reservedEscrowMWh: 2000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'GASSCO_NO',
    registryName: 'Gassco / Statnett (Norway)',
    countryCode: 'NO',
    accountHolderId: 'ACC-NO-DESK-01',
    accountHolderName: 'Norsk Biogass Trading AS',
    currentBalanceMWh: 14000,
    availableForExportMWh: 0,
    reservedEscrowMWh: 0,
    activeBatchesCount: 1,
  },
  {
    registryId: 'URE_PL',
    registryName: 'URE / GAZ-SYSTEM (Poland)',
    countryCode: 'PL',
    accountHolderId: 'ACC-PL-DESK-01',
    accountHolderName: 'Polski Biometan Sp. z o.o.',
    currentBalanceMWh: 38000,
    availableForExportMWh: 22000,
    reservedEscrowMWh: 3500,
    activeBatchesCount: 1,
  },
  {
    registryId: 'OTE_CZ',
    registryName: 'OTE a.s. (Czechia)',
    countryCode: 'CZ',
    accountHolderId: 'ACC-CZ-DESK-01',
    accountHolderName: 'Bohemia Green Gas s.r.o.',
    currentBalanceMWh: 26000,
    availableForExportMWh: 12000,
    reservedEscrowMWh: 2000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'REN_PT',
    registryName: 'REN GdO (Portugal)',
    countryCode: 'PT',
    accountHolderId: 'ACC-PT-DESK-01',
    accountHolderName: 'Lusitânia Biogás Trading Lda',
    currentBalanceMWh: 16000,
    availableForExportMWh: 9000,
    reservedEscrowMWh: 1500,
    activeBatchesCount: 1,
  },
  {
    registryId: 'GNI_IE',
    registryName: 'GNI Registry (Ireland)',
    countryCode: 'IE',
    accountHolderId: 'ACC-IE-DESK-01',
    accountHolderName: 'Celtic Green Gas Trading Ltd',
    currentBalanceMWh: 19000,
    availableForExportMWh: 6000,
    reservedEscrowMWh: 1000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'MEKH_HU',
    registryName: 'MEKH / CEEGEX (Hungary)',
    countryCode: 'HU',
    accountHolderId: 'ACC-HU-DESK-01',
    accountHolderName: 'Danubian Biomethane Kft.',
    currentBalanceMWh: 17000,
    availableForExportMWh: 8000,
    reservedEscrowMWh: 1200,
    activeBatchesCount: 1,
  },
  {
    registryId: 'ELERING_EE',
    registryName: 'Elering (Estonia)',
    countryCode: 'EE',
    accountHolderId: 'ACC-EE-DESK-01',
    accountHolderName: 'Baltic Biomethane OÜ',
    currentBalanceMWh: 12000,
    availableForExportMWh: 7500,
    reservedEscrowMWh: 1000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'CONEXUS_LV',
    registryName: 'Conexus Baltic Grid (Latvia)',
    countryCode: 'LV',
    accountHolderId: 'ACC-LV-DESK-01',
    accountHolderName: 'Latvija Bio-Trading SIA',
    currentBalanceMWh: 9500,
    availableForExportMWh: 5000,
    reservedEscrowMWh: 800,
    activeBatchesCount: 1,
  },
  {
    registryId: 'AMBERGRID_LT',
    registryName: 'Amber Grid (Lithuania)',
    countryCode: 'LT',
    accountHolderId: 'ACC-LT-DESK-01',
    accountHolderName: 'Lietuva Green Gas UAB',
    currentBalanceMWh: 14000,
    availableForExportMWh: 8000,
    reservedEscrowMWh: 1200,
    activeBatchesCount: 1,
  },
  {
    registryId: 'OKTE_SK',
    registryName: 'OKTE (Slovakia)',
    countryCode: 'SK',
    accountHolderId: 'ACC-SK-DESK-01',
    accountHolderName: 'Slovakia Biogas Trading s.r.o.',
    currentBalanceMWh: 11000,
    availableForExportMWh: 5500,
    reservedEscrowMWh: 900,
    activeBatchesCount: 1,
  },
];

export const BASELINE_BALANCE_OF_TRADE: BalanceOfTradeSummary[] = [
  {
    registryId: 'ENERGINET',
    countryCode: 'DK',
    registryName: 'Energinet Biometangasregister',
    totalIssuanceMWh: 6800000,
    domesticConsumptionMWh: 1200000,
    grossExportMWh: 5600000,
    grossImportMWh: 0,
    netTradeBalanceMWh: 5600000,
    activeEscrowMWh: 240000,
    totalCancellationsMWh: 1200000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 82.35,
  },
  {
    registryId: 'DENA',
    countryCode: 'DE',
    registryName: 'dena Biogasregister',
    totalIssuanceMWh: 11800000,
    domesticConsumptionMWh: 14600000,
    grossExportMWh: 600000,
    grossImportMWh: 3400000,
    netTradeBalanceMWh: -2800000,
    activeEscrowMWh: 450000,
    totalCancellationsMWh: 14600000,
    tradeRole: 'NET_IMPORTER',
    exportSharePercent: 5.08,
  },
  {
    registryId: 'VERTICER',
    countryCode: 'NL',
    registryName: 'VertiCer / NEa REV',
    totalIssuanceMWh: 3200000,
    domesticConsumptionMWh: 4500000,
    grossExportMWh: 300000,
    grossImportMWh: 1600000,
    netTradeBalanceMWh: -1300000,
    activeEscrowMWh: 120000,
    totalCancellationsMWh: 4500000,
    tradeRole: 'NET_IMPORTER',
    exportSharePercent: 9.38,
  },
  {
    registryId: 'ENAGAS',
    countryCode: 'ES',
    registryName: 'Enagás GTS GdO',
    totalIssuanceMWh: 1900000,
    domesticConsumptionMWh: 800000,
    grossExportMWh: 1100000,
    grossImportMWh: 0,
    netTradeBalanceMWh: 1100000,
    activeEscrowMWh: 95000,
    totalCancellationsMWh: 800000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 57.89,
  },
  {
    registryId: 'GSE',
    countryCode: 'IT',
    registryName: 'GSE Piattaforma Biometano',
    totalIssuanceMWh: 4800000,
    domesticConsumptionMWh: 4200000,
    grossExportMWh: 600000,
    grossImportMWh: 150000,
    netTradeBalanceMWh: 450000,
    activeEscrowMWh: 85000,
    totalCancellationsMWh: 4200000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 12.5,
  },
  {
    registryId: 'EEX',
    countryCode: 'FR',
    registryName: 'EEX French Registry',
    totalIssuanceMWh: 10400000,
    domesticConsumptionMWh: 9800000,
    grossExportMWh: 700000,
    grossImportMWh: 100000,
    netTradeBalanceMWh: 600000,
    activeEscrowMWh: 160000,
    totalCancellationsMWh: 9800000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 6.73,
  },
  {
    registryId: 'AGCS',
    countryCode: 'AT',
    registryName: 'AGCS Biomethane Registry Austria',
    totalIssuanceMWh: 1200000,
    domesticConsumptionMWh: 1100000,
    grossExportMWh: 250000,
    grossImportMWh: 150000,
    netTradeBalanceMWh: 100000,
    activeEscrowMWh: 40000,
    totalCancellationsMWh: 1100000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 20.83,
  },
  {
    registryId: 'GGCS_UK',
    countryCode: 'GB',
    registryName: 'Green Gas Certification Scheme (UK)',
    totalIssuanceMWh: 6100000,
    domesticConsumptionMWh: 6100000,
    grossExportMWh: 0,
    grossImportMWh: 0,
    netTradeBalanceMWh: 0,
    activeEscrowMWh: 0,
    totalCancellationsMWh: 6100000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 0.0,
  },
  {
    registryId: 'BRUGEL_BE',
    countryCode: 'BE',
    registryName: 'Brugel / VREG Registry (Belgium)',
    totalIssuanceMWh: 850000,
    domesticConsumptionMWh: 1400000,
    grossExportMWh: 100000,
    grossImportMWh: 650000,
    netTradeBalanceMWh: -550000,
    activeEscrowMWh: 28000,
    totalCancellationsMWh: 1400000,
    tradeRole: 'NET_IMPORTER',
    exportSharePercent: 11.76,
  },
  {
    registryId: 'ENERGISVERIGE_SE',
    countryCode: 'SE',
    registryName: 'Energigas Sverige GO (Sweden)',
    totalIssuanceMWh: 2100000,
    domesticConsumptionMWh: 2800000,
    grossExportMWh: 150000,
    grossImportMWh: 850000,
    netTradeBalanceMWh: -700000,
    activeEscrowMWh: 35000,
    totalCancellationsMWh: 2800000,
    tradeRole: 'NET_IMPORTER',
    exportSharePercent: 7.14,
  },
  {
    registryId: 'PRONOVO_CH',
    countryCode: 'CH',
    registryName: 'Pronovo / VSG (Switzerland)',
    totalIssuanceMWh: 400000,
    domesticConsumptionMWh: 400000,
    grossExportMWh: 0,
    grossImportMWh: 0,
    netTradeBalanceMWh: 0,
    activeEscrowMWh: 0,
    totalCancellationsMWh: 400000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 0.0,
  },
  {
    registryId: 'GASGRID_FI',
    countryCode: 'FI',
    registryName: 'Gasgrid Finland GO (Finland)',
    totalIssuanceMWh: 550000,
    domesticConsumptionMWh: 500000,
    grossExportMWh: 80000,
    grossImportMWh: 30000,
    netTradeBalanceMWh: 50000,
    activeEscrowMWh: 12000,
    totalCancellationsMWh: 500000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 14.55,
  },
  {
    registryId: 'GASSCO_NO',
    countryCode: 'NO',
    registryName: 'Gassco / Statnett (Norway)',
    totalIssuanceMWh: 200000,
    domesticConsumptionMWh: 200000,
    grossExportMWh: 0,
    grossImportMWh: 0,
    netTradeBalanceMWh: 0,
    activeEscrowMWh: 0,
    totalCancellationsMWh: 200000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 0.0,
  },
  {
    registryId: 'URE_PL',
    countryCode: 'PL',
    registryName: 'URE / GAZ-SYSTEM (Poland)',
    totalIssuanceMWh: 950000,
    domesticConsumptionMWh: 800000,
    grossExportMWh: 200000,
    grossImportMWh: 50000,
    netTradeBalanceMWh: 150000,
    activeEscrowMWh: 30000,
    totalCancellationsMWh: 800000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 21.05,
  },
  {
    registryId: 'OTE_CZ',
    countryCode: 'CZ',
    registryName: 'OTE a.s. (Czechia)',
    totalIssuanceMWh: 450000,
    domesticConsumptionMWh: 400000,
    grossExportMWh: 90000,
    grossImportMWh: 40000,
    netTradeBalanceMWh: 50000,
    activeEscrowMWh: 15000,
    totalCancellationsMWh: 400000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 20.0,
  },
  {
    registryId: 'REN_PT',
    countryCode: 'PT',
    registryName: 'REN GdO (Portugal)',
    totalIssuanceMWh: 250000,
    domesticConsumptionMWh: 100000,
    grossExportMWh: 160000,
    grossImportMWh: 10000,
    netTradeBalanceMWh: 150000,
    activeEscrowMWh: 12000,
    totalCancellationsMWh: 100000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 64.0,
  },
  {
    registryId: 'GNI_IE',
    countryCode: 'IE',
    registryName: 'GNI Registry (Ireland)',
    totalIssuanceMWh: 300000,
    domesticConsumptionMWh: 250000,
    grossExportMWh: 60000,
    grossImportMWh: 10000,
    netTradeBalanceMWh: 50000,
    activeEscrowMWh: 8000,
    totalCancellationsMWh: 250000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 20.0,
  },
  {
    registryId: 'MEKH_HU',
    countryCode: 'HU',
    registryName: 'MEKH / CEEGEX (Hungary)',
    totalIssuanceMWh: 350000,
    domesticConsumptionMWh: 300000,
    grossExportMWh: 80000,
    grossImportMWh: 30000,
    netTradeBalanceMWh: 50000,
    activeEscrowMWh: 10000,
    totalCancellationsMWh: 300000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 22.86,
  },
  {
    registryId: 'ELERING_EE',
    countryCode: 'EE',
    registryName: 'Elering (Estonia)',
    totalIssuanceMWh: 220000,
    domesticConsumptionMWh: 90000,
    grossExportMWh: 140000,
    grossImportMWh: 10000,
    netTradeBalanceMWh: 130000,
    activeEscrowMWh: 9000,
    totalCancellationsMWh: 90000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 63.64,
  },
  {
    registryId: 'CONEXUS_LV',
    countryCode: 'LV',
    registryName: 'Conexus Baltic Grid (Latvia)',
    totalIssuanceMWh: 180000,
    domesticConsumptionMWh: 80000,
    grossExportMWh: 110000,
    grossImportMWh: 10000,
    netTradeBalanceMWh: 100000,
    activeEscrowMWh: 7000,
    totalCancellationsMWh: 80000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 61.11,
  },
  {
    registryId: 'AMBERGRID_LT',
    countryCode: 'LT',
    registryName: 'Amber Grid (Lithuania)',
    totalIssuanceMWh: 280000,
    domesticConsumptionMWh: 120000,
    grossExportMWh: 170000,
    grossImportMWh: 10000,
    netTradeBalanceMWh: 160000,
    activeEscrowMWh: 11000,
    totalCancellationsMWh: 120000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 60.71,
  },
  {
    registryId: 'OKTE_SK',
    countryCode: 'SK',
    registryName: 'OKTE (Slovakia)',
    totalIssuanceMWh: 260000,
    domesticConsumptionMWh: 220000,
    grossExportMWh: 60000,
    grossImportMWh: 20000,
    netTradeBalanceMWh: 40000,
    activeEscrowMWh: 8500,
    totalCancellationsMWh: 220000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 23.08,
  },
];

export const PROTOCOL_INTEROPERABILITY_MATRIX: ProtocolInteroperability[] = [
  {
    sourceRegistry: 'ENERGINET',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    isDirectUdbEligible: true,
    notes: 'Interconnected via Ellund IP. Full mass balance title transfer per RED III Art. 31a.',
  },
  {
    sourceRegistry: 'ENERGINET',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    isDirectUdbEligible: true,
    notes: 'Seamless cross-border transfer into Dutch ERE compliance system.',
  },
  {
    sourceRegistry: 'DENA',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    isDirectUdbEligible: true,
    notes: 'Direct transit between THE and TTF hubs via Oude Statenzijl / Vlieghuis.',
  },
  {
    sourceRegistry: 'ENAGAS',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Transit across VIP Pirineos / France into German compliance quotas.',
  },
  {
    sourceRegistry: 'ENAGAS',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Active Iberian export pathway under Real Decreto 376/2022.',
  },
  {
    sourceRegistry: 'REN_PT',
    targetRegistry: 'ENAGAS',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Iberian VIP interconnection (Valença do Minho / Campo Maior).',
  },
  {
    sourceRegistry: 'GSE',
    targetRegistry: 'DENA',
    supportedProtocols: ['AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER', 'BILATERAL_RECOGNITION'],
    isDirectUdbEligible: true,
    notes: 'Alpine corridor transit via Passo Gries / Wallbach.',
  },
  {
    sourceRegistry: 'EEX',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Franco-German grid interconnection at Medelsheim / Obergailbach.',
  },
  {
    sourceRegistry: 'BRUGEL_BE',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Zeebrugge-THE transit via Eynatten / Lichtenbusch IP.',
  },
  {
    sourceRegistry: 'BRUGEL_BE',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Direct Belux-TTF cross-border interconnection via Zelzate / Hilvarenbeek.',
  },
  {
    sourceRegistry: 'AGCS',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'CEGH to THE connection via Oberkappel / Überackern.',
  },
  {
    sourceRegistry: 'OTE_CZ',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'NET4GAS to THE via Brandov / Waidhaus.',
  },
  {
    sourceRegistry: 'URE_PL',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'GAZ-SYSTEM to THE via Mallnow IP and Lasów.',
  },
  {
    sourceRegistry: 'ELERING_EE',
    targetRegistry: 'CONEXUS_LV',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Common Baltic single entry-exit zone via Karksi IP.',
  },
  {
    sourceRegistry: 'CONEXUS_LV',
    targetRegistry: 'AMBERGRID_LT',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Baltic zone interconnection via Kiemėnai IP.',
  },
  {
    sourceRegistry: 'AMBERGRID_LT',
    targetRegistry: 'URE_PL',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'GIPL pipeline interconnecting Baltics to Continental European market.',
  },
  {
    sourceRegistry: 'GASGRID_FI',
    targetRegistry: 'ELERING_EE',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Balticconnector offshore pipeline connecting Finland to Baltic single gas zone.',
  },
  {
    sourceRegistry: 'ENERGISVERIGE_SE',
    targetRegistry: 'ENERGINET',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Dragør / Öresund transmission interconnector.',
  },
  {
    sourceRegistry: 'OKTE_SK',
    targetRegistry: 'AGCS',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Baumgarten interconnection connecting Slovakia to Austria CEGH.',
  },
  {
    sourceRegistry: 'MEKH_HU',
    targetRegistry: 'AGCS',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'HAG interconnector (Mosonmagyaróvár / Baumgarten).',
  },
  {
    sourceRegistry: 'GNI_IE',
    targetRegistry: 'GGCS_UK',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'SNIP / IC1 / IC2 interconnectors with Great Britain.',
  },
  {
    sourceRegistry: 'GGCS_UK',
    targetRegistry: 'DENA',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'BLOCKED per Reg (EU) 2024/2792 Art. 15(4) unless UK-EU bilateral treaty is enacted.',
  },
  {
    sourceRegistry: 'GGCS_UK',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'BLOCKED for BBL pipeline transit without mutual recognition under RED III Art. 31a.',
  },
  {
    sourceRegistry: 'PRONOVO_CH',
    targetRegistry: 'DENA',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'Non-EU Swiss Grid transit via Wallbach requires bilateral mutual recognition agreement.',
  },
  {
    sourceRegistry: 'GASSCO_NO',
    targetRegistry: 'DENA',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'Norse offshore landing points require bilateral agreement under RED III Art. 31a.',
  },
];
