import {
  RegistryId,
  RegistryMetadata,
  InjectionBatch,
  RegistryAccount,
  BalanceOfTradeSummary,
  ProtocolInteroperability,
} from './types';

export const REGISTRY_METADATA_TABLE: Record<RegistryId, RegistryMetadata> = {
  DENA: {
    id: 'DENA',
    name: 'dena Biogasregister',
    operator: 'Deutsche Energie-Agentur GmbH (dena) / UBA',
    countryCode: 'DE',
    countryName: 'Germany',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    hubConnection: 'Trading Hub Europe (THE)',
    statutoryLegalBasis: '§37a BImSchG / 38. BImSchV & Biokraft-NachV',
    udbDirectIntegration: true,
  },
  VERTICER: {
    id: 'VERTICER',
    name: 'VertiCer & NEa REV',
    operator: 'VertiCer B.V. / Nederlandse Emissieautoriteit (NEa)',
    countryCode: 'NL',
    countryName: 'Netherlands',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    hubConnection: 'Title Transfer Facility (TTF)',
    statutoryLegalBasis: 'Wet milieubeheer / Regeling energie vervoer (ERE)',
    udbDirectIntegration: true,
  },
  ENERGINET: {
    id: 'ENERGINET',
    name: 'Energinet Biometangasregister',
    operator: 'Energinet Gas TSO A/S',
    countryCode: 'DK',
    countryName: 'Denmark',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Danish Gas System / Ellund & Dragør IPs',
    statutoryLegalBasis: 'Danish Natural Gas Supply Act & VE-Direktiv',
    udbDirectIntegration: true,
  },
  ENAGAS: {
    id: 'ENAGAS',
    name: 'Enagás GTS Sistema de Garantías de Origen',
    operator: 'Enagás GTS S.A.',
    countryCode: 'ES',
    countryName: 'Spain',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Punto Virtual de Balance (PVB)',
    statutoryLegalBasis: 'Real Decreto 376/2022 & Circular 1/2022 CNMC',
    udbDirectIntegration: true,
  },
  GSE: {
    id: 'GSE',
    name: 'GSE Piattaforma Biometano',
    operator: 'Gestore dei Servizi Energetici GSE S.p.A. / SNAM',
    countryCode: 'IT',
    countryName: 'Italy',
    isEUSingleArea: true,
    primaryProtocols: ['AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER', 'BILATERAL_RECOGNITION'],
    hubConnection: 'Punto di Scambio Virtuale (PSV)',
    statutoryLegalBasis: 'D.M. 02/03/2018 & PNRR D.M. 15/09/2022',
    udbDirectIntegration: true,
  },
  EEX: {
    id: 'EEX',
    name: 'EEX French National Biomethane Registry',
    operator: 'European Energy Exchange AG (Powernext) / DGDDI',
    countryCode: 'FR',
    countryName: 'France',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Point d’Échange de Gaz (PEG)',
    statutoryLegalBasis: 'Code de l’énergie Art. L.446-24 / TIRUERT',
    udbDirectIntegration: true,
  },
  AGCS: {
    id: 'AGCS',
    name: 'AGCS Biomethane Registry Austria',
    operator: 'AGCS Gas Clearing and Settlement AG / E-Control',
    countryCode: 'AT',
    countryName: 'Austria',
    isEUSingleArea: true,
    primaryProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    hubConnection: 'Central European Gas Hub (CEGH)',
    statutoryLegalBasis: 'Erneuerbaren-Ausbau-Gesetz (EAG)',
    udbDirectIntegration: true,
  },
  GGCS_UK: {
    id: 'GGCS_UK',
    name: 'Green Gas Certification Scheme (GGCS) / RTFO',
    operator: 'Renewable Energy Assurance Ltd (REAL) / DfT',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    isEUSingleArea: false,
    primaryProtocols: ['DOMESTIC_ONLY', 'BILATERAL_RECOGNITION'],
    hubConnection: 'National Balancing Point (NBP)',
    statutoryLegalBasis: 'Energy Act 2004 / RTFO Order 2007 (SI 2007/3072)',
    udbDirectIntegration: false,
  },
};

export const BASELINE_INJECTION_BATCHES: InjectionBatch[] = [
  // --- DENMARK (Energinet) - High Export Surplus ---
  {
    id: 'BATCH-DK-2026-001',
    plantId: 'PLANT-DK-GLANSAGER',
    plantName: 'Nature Energy Glansager',
    originCountry: 'DK',
    registryId: 'ENERGINET',
    injectionPointId: 'DK-IP-ELLUND-01',
    meteringPeriod: { startDate: '2026-08-01', endDate: '2026-08-15' },
    volumeMWh: 48500,
    volumeNm3: 4490740,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Manure & Agricultural Slurry',
    feedstockDetails: '75% Liquid bovine manure, 25% deep litter straw',
    annexClassification: 'IX_A',
    verifiedCI: -95.2,
    sustainabilityProofId: 'ISCC-EU-POS-2026-DK-99210',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-DK-2026-0891',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-16T08:30:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DK-2026-002',
    plantId: 'PLANT-DK-HOLSTED',
    plantName: 'Nature Energy Holsted',
    originCountry: 'DK',
    registryId: 'ENERGINET',
    injectionPointId: 'DK-IP-ELLUND-02',
    meteringPeriod: { startDate: '2026-07-15', endDate: '2026-07-31' },
    volumeMWh: 62000,
    volumeNm3: 5767440,
    grossCalorificValueKwhNm3: 10.75,
    feedstockCategory: 'Manure & Organic Residues',
    feedstockDetails: '80% Swine/Cattle slurry, 20% certified organic waste',
    annexClassification: 'IX_A',
    verifiedCI: -88.4,
    sustainabilityProofId: 'REDC-EU-POS-2026-DK-44120',
    certificationScheme: 'REDcert EU',
    udbRegistrationId: 'UDB-DK-2026-1044',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-08-02T09:15:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DK-2026-003',
    plantId: 'PLANT-DK-VINKEL',
    plantName: 'Vinkel Bioenergi',
    originCountry: 'DK',
    registryId: 'ENERGINET',
    injectionPointId: 'DK-IP-SKIVE-01',
    meteringPeriod: { startDate: '2026-07-01', endDate: '2026-07-15' },
    volumeMWh: 54000,
    volumeNm3: 5000000,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Manure & Catch Crops',
    feedstockDetails: 'Manure slurry with catch crops and straw residues',
    annexClassification: 'IX_A',
    verifiedCI: -92.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-DK-88319',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-DK-2026-0772',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-07-18T10:00:00Z',
    status: 'ISSUED',
  },

  // --- GERMANY (dena) - High Domestic Demand & Importer ---
  {
    id: 'BATCH-DE-2026-001',
    plantId: 'PLANT-DE-WIETZENDORF',
    plantName: 'Biogas Wietzendorf',
    originCountry: 'DE',
    registryId: 'DENA',
    injectionPointId: 'DE-IP-THE-WIETZ-01',
    meteringPeriod: { startDate: '2026-06-15', endDate: '2026-06-30' },
    volumeMWh: 28000,
    volumeNm3: 2568800,
    grossCalorificValueKwhNm3: 10.9,
    feedstockCategory: 'Liquid Bovine Manure',
    feedstockDetails: '100% Raw cattle manure with closed digestate storage',
    annexClassification: 'IX_A',
    verifiedCI: -102.5,
    sustainabilityProofId: 'REDC-EU-POS-2026-DE-11029',
    certificationScheme: 'REDcert EU',
    udbRegistrationId: 'UDB-DE-2026-4412',
    gridInterconnectionStatus: 'DSO_DISTRIBUTION',
    issuedAt: '2026-07-05T11:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DE-2026-002',
    plantId: 'PLANT-DE-GUSTROW',
    plantName: 'Güstrow Biomethane Refinery',
    originCountry: 'DE',
    registryId: 'DENA',
    injectionPointId: 'DE-IP-THE-GUST-02',
    meteringPeriod: { startDate: '2026-06-01', endDate: '2026-06-15' },
    volumeMWh: 75000,
    volumeNm3: 6880730,
    grossCalorificValueKwhNm3: 10.9,
    feedstockCategory: 'Agricultural Residues & Silage',
    feedstockDetails: 'Maize silage and agricultural crop residues',
    annexClassification: 'CROP',
    verifiedCI: 24.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-DE-00384',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-DE-2026-0038',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-06-20T12:30:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-DE-2026-003',
    plantId: 'PLANT-DE-KONNERN',
    plantName: 'Biomethan Könnern',
    originCountry: 'DE',
    registryId: 'DENA',
    injectionPointId: 'DE-IP-THE-KONN-01',
    meteringPeriod: { startDate: '2026-05-15', endDate: '2026-05-31' },
    volumeMWh: 42000,
    volumeNm3: 3888880,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Sugar Beet Pulp & Agro Residues',
    feedstockDetails: 'Sugar beet pulp, straw, and agricultural byproduct residues',
    annexClassification: 'IX_A',
    verifiedCI: 14.2,
    sustainabilityProofId: 'REDC-EU-POS-2026-DE-21901',
    certificationScheme: 'REDcert EU',
    udbRegistrationId: 'UDB-DE-2026-2190',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-06-05T14:20:00Z',
    status: 'ISSUED',
  },

  // --- NETHERLANDS (VertiCer) - Importer ---
  {
    id: 'BATCH-NL-2026-001',
    plantId: 'PLANT-NL-ATTERO-WIJSTER',
    plantName: 'Attero Biogas Wijster',
    originCountry: 'NL',
    registryId: 'VERTICER',
    injectionPointId: 'NL-IP-GTS-WIJST-01',
    meteringPeriod: { startDate: '2026-05-01', endDate: '2026-05-15' },
    volumeMWh: 38000,
    volumeNm3: 3518510,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Organic Municipal Biowaste',
    feedstockDetails: 'Source-separated household organic biowaste (VGF)',
    annexClassification: 'IX_A',
    verifiedCI: 16.8,
    sustainabilityProofId: 'ISCC-EU-POS-2026-NL-30211',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-NL-2026-3021',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-05-20T15:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-NL-2026-002',
    plantId: 'PLANT-NL-VIERVERLATEN',
    plantName: 'Suiker Unie Vierverlaten',
    originCountry: 'NL',
    registryId: 'VERTICER',
    injectionPointId: 'NL-IP-GTS-VIERV-01',
    meteringPeriod: { startDate: '2026-04-15', endDate: '2026-04-30' },
    volumeMWh: 45000,
    volumeNm3: 4166660,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Agro-Industrial Byproducts',
    feedstockDetails: 'Sugar beet washing water and processing pulp residues',
    annexClassification: 'IX_A',
    verifiedCI: 12.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-NL-11024',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-NL-2026-1102',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-05-05T09:40:00Z',
    status: 'ISSUED',
  },

  // --- SPAIN (Enagás) - Net Exporter ---
  {
    id: 'BATCH-ES-2026-001',
    plantId: 'PLANT-ES-VALDEMINGOMEZ',
    plantName: 'Parque Tecnológico Valdemingómez',
    originCountry: 'ES',
    registryId: 'ENAGAS',
    injectionPointId: 'ES-IP-MADRID-01',
    meteringPeriod: { startDate: '2026-04-01', endDate: '2026-04-15' },
    volumeMWh: 36000,
    volumeNm3: 3333330,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Urban Organic Fraction (FORSU)',
    feedstockDetails: 'Biomethanization of source-separated municipal organic waste',
    annexClassification: 'IX_A',
    verifiedCI: 19.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-ES-77142',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-ES-2026-7714',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-04-20T16:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-ES-2026-002',
    plantId: 'PLANT-ES-TORRE-SANTAMARIA',
    plantName: 'Granja Torre Santamaría',
    originCountry: 'ES',
    registryId: 'ENAGAS',
    injectionPointId: 'ES-IP-LLEIDA-01',
    meteringPeriod: { startDate: '2026-03-15', endDate: '2026-03-31' },
    volumeMWh: 22000,
    volumeNm3: 2018340,
    grossCalorificValueKwhNm3: 10.9,
    feedstockCategory: 'Dairy Cattle Manure',
    feedstockDetails: '100% Dairy slurry with methane capture and cover',
    annexClassification: 'IX_A',
    verifiedCI: -106.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-ES-04288',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-ES-2026-0428',
    gridInterconnectionStatus: 'DSO_DISTRIBUTION',
    issuedAt: '2026-04-05T11:20:00Z',
    status: 'ISSUED',
  },

  // --- ITALY (GSE) - Emerging Exporter / Balanced ---
  {
    id: 'BATCH-IT-2026-001',
    plantId: 'PLANT-IT-MONTELLO',
    plantName: 'Montello Biometano S.p.A.',
    originCountry: 'IT',
    registryId: 'GSE',
    injectionPointId: 'IT-IP-SNAM-MONT-01',
    meteringPeriod: { startDate: '2026-03-01', endDate: '2026-03-15' },
    volumeMWh: 68000,
    volumeNm3: 6296290,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Organic Municipal Fraction (FORSU)',
    feedstockDetails: 'Source-separated kitchen waste from Lombardy region',
    annexClassification: 'IX_A',
    verifiedCI: 15.2,
    sustainabilityProofId: '2BS-POS-2026-IT-01129',
    certificationScheme: '2BSvs',
    udbRegistrationId: 'UDB-IT-2026-0112',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-03-20T10:10:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-IT-2026-002',
    plantId: 'PLANT-IT-CALIMERA',
    plantName: 'Calimera Biometano',
    originCountry: 'IT',
    registryId: 'GSE',
    injectionPointId: 'IT-IP-SNAM-PUGL-01',
    meteringPeriod: { startDate: '2026-02-15', endDate: '2026-02-28' },
    volumeMWh: 25000,
    volumeNm3: 2314810,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Olive Mill Wastewater & Residues',
    feedstockDetails: 'Olive pomace and agricultural residues from Puglia',
    annexClassification: 'IX_A',
    verifiedCI: 8.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-IT-44018',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-IT-2026-4401',
    gridInterconnectionStatus: 'DSO_DISTRIBUTION',
    issuedAt: '2026-03-05T12:00:00Z',
    status: 'ISSUED',
  },

  // --- FRANCE (EEX) - Domestic Balanced ---
  {
    id: 'BATCH-FR-2026-001',
    plantId: 'PLANT-FR-EQUIBIO',
    plantName: 'EquiBio Châteaubriant',
    originCountry: 'FR',
    registryId: 'EEX',
    injectionPointId: 'FR-IP-GRT-CHAT-01',
    meteringPeriod: { startDate: '2026-02-01', endDate: '2026-02-15' },
    volumeMWh: 26000,
    volumeNm3: 2407400,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Agricultural Waste & Manure',
    feedstockDetails: 'Bovine manure and agricultural intermediate crops (CIVE)',
    annexClassification: 'IX_A',
    verifiedCI: -68.0,
    sustainabilityProofId: '2BS-POS-2026-FR-11883',
    certificationScheme: '2BSvs',
    udbRegistrationId: 'UDB-FR-2026-1188',
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-02-20T13:15:00Z',
    status: 'ISSUED',
  },

  // --- UNITED KINGDOM (GGCS_UK) - Non-EU Grid Injection ---
  {
    id: 'BATCH-GB-2026-001',
    plantId: 'PLANT-GB-POUNDBURY',
    plantName: 'Rainbarrow Farm Poundbury',
    originCountry: 'GB',
    registryId: 'GGCS_UK',
    injectionPointId: 'GB-IP-NATGAS-DORSET-01',
    meteringPeriod: { startDate: '2026-01-15', endDate: '2026-01-31' },
    volumeMWh: 22000,
    volumeNm3: 2037030,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Commercial Food Waste & Residues',
    feedstockDetails: 'Food waste collected from commercial retailers and local farming residues',
    annexClassification: 'IX_A',
    verifiedCI: 23.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-GB-88122',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: null, // Non-EU grid injection excluded from UDB mass balance
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-02-05T09:00:00Z',
    status: 'ISSUED',
  },
  {
    id: 'BATCH-GB-2026-002',
    plantId: 'PLANT-GB-LEEMING',
    plantName: 'Leeming Biogas',
    originCountry: 'GB',
    registryId: 'GGCS_UK',
    injectionPointId: 'GB-IP-NATGAS-YORK-01',
    meteringPeriod: { startDate: '2026-01-01', endDate: '2026-01-15' },
    volumeMWh: 35000,
    volumeNm3: 3240740,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Industrial Food Processing Waste',
    feedstockDetails: 'Confectionery and bakery food processing organic waste',
    annexClassification: 'IX_A',
    verifiedCI: 17.5,
    sustainabilityProofId: 'ISCC-EU-POS-2026-GB-90219',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: null,
    gridInterconnectionStatus: 'TSO_HIGH_PRESSURE',
    issuedAt: '2026-01-20T14:30:00Z',
    status: 'ISSUED',
  },

  // --- OFF-GRID / SEGREGATED FACILITY (Sweden Bio-LNG) ---
  {
    id: 'BATCH-SE-2026-001',
    plantId: 'PLANT-SE-SKELLEFTEA',
    plantName: 'Nordic Bio-LNG Skellefteå',
    originCountry: 'SE',
    registryId: 'AGCS',
    injectionPointId: 'SE-OFFGRID-LNG-01',
    meteringPeriod: { startDate: '2026-01-01', endDate: '2026-01-31' },
    volumeMWh: 15000,
    volumeNm3: 1388880,
    grossCalorificValueKwhNm3: 10.8,
    feedstockCategory: 'Manure & Forestry Industrial Residues',
    feedstockDetails: 'Off-grid liquefaction directly into cryogenic ISO containers',
    annexClassification: 'IX_A',
    verifiedCI: -80.0,
    sustainabilityProofId: 'ISCC-EU-POS-2026-SE-99011',
    certificationScheme: 'ISCC EU',
    udbRegistrationId: 'UDB-SE-2026-9901',
    gridInterconnectionStatus: 'OFF_GRID_SEGREGATED',
    issuedAt: '2026-02-05T17:00:00Z',
    status: 'ISSUED',
  },
];

export const BASELINE_ACCOUNTS: RegistryAccount[] = [
  {
    registryId: 'ENERGINET',
    registryName: 'Energinet Biometangasregister',
    countryCode: 'DK',
    accountHolderId: 'ACC-DK-DESK-01',
    accountHolderName: 'Continental Biomethane Trading Desk ApS',
    currentBalanceMWh: 164500,
    availableForExportMWh: 142000,
    reservedEscrowMWh: 22500,
    activeBatchesCount: 3,
  },
  {
    registryId: 'DENA',
    registryName: 'dena Biogasregister',
    countryCode: 'DE',
    accountHolderId: 'ACC-DE-DESK-01',
    accountHolderName: 'Pan-European Clean Fuels Trading GmbH',
    currentBalanceMWh: 145000,
    availableForExportMWh: 35000,
    reservedEscrowMWh: 12000,
    activeBatchesCount: 3,
  },
  {
    registryId: 'VERTICER',
    registryName: 'VertiCer & NEa REV',
    countryCode: 'NL',
    accountHolderId: 'ACC-NL-DESK-01',
    accountHolderName: 'Low Carbon Commodities B.V.',
    currentBalanceMWh: 83000,
    availableForExportMWh: 18000,
    reservedEscrowMWh: 8500,
    activeBatchesCount: 2,
  },
  {
    registryId: 'ENAGAS',
    registryName: 'Enagás GTS Sistema de GdO',
    countryCode: 'ES',
    accountHolderId: 'ACC-ES-DESK-01',
    accountHolderName: 'Iberian Renewable Gas Trading S.L.',
    currentBalanceMWh: 58000,
    availableForExportMWh: 45000,
    reservedEscrowMWh: 6000,
    activeBatchesCount: 2,
  },
  {
    registryId: 'GSE',
    registryName: 'GSE Piattaforma Biometano',
    countryCode: 'IT',
    accountHolderId: 'ACC-IT-DESK-01',
    accountHolderName: 'Trans-Alpine Gas Desk S.r.l.',
    currentBalanceMWh: 93000,
    availableForExportMWh: 40000,
    reservedEscrowMWh: 15000,
    activeBatchesCount: 2,
  },
  {
    registryId: 'EEX',
    registryName: 'EEX French Registry',
    countryCode: 'FR',
    accountHolderId: 'ACC-FR-DESK-01',
    accountHolderName: 'Hexagone Biométhane SAS',
    currentBalanceMWh: 58000,
    availableForExportMWh: 12000,
    reservedEscrowMWh: 4000,
    activeBatchesCount: 1,
  },
  {
    registryId: 'GGCS_UK',
    registryName: 'Green Gas Certification Scheme (UK)',
    countryCode: 'GB',
    accountHolderId: 'ACC-GB-DESK-01',
    accountHolderName: 'UK Renewable Fuels Desk Ltd',
    currentBalanceMWh: 57000,
    availableForExportMWh: 57000,
    reservedEscrowMWh: 0,
    activeBatchesCount: 2,
  },
];

export const BASELINE_BALANCE_OF_TRADE: BalanceOfTradeSummary[] = [
  {
    registryId: 'ENERGINET',
    countryCode: 'DK',
    registryName: 'Energinet Biometangasregister',
    totalIssuanceMWh: 6800000,
    domesticConsumptionMWh: 1200000,
    grossExportMWh: 5600000,
    grossImportMWh: 0,
    netTradeBalanceMWh: 5600000,
    activeEscrowMWh: 240000,
    totalCancellationsMWh: 1200000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 82.35,
  },
  {
    registryId: 'DENA',
    countryCode: 'DE',
    registryName: 'dena Biogasregister',
    totalIssuanceMWh: 11800000,
    domesticConsumptionMWh: 14600000,
    grossExportMWh: 600000,
    grossImportMWh: 3400000,
    netTradeBalanceMWh: -2800000,
    activeEscrowMWh: 450000,
    totalCancellationsMWh: 14600000,
    tradeRole: 'NET_IMPORTER',
    exportSharePercent: 5.08,
  },
  {
    registryId: 'VERTICER',
    countryCode: 'NL',
    registryName: 'VertiCer / NEa REV',
    totalIssuanceMWh: 3200000,
    domesticConsumptionMWh: 4500000,
    grossExportMWh: 300000,
    grossImportMWh: 1600000,
    netTradeBalanceMWh: -1300000,
    activeEscrowMWh: 120000,
    totalCancellationsMWh: 4500000,
    tradeRole: 'NET_IMPORTER',
    exportSharePercent: 9.38,
  },
  {
    registryId: 'ENAGAS',
    countryCode: 'ES',
    registryName: 'Enagás GTS GdO',
    totalIssuanceMWh: 1900000,
    domesticConsumptionMWh: 800000,
    grossExportMWh: 1100000,
    grossImportMWh: 0,
    netTradeBalanceMWh: 1100000,
    activeEscrowMWh: 95000,
    totalCancellationsMWh: 800000,
    tradeRole: 'NET_EXPORTER',
    exportSharePercent: 57.89,
  },
  {
    registryId: 'GSE',
    countryCode: 'IT',
    registryName: 'GSE Piattaforma Biometano',
    totalIssuanceMWh: 4200000,
    domesticConsumptionMWh: 4000000,
    grossExportMWh: 300000,
    grossImportMWh: 100000,
    netTradeBalanceMWh: 200000,
    activeEscrowMWh: 80000,
    totalCancellationsMWh: 4000000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 7.14,
  },
  {
    registryId: 'EEX',
    countryCode: 'FR',
    registryName: 'EEX French Registry',
    totalIssuanceMWh: 9500000,
    domesticConsumptionMWh: 9200000,
    grossExportMWh: 400000,
    grossImportMWh: 100000,
    netTradeBalanceMWh: 300000,
    activeEscrowMWh: 150000,
    totalCancellationsMWh: 9200000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 4.21,
  },
  {
    registryId: 'AGCS',
    countryCode: 'AT',
    registryName: 'AGCS Biomethane Registry Austria',
    totalIssuanceMWh: 1200000,
    domesticConsumptionMWh: 1100000,
    grossExportMWh: 250000,
    grossImportMWh: 150000,
    netTradeBalanceMWh: 100000,
    activeEscrowMWh: 40000,
    totalCancellationsMWh: 1100000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 20.83,
  },
  {
    registryId: 'GGCS_UK',
    countryCode: 'GB',
    registryName: 'Green Gas Certification Scheme (UK)',
    totalIssuanceMWh: 3800000,
    domesticConsumptionMWh: 3800000,
    grossExportMWh: 0,
    grossImportMWh: 0,
    netTradeBalanceMWh: 0,
    activeEscrowMWh: 0,
    totalCancellationsMWh: 3800000,
    tradeRole: 'BALANCED_DOMESTIC',
    exportSharePercent: 0.0,
  },
];

export const PROTOCOL_INTEROPERABILITY_MATRIX: ProtocolInteroperability[] = [
  {
    sourceRegistry: 'ENERGINET',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    isDirectUdbEligible: true,
    notes: 'Interconnected via Ellund IP. Full mass balance title transfer per RED III Art. 31a.',
  },
  {
    sourceRegistry: 'ENERGINET',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    isDirectUdbEligible: true,
    notes: 'Seamless cross-border transfer into Dutch ERE compliance system.',
  },
  {
    sourceRegistry: 'DENA',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER', 'AIB_EECS_GAS'],
    isDirectUdbEligible: true,
    notes: 'Direct transit between THE and TTF hubs via Oude Statenzijl / Vlieghuis.',
  },
  {
    sourceRegistry: 'ENAGAS',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Transit across VIP Pirineos / France into German compliance quotas.',
  },
  {
    sourceRegistry: 'ENAGAS',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['ERGAR_COO', 'AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Active Iberian export pathway under Real Decreto 376/2022.',
  },
  {
    sourceRegistry: 'GSE',
    targetRegistry: 'DENA',
    supportedProtocols: ['AIB_EECS_GAS', 'UDB_DIRECT_TRANSFER', 'BILATERAL_RECOGNITION'],
    isDirectUdbEligible: true,
    notes: 'Alpine corridor transit via Passo Gries / Wallbach.',
  },
  {
    sourceRegistry: 'EEX',
    targetRegistry: 'DENA',
    supportedProtocols: ['ERGAR_COO', 'UDB_DIRECT_TRANSFER'],
    isDirectUdbEligible: true,
    notes: 'Franco-German grid interconnection at Medelsheim / Obergailbach.',
  },
  {
    sourceRegistry: 'GGCS_UK',
    targetRegistry: 'DENA',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'BLOCKED per Reg (EU) 2024/2792 Art. 15(4) unless UK-EU bilateral treaty is enacted.',
  },
  {
    sourceRegistry: 'GGCS_UK',
    targetRegistry: 'VERTICER',
    supportedProtocols: ['BILATERAL_RECOGNITION', 'DOMESTIC_ONLY'],
    isDirectUdbEligible: false,
    notes: 'BLOCKED for BBL pipeline transit without mutual recognition under RED III Art. 31a.',
  },
];
